# IM 分钟混合贡献的日内季节性

本文使用交易日和日内分钟两个索引；符号在首次使用时定义，代码字段保持现有名称。收益及其周期尺度沿用 Boudt 等收益过滤文献的符号约定，其他文献须按定义映射，不能仅凭相同字母认定是同一对象。完整依据与方法边界见[项目符号与方法说明](../volatility_research/README.md)。

| 符号 | 含义 | 代码对应或用途 |
|---|---|---|
| $t$；$i=1,\ldots,M$ | 交易日序号；全天分钟位置，$M=240$ | 09:31 为 $i=1$，13:01 为 $i=121$ |
| $L$ | 回望交易日数，取 30、60、120、360 | `lookback_windows` |
| $r_{t,i}$ | 分钟对数收益率 | `log_return` |
| $f_{t,i}$；$f_{t,i}^{2}$ | 收益的标准差周期；相应方差周期，约定 $M^{-1}\sum_i f_{t,i}^{2}=1$ | 用于区分统计对象；本 Notebook 未直接估计 $f$ |
| $\widehat f_{t,i}$；$r^f_{t,i}=r_{t,i}/\widehat f_{t,i}$ | 估计的标准差周期；据此过滤的收益 | 帽号表示估计量；不要与下文旧收益调整构造混用 |
| $RV_t$；$BV_t$（亦称 BPV） | 收益平方和；绝对收益相邻乘积构成的实现双幂变差 | 沿用文献常见名称；本项目只在同一 Session 内配对 |
| $b_{t,i}$ | $\frac{\pi}{2}\lvert r_{t,i}\rvert\lvert r_{t,i-1}\rvert$，仅限有效同 Session 配对 | `bpv_contribution`；$b$ 是本项目对 BV 求和项的简称 |
| $c^{\mathrm{mix}}_{t,i}$ | 首分钟收益平方、其余分钟 $b_{t,i}$ 构成的混合贡献 | `variance_contribution` |
| $x^{\mathrm{mix}}_{t,i}$ | 混合贡献除以当日平均混合贡献 | `daily_shape_matrix` |
| $\widehat g^{\mathrm{mix},(L)}_{t,i}$ | 过去 $L$ 个交易日估计的混合贡献季节因子 | `seasonality_by_lookback[L]`；输出字段 `variance_seasonality` |

$c$、$x$、$g$ 及上标 $\mathrm{mix}$ 是本项目为现有混合构造明确约定的记号，并非文献统一命名。$\widehat g^{\mathrm{mix},(L)}$ 调整的是贡献形状，不能由其构造直接断言它就是 $f^2$。

#### Cell 1：导入依赖，设置路径和滚动窗口。

In [1]:
import pathlib
import sys

project_markers = [".git", ".env", "config/settings.py"]
current_path = pathlib.Path.cwd().resolve()

for candidate_root in [current_path, *current_path.parents]:
    if all((candidate_root / marker).exists() for marker in project_markers):
        sys.path.insert(0, str(candidate_root))
        sys.path.insert(0, str(candidate_root / "02_Futures_Lakehouse"))
        break
else:
    raise RuntimeError("未找到项目根目录")

from config.settings import settings
from config.data_contracts import TRADE_CALENDAR_SCHEMA, arrow_to_pandas
from a00_03_notebook_schema_browser import display_schema_metadata

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.dataset as ds
import pyarrow.parquet as pq

research_dir = (
    candidate_root / "01_project_collection/JQ_strategy/draft_experiments_v2"
)
source_path = research_dir / "im_main_continuous_1m.parquet"
lookback_windows = (30, 60, 120, 360)  # 单位：交易日
as_of_at = pd.Timestamp.now(tz="Asia/Shanghai")

#### Cell 2：读取实际合约的原始收盘价，按交易日和时间排序。

In [11]:
minute_input_schema = pa.schema([
    pa.field("contract_code", pa.string(), nullable=False),
    pa.field("trading_date", pa.date32(), nullable=False),
    pa.field("session_number", pa.int8(), nullable=False),
    pa.field("bar_at", pa.timestamp("us", tz="Asia/Shanghai"), nullable=False),
    pa.field("open", pa.float64(), nullable=False),
    pa.field("close", pa.float64(), nullable=False),
])

minute_table = pq.read_table(source_path, columns=minute_input_schema.names)
minute_df = (
    minute_table.cast(minute_input_schema)
    .to_pandas(types_mapper=pd.ArrowDtype)
    .sort_values(["trading_date", "bar_at"])
    .reset_index(drop=True)
)
minute_df[["open", "close"]] = minute_df[["open", "close"]].astype("float64")

#### Cell 3：读取完整交易日序列，建立每天 240 个分钟位置，供后续矩阵对齐。

In [12]:
display_schema_metadata([TRADE_CALENDAR_SCHEMA])

calendar_table_name = (
    TRADE_CALENDAR_SCHEMA.metadata[b"table_name"].decode("utf-8")
)
calendar_primary_key = (
    TRADE_CALENDAR_SCHEMA.metadata[b"primary_key"].decode("utf-8").split(",")
)
calendar_partition_columns = (
    TRADE_CALENDAR_SCHEMA.metadata[b"partition_columns"]
    .decode("utf-8").split(",")
)
calendar_read_schema = pa.schema([
    TRADE_CALENDAR_SCHEMA.field("calendar_date"),
])
calendar_partitioning = ds.partitioning(
    pa.schema([
        TRADE_CALENDAR_SCHEMA.field(column)
        for column in calendar_partition_columns
    ]),
    flavor="hive",
)

calendar_dataset = ds.dataset(
    settings.futures_lake_root / "silver" / calendar_table_name,
    format="parquet",
    partitioning=calendar_partitioning,
)
calendar_table = calendar_dataset.to_table(
    columns=calendar_read_schema.names,
    filter=(
        (ds.field("calendar_date") >= minute_df["trading_date"].min())
        & (ds.field("calendar_date") <= minute_df["trading_date"].max())
        & ds.field("is_trading_day")
    ),
)
calendar_df = arrow_to_pandas(calendar_table, calendar_read_schema)
calendar_df = calendar_df.sort_values(calendar_primary_key)

trading_dates = pd.Index(
    calendar_df["calendar_date"].tolist(),
    name="trading_date",
)
minute_slots = pd.Index([
    *pd.date_range("2000-01-01 09:31", "2000-01-01 11:30", freq="min").time,
    *pd.date_range("2000-01-01 13:01", "2000-01-01 15:00", freq="min").time,
], name="minute_slot")

VBox(children=(Dropdown(description='Schema：', layout=Layout(margin='24px 0 4px 0', max_width='100%', width='7…

### Session 首分钟的收益起点

收益按“交易日＋合约＋Session”分组计算。09:31 和 13:01
分别对应全天分钟位置 $i=1$ 和 $i=121$，是各 Session 的第一根分钟线，
没有组内前一分钟的 close。因此直接 diff() 会产生空值。
这属于计算边界，不代表源数据漏采。

记 $P_{t,i}$、$P^{\mathrm{open}}_{t,i}$ 分别为第 $t$ 个交易日、第 $i$ 根分钟线的原始收盘价和开盘价。
首分钟使用本根分钟线的原始 open 作为收益起点：

$$
r_{t,i}=\log(P_{t,i}/P^{\mathrm{open}}_{t,i}),\qquad i\in\{1,121\}.
$$

其余分钟使用同一 Session 内相邻收盘价的对数差：

$$
r_{t,i}=\log(P_{t,i}/P_{t,i-1}).
$$

这样不会把隔夜或午休期间的价格变化混入一分钟收益。
open 仅用于 Session 首分钟；盘中时间缺口仍保留为空，不套用这一处理。

#### Cell 4：在同一交易日、合约和 Session 内计算一分钟收益

In [14]:
import datetime as dt

minute_df["minute_slot"] = minute_df["bar_at"].dt.time
minute_df["log_close"] = np.log(
    minute_df["close"].where(minute_df["close"] > 0)
)

minute_groups = minute_df.groupby(
    ["trading_date", "contract_code", "session_number"],
    sort=False,
)
minute_interval = minute_groups["bar_at"].diff()

minute_df["log_return"] = (
    minute_groups["log_close"].diff()
    .where(minute_interval.eq(pd.Timedelta(minutes=1)))
)

is_session_open_minute = minute_df["minute_slot"].isin([
    dt.time(9, 31), dt.time(13, 1),
])
session_open_prices = minute_df.loc[is_session_open_minute, "open"]

minute_df.loc[is_session_open_minute, "log_return"] = (
    minute_df.loc[is_session_open_minute, "log_close"]
    - np.log(session_open_prices.where(session_open_prices > 0))
)

minute_df.head()

  contract_code trading_date  session_number                     bar_at    open   close minute_slot  log_close  log_return
0   IM2208.CCFX   2022-07-25               1  2022-07-25 09:31:00+08:00  6974.2  6973.8    09:31:00   8.849916   -0.000057
1   IM2208.CCFX   2022-07-25               1  2022-07-25 09:32:00+08:00  6974.0  6982.8    09:32:00   8.851205    0.001290
2   IM2208.CCFX   2022-07-25               1  2022-07-25 09:33:00+08:00  6982.4  6989.8    09:33:00   8.852207    0.001002
3   IM2208.CCFX   2022-07-25               1  2022-07-25 09:34:00+08:00  6989.6  6993.0    09:34:00   8.852665    0.000458
4   IM2208.CCFX   2022-07-25               1  2022-07-25 09:35:00+08:00  6993.6  7002.2    09:35:00   8.853980    0.001315

### 首分钟 RV 项与其余分钟 BV 求和项

实现方差的常见记号是 $RV_t=\sum_{i=1}^{M}r_{t,i}^{2}$。
实现双幂变差通常记作 $BV$，也常简称 BPV。对有效的同 Session 相邻收益，
本项目用 $b_{t,i}$ 简称 BV 的一个求和项：

$$
b_{t,i}=\frac{\pi}{2}|r_{t,i}||r_{t,i-1}|.
$$

补入首分钟收益后，仍缺少与它配对的前一个组内收益。
因此现有代码构造的是下面的**混合贡献**，而非每个分钟均为 BV 求和项：

$$
c^{\mathrm{mix}}_{t,i}
=
\begin{cases}
r_{t,i}^{2}, & i\in\{1,121\},\\
b_{t,i}, & \text{其余有效同 Session 配对分钟}.
\end{cases}
$$

所以 09:31、13:01 使用 RV 的平方收益项，09:32、13:02 起使用 BV 求和项。
$c^{\mathrm{mix}}$ 是本项目定义；其每日合计不能直接称为普通 BV。
代码将混合贡献存入 `variance_contribution`，通过 `contribution_method`
标明类型。缺失收益或无效配对仍保留为空。

#### Cell 5：计算 BV 求和项与首分钟 RV 项，整理混合贡献矩阵。

`bpv_contribution` 保存有效相邻绝对收益乘积；
`variance_contribution_matrix` 保存“交易日 × 分钟位置”的混合贡献 $c^{\mathrm{mix}}_{t,i}$。

In [15]:
previous_log_return = minute_groups["log_return"].shift(1)

minute_df["bpv_contribution"] = (
    (np.pi / 2)
    * minute_df["log_return"].abs()
    * previous_log_return.abs()
)

minute_df["variance_contribution"] = minute_df["bpv_contribution"]
minute_df.loc[is_session_open_minute, "variance_contribution"] = (
    minute_df.loc[is_session_open_minute, "log_return"].pow(2)
)
minute_df["contribution_method"] = np.where(
    is_session_open_minute, "rv_open", "bpv"
)

variance_contribution_matrix = minute_df.pivot(
    index="trading_date",
    columns="minute_slot",
    values="variance_contribution",
).reindex(
    index=trading_dates,
    columns=minute_slots,
)

In [16]:
variance_contribution_matrix.head()

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2022-07-25,3.289698e-09,1.161959e-07,2.029849e-06,7.203716e-07,9.452452e-07,1.709906e-06,7.425461e-07,4.096514e-07,5.936471e-07,1.111866e-07,2.992373e-07,3.700619e-06,1.758308e-06,1.520590e-06,2.095229e-06,2.028622e-06,1.472756e-06,1.428002e-06,5.409673e-07,8.661677e-07,3.471532e-06,2.610980e-06,3.313059e-06,9.190267e-07,9.055102e-08,2.809299e-07,3.615068e-07,4.201099e-07,2.384528e-06,2.984648e-06,5.263390e-07,4.911014e-07,1.638064e-06,1.675596e-06,1.170610e-06,2.719066e-08,7.113807e-08,1.847389e-06,7.727661e-07,1.578082e-06,1.925480e-06,0.000000e+00,0.000000e+00,1.169995e-07,3.315321e-07,3.755419e-07,7.950936e-07,1.967092e-06,4.379378e-07,1.460718e-07,2.555005e-07,8.202235e-07,2.163341e-06,1.774763e-06,6.226884e-07,3.700718e-07,4.269079e-07,1.940992e-07,1.553841e-07,6.370110e-07,2.812779e-06,2.127774e-06,7.628962e-07,1.230513e-07,8.418816e-08,1.177991e-07,2.446598e-07,3.147342e-07,2.915629e-07,0.000000e+00,0.000000e+00,9.328806e-08,7.770879e-09,3.366801e-08,4.882212e-07,1.315953e-06,1.773244e-06,8.121312e-07,4.167833e-07,2.083437e-07,3.956138e-07,2.320390e-06,1.768203e-06,8.280623e-07,3.716595e-07,1.014229e-07,2.729283e-07,1.818580e-06,1.766900e-06,1.632857e-06,4.795003e-08,6.342122e-08,1.266987e-06,1.241825e-06,1.493188e-06,5.920310e-07,2.962284e-07,4.366915e-07,6.191894e-07,4.426602e-08,8.598509e-08,3.442972e-07,4.176487e-08,6.789630e-08,1.528129e-07,3.174814e-07,2.117734e-07,2.353648e-08,3.530014e-08,3.295298e-07,7.329968e-07,7.596027e-07,4.554328e-07,4.081600e-07,1.701526e-07,1.962902e-07,2.001756e-06,4.278810e-06,8.508109e-06,2.669822e-06,3.248002e-06,2.471019e-07,1.833923e-07,2.442210e-07,1.591936e-08,1.352674e-07,1.532340e-06,2.254390e-07,5.968804e-08,4.293858e-07,1.907246e-06,1.589694e-06,1.470830e-06,4.905973e-08,2.521407e-08,1.034980e-06,1.036789e-06,1.265923e-07,3.596578e-07,6.464989e-07,2.633348e-07,1.756766e-07,4.792296e-08,7.989020e-08,5.731221e-07,7.459602e-07,6.940478e-08,5.337118e-09,2.134163e-08,2.133106e-08,9.339417e-08,2.806281e-06,2.043354e-06,6.798188e-08,3.595059e-08,7.184783e-08,1.886751e-07,9.414443e-08,1.457262e-08,2.915497e-08,3.712196e-08,1.856934e-08,1.459592e-08,1.459868e-07,3.183640e-07,1.623492e-06,1.083808e-06,1.063762e-07,5.984967e-08,1.915998e-07,6.606470e-07,7.025612e-07,3.853540e-07,2.946997e-07,2.773927e-07,1.494219e-07,1.214354e-07,1.908047e-07,2.348127e-07,1.044918e-06,1.499077e-06,1.742860e-06,2.581094e-06,1.088376e-06,7.358574e-07,5.205724e-07,1.468574e-06,1.293317e-06,2.386863e-07,8.749799e-07,1.019151e-06,7.963284e-07,2.731220e-06,1.714305e-06,4.644190e-07,4.989941e-07,4.985744e-07,2.405479e-07,8.519234e-07,3.047490e-07,0.000000e+00,0.000000e+00,2.148114e-07,7.162877e-08,3.581595e-08,2.386932e-08,4.243620e-08,2.334635e-07,7.295629e-08,3.315906e-08,6.108993e-07,6.120465e-06,1.728841e-06,9.318240e-07,2.074522e-06,0.000000e+00,0.000000e+00,4.640236e-06,1.233688e-06,4.268508e-07,4.773177e-07,1.004661e-07,6.871602e-08,6.529538e-07,6.033828e-07,2.225443e-07,1.855640e-08,7.955284e-09,3.182530e-08,1.008050e-07,2.773064e-07,5.838115e-08,3.714624e-08,8.357783e-08,9.554390e-08,6.372464e-08,4.781154e-08,7.971836e-08,1.329335e-07,3.722247e-07
2022-07-26,8.772026e-06,8.515418e-06,3.507263e-06,2.005811e-06,1.004875e-06,1.033405e-06,1.475219e-07,1.195636e-08,3.986034e-09,2.789575e-08,2.787507e-07,1.061152e-07,4.139274e-07,1.035902e-07,5.845333e-08,1.198276e-06,4.791156e-06,4.317573e-06,1.914164e-06,3.371535e-06,1.473628e-06,9.996140e-07,1.236331e-06,3.091414e-07,3.384747e-07,8.915099e-07,6.583274e-07,4.539196e-07,2.798402e-06,2.091333e-06,5.563688e-07,7.408459e-07,2.114860e-07,1.268622e-07,3.806307e-07,1.904313e-07,5.789182e-07,3.179114e-06,4.353876e-07,4.879922e-07,3.554257e-06,1.724079e-06,1.886645e-07,6.387821e-07,1.036121e-06,1.307702e-06,7.853346e-06,2.038095e-06,7.053821e-07,7.061556e-08,5.758262e-08,5.761921e-08,1.571977e-08,9.434862e-08,4.560249e-07,7.595150e-08,4.713210e-08,8.247999e-07,5.953536e-07,1.190432e-07,9.156906e-09,5.627719e-08,1.745953e-06,3.653793e-07,4.834390e-07,4.302390e-07,1.259473e-07,1.730699e-07,3.602553e-07,6.544519e-08,1.751706e-07,1.398378e-06,3.543934e-07,1.772222e-07,9.381271e-08,4.688610e-08,8.331348e-08,7.498213e-07,6.096071e-07,7.277961e-07,1.062478e-06,1.976788e-07,0.000000e+00,0.000000e+00,2.432075e-07,2.575990e-07,5.391591e-07,8.091696e-07,3.165313e-07,3.987385e-07,3.104428e-07,2.101356e-07,3.003668e-08,5.225353e-09,6.791000e-08,2.375343e-07,3.835987e-07,5.482035e-08,2.610756e-08,1.304945e-08,2.087071e-08,8.756234e-07,1.802520e-06,1.113697e-06,6.741633e-08,1.139811e-07,3.414921e-07,7.754839e-09,2.842218e-08,2.556676e-07,6.972953e-08,2.711160e-07,6.318973e-07,1.082182e-07,3.711509e-07,5.575167e-07,2.093206e-07,2.327253e-08,9.053413e-09,0.000000e+00,7.418193e-09,6.604394e-08,2.862644e-07,3.702950e-07,3.131197e-07,4.267977e-07,1.823538e-06,4.259260e-07,2.901129e-07,1.242377e-07,3.881538e-08,1.294292e-08,2.978367e-08,8.043900e-07,1.224142e-06,3.175982e-07,1.816072e-08,5.450096e-08,4.361581e-07,0.000000e+00,0.000000e+00,1.765808e-07,1.974118e-07,7.406454e-08,3.509128e-08,2.922592e-07,3.892814e-07,7.780707e-08,5.187585e-08,5.189523e-08,6.237649e-07,3.751593e-06,4.692730e-07,4.537810e-07,4.543175e-07,1.410845e-07,1.410479e-07,1.723372e-07,2.872618e-08,2.350256e-08,3.053309e-07,6.441974e-07,2.478075e-08,3.262599e-08,1.632570e-07,0.000000e+00,0.000000e+00,0.000000e+00,6.536403e-08,2.614410e-08,3.136976e-08,1.489827e-07,2.233420e-07,0.000000e+00,0.000000e+00,3.915118e-09,2.348293e-08,3.988993e-07,1.328554e-07,0.000000e+00,0.000000e+00,5.513725e-07,9.635151e-07,4.181171e-07,5.978428e-08,6.503154e-08,5.207617e-07,0.000000e+00,0.000000e+00,5.474931e-08,0.000000e+00,0.000000e+00,0.000000e+00,1.861498e-06,1.376292e-07,5.188405e-08,1.036519e-06,1.708612e-06,7.693614e-07,9.335373e-08,5.707984e-08,8.565914e-08,7.790889e-08,1.298986e-08,1.299228e-09,1.169507e-08,4.326058e-07,1.152936e-06,1.869760e-07,1.558357e-08,1.608637e-07,1.686524e-06,7.073126e-07,1.011463e-07,5.446808e-08,1.814534e-07,3.886221e-08,1.165649e-08,1.165649e-08,1.165548e-08,3.884603e-09,1.294961e-08,2.201496e-07,8.803458e-08,8.800173e-08,1.979442e-07,1.397033e-07,1.551947e-08,1.163643e-08,8.142697e-08,1.085522e-07,1.085895e-07,6.336117e-08,1.448442e-07,1.656147e-07,1.242466e-07,7.764190e-08,2.069441e-07,1.322715e-06,2.103641e-06
2022-07-27,2.222052e-06,6.046348e-07,3.257687e-07,1.590571e-06,5.671986e-07,2.962906e-07,3.850510e-07,1.674231e-08,3.864273e-09,1.585169e-07,1.217074e-06,3.269910e-07,7.112580e-08,5.172266e-08,9.306073e-08,9.303671e-08,2.067749e-08,3.878532e-08,6.205651e-07,4.134254e-08,5.039273e-08,3.175471e-06,1.220075e-06,7.743285e-08,7.227998e-08,3.792253e-07,2.027758e-06,2.889842e-07,3.848772e-08,4.615032e-07,1.428354e-06,5.548054e-07,5.012933e-07,1.506286e-06,8.080576e-07,3.848662e-08,2.821465e-08,7.051145e-08,5.823905e-07,3.253997e-06,1.036042e-06,0.000000e+00,0.000000e+00,1.696747e-07,1.874925e-07,2.676976e-07,2.549392e-08,4.842949e-08,5.806246e-07,9.155111e-07,5.335166e-07,9.950771e-07,1.562005e-06,6.137319e-07,3.908453e-07,4.971992e-07,5.322974e-07,4.754479e-07,3.173032e-07,3.811700e-07,4.579379e-07,1.833473e-07,4.585836e-08,2.675033e-08,6.240854e-08,1.605363e-07,2.982662e-07,1.822815e-07,1.402365e-08,2.167169e-08,4.332177e-08,4.077053e-08,8.157126e-08,1.325193e-07,1.655289e-07,1.209032e-07,9.915191e-07,7.836481e-07,2.296317e-07,1.684638e-07,2.666241e-07,4.600867e-07,5.804923e-07,4.579444e-07,1.335918e-07,1.068993e-07,5.341013e-07,1.245279e-06,7.476142e-07,1.069024e-07,1.935829e-07,1.597946e-06,8.407127e-08,8.399710e-08,2.222222e-06,1.546269e-06,7.879460e-07,6.514487e-07,1.688845e-07,3.555008e-08,7.616142e-08,2.855282e-07,1.903657e-07,1.015327e-07,3.046370e-08,7.617657e-09,8.630034e-08,3.017981e-07,2.662054e-08,6.466641e-08,0.000000e+00,0.000000e+00,3.086424e-07,1.715265e-07,1.906392e-08,2.542398e-09,4.832069e-08,1.934148e-07,1.018335e-07,2.164116e-07,5.913622e-07,3.786495e-07,8.419589e-08,7.655153e-08,3.826705e-07,9.946031e-07,2.321236e-07,9.820755e-08,3.084282e-07,1.120743e-07,3.055701e-08,4.582638e-08,7.636860e-08,3.944757e-07,1.576825e-07,1.017263e-07,4.070674e-07,4.682008e-07,2.927463e-08,3.184110e-08,7.968668e-07,1.595324e-07,1.914880e-08,7.659846e-09,1.021357e-08,2.553355e-08,3.830688e-08,2.298871e-08,3.830906e-08,3.190239e-07,6.376841e-07,1.198300e-06,2.335521e-06,1.043679e-06,1.070333e-07,2.189390e-07,2.130741e-06,7.421625e-07,9.316926e-07,6.204056e-08,2.024923e-08,6.884640e-07,1.333502e-06,2.746262e-07,2.216048e-07,7.916482e-07,9.496003e-08,6.076147e-08,2.026504e-07,2.661941e-07,2.130884e-07,1.014793e-08,5.073821e-09,1.116035e-07,0.000000e+00,0.000000e+00,6.126088e-07,1.668477e-07,6.441361e-08,8.584222e-08,7.570020e-08,1.891862e-07,3.908408e-07,3.905586e-08,3.147259e-08,6.290332e-08,1.509359e-08,8.304413e-08,2.769313e-08,5.289566e-08,2.646806e-07,7.567339e-08,4.542205e-08,1.211289e-07,1.210740e-07,9.075406e-08,7.559091e-08,6.298172e-08,2.519875e-08,7.557914e-08,9.436301e-07,2.199530e-07,1.759400e-08,1.005471e-08,5.530482e-08,2.213257e-07,4.026439e-08,1.762041e-08,7.050159e-08,3.427128e-07,8.150390e-07,2.159383e-07,2.273712e-07,6.316404e-07,8.526782e-07,3.411632e-07,2.021450e-07,1.414313e-07,1.414594e-07,3.235880e-07,4.248719e-07,1.327141e-07,1.137340e-07,1.365524e-07,1.214040e-07,2.022941e-07,5.057927e-08,1.062119e-07,2.919710e-07,6.952282e-08,7.585276e-08,1.668051e-07,4.166345e-07,3.027365e-07,2.622230e-07,0.000000e+00,0.000000e+00,9.824314e-08,1.145959e-07,1.321998e-07
2022-07-28,2.285657e-07,4.010659e-07,8.254919e-07,1.739222e-07,1.741131e-07,1.569446e-06,6.286012e-07,3.666169e-07,0.000000e+00,0.000000e+00,7.977065e-08,1.197099e-07,5.989040e-08,1.197336e-07,9.567629e-07,5.382624e-07,2.357454e-07,8.737586e-08,9.988488e-08,1.098470e-07,3.567213e-07,5.509394e-07,7.845264e-07,3.376649e-06,2.652320e-06,5.088722e-07,4.739517e-07,1.794626e-06,2.322626e-06,1.049576e-06,8.090333e-07,4.047563e-07,1.200005e-07,1.500239e-07,2.063790e-07,1.376598e-08,3.005055e-08,7.219571e-07,1.806576e-07,2.332868e-07,3.107855e-07,1.002463e-07,6.267430e-08,7.519642e-08,2.855528e-07,1.306846e-06,1.098254e-06,1.135884e-06,3.894454e-06,2.726695e-07,2.277533e-07,1.137393e-07,2.471172e-09,5.680350e-08,2.211305e-06,7.679872e-07,2.166239e-07,0.000000e+00,0.000000e+00,3.941539e-08,5.910819e-08,2.660465e-07,8.430351e-07,2.107794e-07,2.441322e-07,8.143443e-08,4.812237e-08,8.017698e-08,1.972620e-07,1.260869e-06,2.044675e-06,3.765812e-06,7.248529e-08,1.352706e-08,2.164481e-07,4.719533e-07,3.241278e-07,8.091205e-07,1.028109e-06,1.884313e-07,4.850249e-07,1.324385e-07,4.048484e-08,8.095498e-08,1.471888e-08,0.000000e+00,0.000000e+00,1.273963e-06,2.230026e-07,8.580618e-08,2.697105e-07,2.428242e-07,1.656059e-07,4.234755e-07,2.542701e-07,2.431570e-07,7.292061e-07,9.948586e-08,4.422892e-08,0.000000e+00,0.000000e+00,1.965867e-07,2.457884e-07,5.653686e-07,5.932471e-07,6.186857e-07,3.832101e-07,4.793276e-08,2.581500e-08,6.025017e-08,2.670164e-07,1.260591e-06,7.738766e-07,0.000000e+00,0.000000e+00,4.450418e-08,2.003503e-07,1.781291e-07,0.000000e+00,0.000000e+00,1.526985e-06,8.180314e-07,5.762027e-07,7.288739e-07,9.395195e-08,1.582460e-07,3.959537e-08,1.238119e-08,3.840974e-07,3.844914e-08,3.722453e-09,2.605278e-08,1.736388e-08,3.223634e-08,2.417284e-07,5.209751e-07,1.252222e-06,4.477887e-07,6.220249e-08,1.367647e-07,2.186973e-07,2.682767e-07,6.702394e-08,4.219195e-08,1.055199e-07,4.965573e-08,3.175601e-07,9.117680e-07,2.277181e-07,7.920740e-08,9.902870e-08,4.950323e-08,1.137920e-07,2.274499e-07,3.955483e-08,7.419757e-08,7.422880e-08,8.411417e-08,5.462516e-07,0.000000e+00,0.000000e+00,2.469232e-08,5.680667e-07,6.248384e-07,2.717108e-07,4.572181e-07,7.777833e-07,1.261217e-07,1.483140e-08,2.224678e-08,1.112745e-07,1.236713e-07,4.946435e-08,2.473322e-08,1.236869e-08,3.957148e-08,3.756497e-07,7.038397e-08,7.038989e-08,4.226889e-07,2.003503e-07,2.226739e-07,4.208897e-07,8.423705e-08,1.090601e-07,2.455542e-07,1.898078e-07,1.475619e-07,2.603010e-08,4.834976e-08,1.612338e-08,1.612972e-08,2.097277e-07,4.518164e-07,4.173839e-07,5.966653e-08,2.486420e-08,3.108506e-08,1.367608e-07,5.742500e-07,2.089004e-07,9.952959e-09,3.983538e-08,3.588922e-07,1.683136e-07,3.177557e-07,2.116880e-08,1.120543e-08,2.241686e-08,4.234058e-08,7.402619e-07,5.218106e-07,5.062395e-07,2.528141e-07,7.430802e-09,1.114636e-08,1.338108e-07,1.487685e-07,1.240121e-07,1.611636e-07,2.094450e-07,9.669272e-08,8.930123e-08,1.042389e-07,1.303738e-07,3.167111e-07,4.222874e-07,1.490782e-07,1.640553e-07,8.206803e-08,2.984628e-08,6.962956e-08,6.092501e-08,5.221189e-08,2.237149e-08,3.728529e-09,3.478639e-08,6.254953e-07,4.465061e-07,4.465312e-07
2022-07-29,1.769623e-07,1.111747e-07,7.411436e-09,5.802453e-08,9.848979e-07,4.186420e-08,5.907180e-08,2.361616e-07,1.279298e-07,4.321319e-07,1.631453e-06,9.686996e-07,4.550656e-07,1.705922e-07,2.077270e-07,2.772415e-07,2.775218e-07,1.667754e-06,5.541740e-06,9.208011e-06,1.677621e-06,3.142850e-07,0.000000e+00,0.000000e+00,1.247141e-06,1.416312e-06,3.079543e-07,9.859645e-08,4.532137e-07,3.000566e-06,3.070393e-06,4.063996e-07,1.038678e-07,1.484451e-08,1.608088e-08,1.607253e-07,9.887321e-08,7.909635e-08,1.087621e-07,3.941795e-07,5.728459e-07,1.184285e-07,1.110438e-07,7.040076e-07,1.175257e-06,7.434352e-07,1.190650e-07,6.945651e-08,5.903970e-07,1.266631e-06,2.464296e-06,8.231917e-07,2.370695e-07,2.369126e-08,2.493922e-08,9.237661e-07,5.088241e-07,2.753468e-07,1.252566e-07,8.773411e-08,4.562625e-07,6.514355e-08,1.502549e-08,2.477561e-07,1.857463e-06,2.085376e-06,1.623884e-06,1.754633e-07,2.603389e-07,6.498472e-08,6.488768e-08,6.480089e-07,1.121190e-07,3.366320e-07,3.370022e-07,6.074772e-07,1.081499e-06,5.006729e-07,1.250446e-07,1.100222e-07,1.924575e-06,6.112867e-07,1.919508e-07,5.487324e-08,9.986237e-08,4.498434e-07,3.036229e-07,6.068605e-07,2.022868e-07,5.619475e-08,8.743254e-08,1.083721e-06,3.089810e-06,4.973541e-08,1.242476e-08,3.727900e-07,5.970180e-07,6.575985e-07,4.114681e-08,6.236649e-09,8.731678e-08,2.445180e-07,4.014988e-07,1.432612e-07,1.183229e-07,6.157905e-07,1.070104e-06,6.580061e-07,5.978925e-07,7.854527e-07,4.716302e-07,3.367364e-07,7.477551e-08,1.894713e-07,4.267973e-07,2.811085e-07,2.813068e-07,5.626294e-08,2.814180e-07,7.887602e-07,5.392231e-07,3.259386e-07,5.017416e-08,0.000000e+00,0.000000e+00,4.013252e-08,1.403904e-07,1.579125e-07,3.611723e-07,3.613356e-07,2.257391e-07,2.255606e-07,7.442133e-07,2.482183e-07,9.782994e-08,3.262842e-07,1.004647e-07,5.525636e-08,3.453474e-07,9.419764e-07,2.483272e-06,1.651266e-06,4.247921e-07,2.124410e-08,2.500681e-08,3.002045e-07,9.004865e-08,3.000775e-08,1.400955e-07,3.504858e-07,1.627738e-07,8.134787e-07,6.054081e-06,2.172541e-06,2.909685e-07,3.235076e-08,4.481543e-08,5.831259e-07,3.243241e-07,2.495715e-07,9.235056e-07,1.386372e-07,7.496332e-08,1.073263e-06,4.174898e-06,2.615111e-06,3.687302e-07,1.639653e-07,6.113842e-07,1.529902e-07,1.007610e-07,2.013774e-07,0.000000e+00,0.000000e+00,7.156208e-07,3.426584e-07,9.599840e-08,8.727988e-08,4.113464e-07,4.110801e-07,6.227784e-08,4.983069e-08,1.096275e-07,1.370807e-07,9.972736e-08,2.593642e-07,4.867124e-07,9.367905e-08,7.498235e-08,6.000703e-08,1.550947e-07,3.104785e-07,1.102600e-07,4.136329e-08,3.760033e-08,2.004247e-07,2.404078e-07,2.104222e-07,1.052616e-07,2.255574e-08,3.007262e-08,2.806184e-07,4.207136e-07,1.201835e-07,4.803816e-07,1.977749e-06,4.937270e-07,7.479236e-08,6.232785e-09,2.616738e-08,1.387067e-06,5.952449e-07,1.799170e-07,6.397862e-07,1.239289e-06,1.161833e-06,3.372113e-07,2.135882e-07,1.424745e-07,7.499504e-09,1.500070e-08,3.452498e-07,2.015806e-07,7.893060e-08,1.353344e-07,1.503185e-07,1.252265e-07,1.252460e-08,4.006740e-08,6.803773e-07,1.487087e-07,5.247876e-08,7.496543e-09,1.874427e-08,3.187154e-07,6.372870e-08,3.748219e-09,7.497600e-09,1.499837e-08,3.250702e-08

#### Cell 6：计算每日混合贡献总量、有效贡献数及历史样本资格。

`daily_variance_proxy` 是 $\sum_i c^{\mathrm{mix}}_{t,i}$，包含两个首分钟 RV 项。
只有早于运行当天、240 个贡献均有限且日总量为正的完整交易日，才能用于历史形状估计。

In [18]:
daily_summary_df = pd.DataFrame({
    "daily_variance_proxy": variance_contribution_matrix.sum(
        axis=1, min_count=1
    ),
    "valid_slot_count": variance_contribution_matrix.count(axis=1),
})

daily_summary_df["is_eligible_history_day"] = (
    (trading_dates < as_of_at.date())
    & np.isfinite(variance_contribution_matrix).all(axis=1)
    & np.isfinite(daily_summary_df["daily_variance_proxy"])
    & daily_summary_df["daily_variance_proxy"].gt(0)
)

daily_summary_df.head()

              daily_variance_proxy  valid_slot_count  is_eligible_history_day
trading_date
2022-07-25                0.000187               240                     True
2022-07-26                0.000137               240                     True
2022-07-27                0.000085               240                     True
2022-07-28                0.000084               240                     True
2022-07-29                0.000125               240                     True

### 每日归一化：提取混合贡献的日内相对形状

将每分钟混合贡献除以当天平均分钟混合贡献。对合格的完整历史日：

$$
x^{\mathrm{mix}}_{t,i}
=
\frac{c^{\mathrm{mix}}_{t,i}}
     {M^{-1}\sum_{j=1}^{M}c^{\mathrm{mix}}_{t,j}}
=
\frac{M c^{\mathrm{mix}}_{t,i}}
     {\sum_{j=1}^{M}c^{\mathrm{mix}}_{t,j}},
\qquad M=240.
$$

$x^{\mathrm{mix}}$ 是本项目定义的“日内相对混合贡献”。
其日内均值为 1；数值 2 表示该分钟贡献是当天平均分钟贡献的两倍。
这一步消去当天混合贡献的总体水平，保留各分钟的相对形状。

代码先使用 `valid_slot_count` 计算，再将不符合完整历史日条件的整行置空；
因此进入滚动估计的有效日满足上式中的 $M=240$。
历史日的全日归一化在估计目标日因子前已经完成；目标日仅使用此前交易日的形状。

#### Cell 7：用“有效贡献数 × 混合贡献 ÷ 日总量”计算 $x^{\mathrm{mix}}_{t,i}$，不合格历史日置空。

In [21]:
daily_shape_matrix = (
    variance_contribution_matrix
    .mul(daily_summary_df["valid_slot_count"], axis=0)
    .div(
        daily_summary_df["daily_variance_proxy"].where(
            daily_summary_df["daily_variance_proxy"] > 0
        ),
        axis=0,
    )
)

daily_shape_matrix.loc[
    ~daily_summary_df["is_eligible_history_day"], :
] = np.nan

daily_shape_matrix.head()

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2022-07-25,0.004215,0.148880,2.600817,0.923002,1.211130,2.190879,0.951414,0.524881,0.760632,0.142462,0.383409,4.741552,2.252895,1.948311,2.684588,2.599246,1.887022,1.829679,0.693134,1.109809,4.448025,3.345412,4.244977,1.177536,0.116022,0.359952,0.463194,0.538281,3.055262,3.824188,0.674391,0.629241,2.098829,2.146918,1.499886,0.034839,0.091148,2.367034,0.990134,2.021975,2.467091,0.000000,0.000000,0.149910,0.424787,0.481177,1.018742,2.520408,0.561124,0.187160,0.327369,1.050941,2.771859,2.273980,0.797842,0.474168,0.546991,0.248697,0.199092,0.816193,3.603975,2.726287,0.977488,0.157664,0.107869,0.150934,0.313479,0.403265,0.373575,0.000000,0.000000,0.119529,0.009957,0.043138,0.625551,1.686112,2.272032,1.040572,0.534019,0.266948,0.506894,2.973083,2.265574,1.060985,0.476202,0.129952,0.349699,2.330121,2.263905,2.092156,0.061438,0.081261,1.623373,1.591133,1.913202,0.758561,0.379553,0.559527,0.793359,0.056717,0.110171,0.441143,0.053513,0.086995,0.195797,0.406785,0.271342,0.030157,0.045230,0.422222,0.939179,0.973268,0.583540,0.522970,0.218014,0.251504,2.564823,5.482380,10.901321,3.420805,4.161619,0.316608,0.234978,0.312917,0.020397,0.173316,1.963366,0.288852,0.076477,0.550166,2.443727,2.036853,1.884554,0.062860,0.032306,1.326106,1.328423,0.162201,0.460825,0.828350,0.337407,0.225092,0.061403,0.102362,0.734333,0.955788,0.088927,0.006838,0.027345,0.027331,0.119665,3.595648,2.618121,0.087104,0.046063,0.092058,0.241747,0.120626,0.018672,0.037356,0.047564,0.023793,0.018702,0.187051,0.407915,2.080157,1.388668,0.136298,0.076685,0.245494,0.846478,0.900182,0.493749,0.377595,0.355419,0.191452,0.155593,0.244475,0.300862,1.338839,1.920747,2.233103,3.307120,1.394521,0.942844,0.667002,1.881664,1.657109,0.305825,1.121100,1.305824,1.020324,3.499474,2.196515,0.595054,0.639354,0.638816,0.308211,1.091558,0.390471,0.000000,0.000000,0.275235,0.091777,0.045890,0.030583,0.054373,0.299134,0.093478,0.042486,0.782737,7.842067,2.215139,1.193933,2.658056,0.000000,0.000000,5.945470,1.580707,0.546918,0.611581,0.128726,0.088045,0.836621,0.773106,0.285143,0.023776,0.010193,0.040777,0.129160,0.355309,0.074803,0.047595,0.107087,0.122419,0.081649,0.061260,0.102142,0.170326,0.476926
2022-07-26,15.374330,14.924584,6.147020,3.515493,1.761199,1.811201,0.258555,0.020955,0.006986,0.048892,0.488554,0.185983,0.725472,0.181558,0.102448,2.100164,8.397241,7.567213,3.354869,5.909136,2.582761,1.751978,2.166861,0.541818,0.593229,1.562509,1.153820,0.795564,4.904631,3.665383,0.975122,1.298447,0.370662,0.222346,0.667114,0.333760,1.014644,5.571889,0.763084,0.855282,6.229384,3.021714,0.330664,1.119564,1.815962,2.291950,13.764201,3.572075,1.236291,0.123765,0.100922,0.100987,0.027551,0.165361,0.799254,0.133117,0.082606,1.445589,1.043449,0.208642,0.016049,0.098634,3.060053,0.640384,0.847302,0.754060,0.220742,0.303332,0.631403,0.114703,0.307014,2.450874,0.621129,0.310609,0.164421,0.082175,0.146020,1.314178,1.068431,1.275575,1.862157,0.346463,0.000000,0.000000,0.426259,0.451482,0.944960,1.418195,0.554770,0.698851,0.544099,0.368295,0.052644,0.009158,0.119023,0.416316,0.672316,0.096081,0.045758,0.022871,0.036579,1.534665,3.159194,1.951926,0.118158,0.199769,0.598518,0.013592,0.049814,0.448097,0.122212,0.475173,1.107498,0.189669,0.650499,0.977134,0.366867,0.040789,0.015868,0.000000,0.013002,0.115752,0.501723,0.648999,0.548791,0.748029,3.196032,0.746501,0.508468,0.217746,0.068030,0.022684,0.052200,1.409818,2.145498,0.556640,0.031829,0.095521,0.764434,0.000000,0.000000,0.309485,0.345995,0.129810,0.061503,0.512229,0.682276,0.136369,0.090920,0.090954,1.093244,6.575247,0.822473,0.795321,0.796262,0.247272,0.247208,0.302048,0.050347,0.041192,0.535139,1.129055,0.043432,0.057182,0.286133,0.000000,0.000000,0.000000,0.114561,0.045822,0.054980,0.261115,0.391441,0.000000,0.000000,0.006862,0.041157,0.699133,0.232850,0.000000,0.000000,0.966365,1.688709,0.732815,0.104781,0.113978,0.912715,0.000000,0.000000,0.095957,0.000000,0.000000,0.000000,3.262563,0.241216,0.090935,1.816660,2.994607,1.348425,0.163617,0.100041,0.150131,0.136547,0.022767,0.002277,0.020497,0.758208,2.020698,0.327704,0.027313,0.281939,2.955893,1.239675,0.177274,0.095464,0.318025,0.068112,0.020430,0.020430,0.020428,0.006808,0.022696,0.385846,0.154294,0.154237,0.346928,0.244852,0.027200,0.020395,0.142713,0.190254,0.190320,0.111050,0.253862,0.290265,0.217761,0.136079,0.362701,2.318262,3.686956
2022-07-27,6.248892,1.700364,0.916132,4.473028,1.595085,0.833233,1.082847,0.047083,0.010867,0.445784,3.422675,0.919570,0.200021,0.145455,0.261707,0.261639,0.058150,0.109073,1.745163,0.116264,0.141715,8.930112,3.431114,0.217758,0.203267,1.066464,5.702494,0.812686,0.108236,1.297847,4.016840,1.560233,1.409745,4.236003,2.272433,0.108233,0.079346,0.198293,1.637808,9.150944,2.913574,0.000000,0.000000,0.477162,0.527269,0.752824,0.071694,0.136194,1.632842,2.574615,1.500364,2.798372,4.392696,1.725947,1.099142,1.398232,1.496935,1.337062,0.892325,1.071933,1.287820,0.515612,0.128964,0.075228,0.175506,0.451463,0.838789,0.512615,0.039438,0.060945,0.121830,0.114656,0.229396,0.372673,0.465503,0.340006,2.788366,2.203788,0.645774,0.473757,0.749805,1.293863,1.632470,1.287839,0.375689,0.300624,1.502008,3.501995,2.102453,0.300633,0.544397,4.493769,0.236427,0.236218,6.249370,4.348444,2.215875,1.832015,0.474940,0.099975,0.214182,0.802967,0.535349,0.285532,0.085671,0.021423,0.242695,0.848721,0.074863,0.181856,0.000000,0.000000,0.867969,0.482370,0.053612,0.007150,0.135888,0.543924,0.286378,0.608596,1.663038,1.064844,0.236777,0.215279,1.076152,2.797039,0.652782,0.276181,0.867367,0.315177,0.085933,0.128874,0.214765,1.109351,0.443437,0.286076,1.144762,1.316682,0.082327,0.089544,2.240962,0.448640,0.053851,0.021541,0.028723,0.071806,0.107727,0.064649,0.107733,0.897164,1.793306,3.369879,6.567989,2.935051,0.301001,0.615704,5.992106,2.087121,2.620121,0.174471,0.056945,1.936110,3.750095,0.772308,0.623201,2.226286,0.267048,0.170874,0.569897,0.748595,0.599251,0.028538,0.014269,0.313853,0.000000,0.000000,1.722788,0.469212,0.181145,0.241407,0.212885,0.532032,1.099129,0.109834,0.088508,0.176898,0.042446,0.233538,0.077879,0.148754,0.744339,0.212810,0.127737,0.340641,0.340486,0.255220,0.212578,0.177118,0.070864,0.212545,2.653692,0.618556,0.049478,0.028276,0.155529,0.622416,0.113232,0.049552,0.198266,0.963783,2.292066,0.607265,0.639417,1.776309,2.397916,0.959425,0.568475,0.397735,0.397814,0.909999,1.194832,0.373221,0.319845,0.384015,0.341414,0.568895,0.142240,0.298691,0.821086,0.195513,0.213314,0.469092,1.171666,0.851360,0.737428,0.000000,0.000000,0.276281,0.322268,0.371775
2022-07-28,0.652364,1.144707,2.356088,0.496402,0.496947,4.479455,1.794130,1.046384,0.000000,0.000000,0.227678,0.341672,0.170937,0.341739,2.730757,1.536288,0.672856,0.249385,0.285088,0.313521,1.018141,1.572471,2.239166,9.637505,7.570152,1.452404,1.352735,5.122154,6.629151,2.995659,2.309113,1.155240,0.342501,0.428193,0.589039,0.039290,0.085769,2.060583,0.515626,0.665838,0.887032,0.286119,0.178883,0.214623,0.815014,3.729951,3.134596,3.241998,11.115405,0.778243,0.650045,0.324630,0.007053,0.162126,6.311425,2.191960,0.618280,0.000000,0.000000,0.112498,0.168704,0.759340,2.406159,0.601599,0.696793,0.232427,0.137349,0.228838,0.563018,3.598726,5.835833,10.748239,0.206885,0.038608,0.617778,1.347032,0.925113,2.309361,2.934389,0.537814,1.384340,0.378001,0.115550,0.231059,0.042010,0.000000,0.000000,3.636097,0.636486,0.244905,0.769798,0.693060,0.472666,1.208668,0.725728,0.694010,2.081273,0.283949,0.126237,0.000000,0.000000,0.561090,0.701520,1.613654,1.693224,1.765829,1.093744,0.136808,0.073680,0.171964,0.762108,3.597930,2.208770,0.000000,0.000000,0.127022,0.571832,0.508409,0.000000,0.000000,4.358263,2.334795,1.644576,2.080324,0.268154,0.451660,0.113012,0.035338,1.096276,0.109740,0.010624,0.074359,0.049559,0.092008,0.689932,1.486948,3.574046,1.278062,0.177536,0.390349,0.624198,0.765705,0.191297,0.120423,0.301171,0.141726,0.906368,2.602334,0.649944,0.226071,0.282644,0.141290,0.324781,0.649179,0.112896,0.211772,0.211861,0.240076,1.559091,0.000000,0.000000,0.070476,1.621355,1.783390,0.775507,1.304975,2.219920,0.359972,0.042331,0.063496,0.317595,0.352978,0.141179,0.070593,0.035302,0.112943,1.072165,0.200887,0.200904,1.206423,0.571832,0.635548,1.201288,0.240426,0.311275,0.700852,0.541742,0.421166,0.074294,0.137998,0.046019,0.046037,0.598597,1.289557,1.191282,0.170298,0.070966,0.088722,0.390338,1.639003,0.596236,0.028407,0.113697,1.024337,0.480394,0.906926,0.060419,0.031982,0.063981,0.120847,2.112828,1.489332,1.444890,0.721573,0.021209,0.031814,0.381918,0.424609,0.353951,0.459987,0.597790,0.275977,0.254880,0.297515,0.372108,0.903945,1.205277,0.425494,0.468240,0.234235,0.085186,0.198734,0.173890,0.149021,0.063852,0.010642,0.099286,1.785265,1.274401,1.274473
2022-07-29,0.339523,0.213302,0.014220,0.111327,1.889644,0.080321,0.113336,0.453104,0.245449,0.829097,3.130139,1.858566,0.873098,0.327302,0.398549,0.531921,0.532459,3.199785,10.632492,17.666672,3.218716,0.602993,0.000000,0.000000,2.392788,2.717365,0.590847,0.189169,0.869545,5.756945,5.890917,0.779726,0.199283,0.028481,0.030853,0.308371,0.189700,0.151756,0.208673,0.756281,1.099073,0.227219,0.213051,1.350723,2.254871,1.426369,0.228440,0.133261,1.132747,2.430183,4.728046,1.579392,0.454846,0.045455,0.047849,1.772356,0.976240,0.528286,0.240320,0.168328,0.875394,0.124986,0.028828,0.475350,3.563766,4.001044,3.115616,0.336647,0.499491,0.124681,0.124495,1.243283,0.215114,0.645869,0.646579,1.165518,2.074986,0.960601,0.239913,0.211091,3.692527,1.172827,0.368281,0.105281,0.191598,0.863078,0.582537,1.164335,0.388112,0.107816,0.167750,2.079248,5.928170,0.095423,0.023838,0.715242,1.145451,1.261681,0.078945,0.011966,0.167528,0.469137,0.770324,0.274864,0.227017,1.181468,2.053122,1.262463,1.147128,1.506985,0.904879,0.646069,0.143466,0.363523,0.818862,0.539340,0.539721,0.107947,0.539934,1.513331,1.034564,0.625352,0.096265,0.000000,0.000000,0.076999,0.269356,0.302974,0.692952,0.693266,0.433107,0.432765,1.427862,0.476237,0.187698,0.626015,0.192754,0.106016,0.662590,1.807294,4.764455,3.168151,0.815015,0.040759,0.047979,0.575978,0.172769,0.057573,0.268790,0.672449,0.312301,1.560756,11.615479,4.168280,0.558258,0.062069,0.085984,1.118797,0.622255,0.478833,1.771856,0.265992,0.143826,2.059184,8.010041,5.017403,0.707453,0.314587,1.173014,0.293530,0.193322,0.386367,0.000000,0.000000,1.373004,0.657431,0.184184,0.167457,0.789217,0.788706,0.119487,0.095606,0.210334,0.263006,0.191339,0.497621,0.933816,0.179734,0.143863,0.115131,0.297568,0.595690,0.211547,0.079360,0.072141,0.384539,0.461251,0.403720,0.201957,0.043276,0.057698,0.538400,0.807189,0.230586,0.921670,3.794549,0.947274,0.143498,0.011958,0.050205,2.661253,1.142049,0.345192,1.227506,2.377724,2.229116,0.646980,0.409795,0.273354,0.014389,0.028781,0.662403,0.386756,0.151438,0.259655,0.288404,0.240262,0.024030,0.076874,1.305385,0.285315,0.100687,0.014383,0.035963,0.611494,0.122271,0.007191,0.014385,0.028776,0.062369

#### Cell 8：先滞后一个交易日，再计算过去 $L$ 个交易日的逐分钟历史中位数。

`shift(1)` 保证目标日 $t$ 仅使用截至 $t-1$ 的历史。
滚动窗口按完整交易日序列计数，并要求窗口内 $L$ 个有效观测；
遇到缺失历史日时，不向更早日期补足。下方既有打印标签“回望日历天数”应按 $L$ 个交易日理解。

In [34]:
lagged_shape_matrix = daily_shape_matrix.shift(1)

rolling_median_by_lookback = {}

for lookback in lookback_windows:
    rolling_median_by_lookback[lookback] = (
        lagged_shape_matrix
        .rolling(window=lookback, min_periods=lookback)
        .median()
    )

print(rolling_median_by_lookback.keys())
for key, value in  rolling_median_by_lookback.items():
    print("回望日历天数 lookback: ", key)
    print(value.columns)
    display(value.tail())

dict_keys([30, 60, 120, 360])
回望日历天数 lookback:  30
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,1.744258,1.289708,1.415416,1.829061,1.324606,1.277820,1.566195,1.853477,2.305179,1.016840,1.259648,1.509946,1.742393,1.406119,1.547350,1.601059,1.534522,1.171147,1.024449,1.008470,0.825666,0.752665,1.045208,0.734660,0.674831,1.186070,1.004819,0.765645,0.555731,0.698132,0.649486,0.853783,0.380392,0.386980,0.456986,0.790199,0.780180,1.194377,0.680796,0.672397,0.780130,0.776411,0.625908,0.649472,0.686232,0.618888,0.942753,0.794710,0.641392,0.552403,0.601283,0.835045,1.157539,0.684292,0.601674,0.37352,0.329793,0.702213,0.617085,0.499771,0.580485,0.624383,0.632096,0.372577,0.463445,0.534768,0.393332,0.350651,0.475347,0.343854,0.354776,0.520965,0.422041,0.602834,0.566896,0.821231,1.241213,0.692657,0.558502,0.440429,0.490753,0.317928,0.566959,0.974792,0.427920,0.403312,0.394241,0.261891,0.425583,0.362175,0.518765,0.631752,0.587181,0.500494,0.346361,0.420230,0.430879,0.510452,0.691327,0.597084,0.583424,0.494546,0.476261,0.504851,0.598138,0.598917,0.626256,0.792806,0.646102,0.79866,0.543440,0.296791,0.282416,0.425662,0.440816,0.388901,0.284708,0.586330,0.523501,0.388449,0.607826,0.514235,0.372191,0.521984,0.66398,0.505246,0.267741,0.511142,0.867104,0.567416,0.327521,0.457808,0.745031,0.286410,0.281814,0.423749,0.776063,0.763483,0.552304,0.266205,0.329278,0.560830,0.530127,0.514417,0.553770,0.386754,0.471502,0.595358,0.445988,0.370595,0.426469,0.569955,0.426237,0.383473,0.663847,0.426211,0.431925,0.639160,0.670312,0.667775,0.461462,0.334019,0.391202,0.566960,0.632698,0.341323,0.433260,0.539762,0.703104,0.649609,0.518733,0.616214,0.412825,0.363391,0.251384,0.445784,0.411557,0.463104,0.355421,0.356945,0.460674,0.720012,0.585242,0.324798,0.443886,0.519357,0.636088,0.592350,0.337052,0.239201,0.305899,0.468795,0.449477,0.411513,0.714596,0.354258,0.404419,0.415885,0.530567,0.797739,0.498995,0.635802,0.658875,0.576547,0.450285,0.430549,0.207624,0.180971,0.272778,0.337261,0.557727,0.623231,0.270801,0.539517,0.527685,0.195646,0.263516,0.297118,0.363227,0.355904,0.431997,0.264534,0.281139,0.234908,0.282248,0.338924,0.348311,0.447952,0.377640,0.297777,0.358342,0.288153,0.107082,0.169845,0.112192,0.115751,0.128720,0.179476,0.334906,0.175850
2026-08-25,1.916966,1.326616,1.337226,1.860642,1.293530,1.111692,1.566195,2.004835,2.305179,1.029772,1.509339,1.509946,2.046072,1.495316,1.629019,1.611978,1.534522,1.116720,1.024449,1.008470,0.919599,0.882460,1.045208,0.734660,0.814316,1.186070,1.004819,0.765645,0.601013,0.793997,0.554573,0.853783,0.444654,0.426863,0.440462,0.790199,0.812912,1.073604,0.680796,0.759953,0.780130,0.776411,0.625908,0.649472,0.686232,0.618888,0.942753,0.794710,0.598036,0.477401,0.601283,0.748254,1.000189,0.756329,0.659321,0.39649,0.367822,0.731895,0.617085,0.499771,0.580485,0.535490,0.613863,0.372577,0.557677,0.534768,0.370897,0.337388,0.475347,0.325089,0.354776,0.520965,0.453480,0.655352,0.651151,0.821231,1.241213,0.692657,0.558502,0.440429,0.490753,0.317928,0.590869,0.974792,0.427920,0.403312,0.418787,0.249904,0.329944,0.362175,0.470715,0.545925,0.587181,0.500494,0.346361,0.411330,0.430879,0.548572,0.850512,0.597084,0.583424,0.494546,0.476261,0.538015,0.641547,0.598917,0.626256,0.792806,0.546133,0.79866,0.543440,0.296791,0.290355,0.425662,0.421723,0.426870,0.284708,0.644025,0.523501,0.388449,0.614766,0.514235,0.415726,0.521984,0.66398,0.585075,0.303651,0.591848,0.860473,0.567416,0.327521,0.421051,0.708071,0.269854,0.205775,0.423749,0.776063,0.704691,0.552304,0.266205,0.275474,0.495006,0.429521,0.477893,0.553770,0.436619,0.471502,0.595358,0.441241,0.330243,0.398300,0.525304,0.497689,0.383473,0.609482,0.426211,0.431925,0.639160,0.675624,0.667775,0.426884,0.279168,0.292820,0.461246,0.655971,0.387108,0.413256,0.499147,0.598146,0.624688,0.436920,0.567473,0.387220,0.351295,0.251384,0.387329,0.399168,0.463104,0.355421,0.356945,0.432671,0.652414,0.552386,0.290749,0.443886,0.519357,0.534620,0.631998,0.427059,0.254213,0.305899,0.463817,0.449477,0.515935,0.738184,0.379389,0.498116,0.415885,0.530567,0.797739,0.498995,0.635802,0.674034,0.598977,0.474058,0.430549,0.174804,0.180971,0.283677,0.337261,0.642997,0.718092,0.270801,0.490954,0.477930,0.179588,0.263516,0.297118,0.363227,0.355904,0.411874,0.218797,0.292856,0.234908,0.307595,0.338924,0.348311,0.373029,0.377640,0.292109,0.347618,0.288153,0.107082,0.169845,0.086816,0.108798,0.103836,0.168106,0.320826,0.175850
2026-08-26,2.148479,1.211124,1.337226,1.860642,1.324606,1.277820,1.566195,2.004835,2.305179,1.029772,1.509339,1.509946,2.041010,1.495316,1.629019,1.625387,1.748466,1.116720,1.024449,1.008470,0.919599,0.882460,1.045208,0.734660,0.936483,1.186070,1.038586,0.765645,0.601013,0.798820,0.554573,0.853783,0.557615,0.451142,0.456986,0.799418,0.780180,0.988711,0.687529,0.759953,0.857311,0.846240,0.625908,0.649472,0.646757,0.602713,0.879518,0.794710,0.598036,0.477401,0.559490,0.716277,0.733136,0.756329,0.624088,0.39649,0.367822,0.731895,0.617085,0.499771,0.527250,0.418464,0.632096,0.341095,0.463445,0.534768,0.370897,0.342324,0.536647,0.296170,0.354776,0.520965,0.522849,0.669939,0.651151,0.821231,1.241213,0.692657,0.558502,0.481538,0.490753,0.341739,0.590869,0.828800,0.321301,0.403312,0.418787,0.249904,0.329944,0.362175,0.470715,0.545925,0.562494,0.489501,0.346361,0.411330,0.430879,0.510452,0.809891,0.597084,0.499273,0.460172,0.476261,0.538015,0.641547,0.668283,0.626256,0.792806,0.546133,0.79866,0.492672,0.356173,0.509090,0.425662,0.421723,0.426870,0.234511,0.644025,0.523501,0.388449,0.614766,0.514235,0.415726,0.503516,0.66398,0.574509,0.303651,0.591848,0.860473,0.540502,0.327521,0.527198,0.708071,0.269854,0.205775,0.423749,0.776063,0.704691,0.551324,0.314041,0.329278,0.495006,0.530127,0.477893,0.502352,0.386754,0.471502,0.595358,0.445988,0.370595,0.357776,0.491656,0.497689,0.383473,0.564712,0.426211,0.431925,0.629957,0.629798,0.693762,0.461462,0.334019,0.391202,0.461246,0.655971,0.387108,0.433260,0.539762,0.564629,0.624688,0.365791,0.457830,0.325471,0.351295,0.219791,0.387329,0.399168,0.435900,0.355421,0.356945,0.391257,0.652414,0.528763,0.324798,0.443886,0.519357,0.534620,0.631998,0.517578,0.252623,0.245956,0.463817,0.449477,0.564429,0.714596,0.354258,0.540989,0.442873,0.548298,0.753405,0.469278,0.635802,0.674034,0.576547,0.450285,0.463585,0.194516,0.180971,0.272778,0.337261,0.659558,0.718092,0.269469,0.385184,0.527215,0.195646,0.263516,0.342859,0.363227,0.355904,0.411874,0.218797,0.292856,0.234908,0.282248,0.330681,0.298594,0.373029,0.377640,0.279896,0.347618,0.288153,0.107082,0.169845,0.084275,0.115751,0.128720,0.168106,0.237289,0.175850
2026-08-27,2.148479,1.326616,1.415416,2.094021,1.438092,1.277820,1.566195,2.004835,2.305179,1.186840,1.697924,1.509946,1.742393,1.268602,1.340324,1.611978,1.748466,1.384262,1.036526,1.008470,0.919599,0.801420,1.010634,0.619546,0.814316,1.186070,1.038586,0.765645,0.726618,1.002628,0.539713,0.830959,0.557615,0.451142,0.456986,0.796954,0.642247,0.988711,0.757992,0.759953,0.857311,0.846240,0.625908,0.649472,0.646757,0.581124,0.809729,0.802346,0.641392,0.491615,0.592838,0.748254,0.768138,0.756329,0.580984,0.37352,0.329793,0.731895,0.617085,0.499771,0.527250,0.418464,0.632096,0.372577,0.463445,0.534768,0.373715,0.350651,0.602278,0.327412,0.369276,0.470394,0.453480,0.669939,0.684750,0.739063,1.044328,0.596742,0.558502,0.481538,0.513392,0.386177,0.592172,0.828800,0.427920,0.403312,0.394241,0.266386,0.425583,0.365262,0.470715,0.545925,0.562494,0.489501,0.309243,0.395621,0.430879,0.548572,0.809891,0.597084,0.450515,0.460172,0.523008,0.567414,0.641547,0.668283,0.626256,0.792806,0.546133,0.79866,0.466281,0.356173,0.509090,0.390463,0.440816,0.426870,0.218118,0.586330,0.471770,0.421057,0.614766,0.561931,0.448486,0.503516,0.66398,0.574509,0.286064,0.511142,0.781998,0.515870,0.327521,0.527198,0.678134,0.239061,0.175542,0.423749,0.745334,0.654863,0.551324,0.314041,0.365976,0.512682,0.468216,0.477893,0.502352,0.386754,0.471502,0.553632,0.443247,0.345846,0.357776,0.491656,0.426237,0.351963,0.564712,0.446575,0.467758,0.625231,0.629798,0.693762,0.494752,0.279168,0.292820,0.378185,0.632698,0.387108,0.413256,0.539762,0.564629,0.624688,0.365791,0.457830,0.325471,0.336094,0.211945,0.387329,0.399168,0.435900,0.355421,0.391671,0.391257,0.631019,0.528763,0.324798,0.443886,0.519357,0.534620,0.631998,0.528553,0.252623,0.245956,0.469580,0.449477,0.564429,0.714596,0.354258,0.540989,0.415885,0.530567,0.609663,0.419456,0.635802,0.675598,0.576547,0.450285,0.430549,0.194516,0.180971,0.272778,0.289385,0.659558,0.623231,0.269469,0.385184,0.527215,0.195646,0.263516,0.355669,0.404468,0.355904,0.382741,0.209011,0.239529,0.234908,0.269084,0.286412,0.253171,0.265642,0.377640,0.270674,0.292014,0.288153,0.096864,0.140228,0.078218,0.108798,0.120909,0.153275,0.167130,0.165766
2026-08-28,1.920496,1.326616,1.415416,2.094021,1.438092,1.277820,1.566195,2.004835,2.305179,1.199395,1.765900,1.509946,2.041010,1.495316,1.340324,1.611978,1.951363,1.622803,1.036526,1.120733,0.919599,0.772235,1.010634,0.619546,0.814316,1.000215,1.038586,0.877887,0.837861,1.002628,0.539713,0.830959,0.676099,0.451142,0.483189,0.841298,0.780180,0.988711,0.757992,0.759953,0.967922,0.872083,0.625908,0.566303,0.646757,0.581124,0.809729,0.826139,0.641392,0.491615,0.593214,0.835045,0.768138,0.684292,0.580984,0.37352,0.329793,0.731895,0.617085,0.504144,0.580485,0.418464,0.632096,0.341095,0.420114,0.600089,0.479002,0.343158,0.536647,0.374450,0.387401,0.470394,0.422041,0.602834,0.684750,0.653528,0.731270,0.596742,0.558502,0.481538,0.513392,0.378417,0.592172,0.974792,0.421191,0.403312,0.418787,0.286212,0.471855,0.365262,0.508606,0.545925,0.562494,0.514327,0.309243,0.411330,0.430879,0.548572,0.691327,0.577341,0.450515,0.460172,0.523008,0.567414,0.743948,0.741151,0.641192,0.715182,0.546133,0.79866,0.492672,0.466158,0.509090,0.425662,0.440816,0.426870,0.218118,0.551473,0.471770,0.421057,0.653417,0.561931,0.423091,0.503516,0.63400,0.677168,0.321200,0.511142,0.700951,0.443831,0.297412,0.421051,0.745031,0.269854,0.175542,0.387810,0.631155,0.693979,0.476039,0.266205,0.275474,0.415973,0.414280,0.477893,0.553770,0.436619,0.419579,0.553632,0.463799,0.345846,0.320543,0.454859,0.426237,0.351963,0.564712,0.597210,0.467758,0.625231,0.629798,0.693762,0.494752,0.260478,0.292820,0.378185,0.632698,0.387108,0.382156,0.539762,0.534701,0.624688,0.436920,0.457830,0.306308,0.336094,0.211945,0.347640,0.363933,0.435900,0.381933,0.407872,0.383474,0.524966,0.492611,0.290749,0.391058,0.432878,0.450239,0.592350,0.517578,0.213326,0.245956,0.469580,0.380655,0.481833,0.688162,0.413598,0.540989,0.415885,0.530567,0.609663,0.419456,0.635802,0.627680,0.576547,0.417918,0.360704,0.207624,0.199553,0.272778,0.289385,0.685231,0.623231,0.269469,0.385184,0.527215,0.195646,0.263516,0.307716,0.363227,0.355904,0.382741,0.255222,0.239529,0.234908,0.282248,0.286412,0.242687,0.174814,0.281902,0.292109,0.228393,0.192318,0.093453,0.105793,0.073815,0.106719,0.085933,0.150269,0.237289,0.177473

回望日历天数 lookback:  60
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,2.044299,1.858066,1.377397,1.800049,1.620350,0.974613,1.356323,2.004835,2.251627,1.287397,1.579068,1.426745,1.225515,1.383644,1.403817,1.601059,1.616864,1.449164,1.024449,1.025722,0.919599,0.901077,0.778224,0.734660,0.957857,0.97903,0.853884,0.769608,0.830590,0.806276,0.686692,0.985933,0.763576,0.489932,0.689298,0.768007,0.812912,1.033878,0.651760,0.718861,0.743511,0.728336,0.565981,0.793706,0.686232,0.655743,0.810755,0.759612,0.718911,0.584931,0.626609,0.748077,0.820696,0.618139,0.515369,0.405318,0.433828,0.727796,0.756816,0.455579,0.472595,0.390462,0.632096,0.742852,0.457251,0.471309,0.417857,0.500059,0.507125,0.351790,0.547907,0.613228,0.576403,0.738185,0.606334,0.798813,0.645298,0.580854,0.528668,0.422928,0.513392,0.392124,0.590869,0.599977,0.457775,0.438344,0.433966,0.529559,0.478311,0.386283,0.429883,0.552935,0.562494,0.524530,0.462671,0.395621,0.407487,0.505294,0.633100,0.602903,0.518618,0.449471,0.478470,0.315518,0.569490,0.598917,0.659433,0.790702,0.524876,0.382347,0.423635,0.367908,0.462130,0.368284,0.486285,0.484577,0.372871,0.413963,0.378643,0.343025,0.804369,0.764154,0.443969,0.521984,0.663980,0.505246,0.366655,0.475974,0.654741,0.466991,0.370144,0.411649,0.67033,0.352102,0.311475,0.335403,0.415943,0.533392,0.455801,0.363546,0.407585,0.407511,0.373739,0.416061,0.488266,0.436619,0.483939,0.558121,0.463799,0.369435,0.576042,0.685472,0.503944,0.393692,0.541912,0.643493,0.393785,0.534704,0.534881,0.612177,0.579703,0.468192,0.521249,0.522541,0.431110,0.303919,0.413256,0.495451,0.608461,0.557821,0.321244,0.459383,0.435649,0.379224,0.413965,0.347640,0.411557,0.459508,0.290789,0.244658,0.483765,0.616413,0.528763,0.532123,0.576660,0.606597,0.463619,0.556157,0.517923,0.334431,0.439395,0.395492,0.406337,0.283694,0.521538,0.284666,0.273202,0.381741,0.478467,0.444904,0.447293,0.523332,0.436545,0.415577,0.408361,0.430896,0.227731,0.247183,0.312098,0.337261,0.466102,0.629894,0.443100,0.522551,0.444587,0.213943,0.323653,0.342859,0.331536,0.374018,0.411874,0.315993,0.256992,0.352617,0.282248,0.323108,0.311139,0.260890,0.261983,0.297777,0.324819,0.257575,0.116212,0.164202,0.139592,0.108648,0.111578,0.163628,0.220536,0.157402
2026-08-25,2.121853,2.149023,1.377397,1.800049,1.438092,0.974613,1.422947,2.004835,2.251627,1.287397,1.579068,1.380498,1.324611,1.406119,1.485486,1.611978,1.590004,1.286382,1.024449,1.025722,0.953601,0.949335,0.949569,0.734660,0.957857,0.97903,0.853884,0.735449,0.830590,0.822105,0.666764,0.960918,0.763576,0.509268,0.631029,0.768007,0.812912,0.988711,0.651760,0.718861,0.743511,0.728336,0.565981,0.793706,0.686232,0.655743,0.799647,0.727562,0.718911,0.584931,0.635814,0.739381,0.820696,0.647249,0.541622,0.411837,0.463769,0.727796,0.794017,0.456304,0.454970,0.382555,0.613863,0.680580,0.474058,0.471309,0.399147,0.433200,0.475347,0.343854,0.547907,0.613228,0.581661,0.787494,0.642222,0.798813,0.645298,0.552523,0.528668,0.422928,0.513392,0.392124,0.627276,0.641058,0.418145,0.438344,0.440728,0.406262,0.464902,0.374101,0.418108,0.541603,0.523762,0.506344,0.406280,0.382965,0.358006,0.510452,0.656778,0.585847,0.518618,0.399533,0.462401,0.330444,0.581957,0.598917,0.659433,0.748595,0.503047,0.382347,0.423635,0.367908,0.516647,0.389305,0.468404,0.513225,0.390855,0.413963,0.378643,0.343025,0.804369,0.670301,0.443969,0.521984,0.663980,0.505246,0.366655,0.475974,0.593898,0.466991,0.370144,0.405219,0.67033,0.330558,0.311475,0.335403,0.415943,0.506107,0.455801,0.352848,0.369263,0.407511,0.373739,0.416061,0.502352,0.436619,0.483939,0.558121,0.445988,0.340734,0.508453,0.622228,0.514322,0.404728,0.541912,0.643493,0.393785,0.534704,0.554574,0.577420,0.545223,0.468192,0.521249,0.522541,0.467680,0.319177,0.413256,0.495451,0.608461,0.569748,0.307959,0.415094,0.412825,0.371162,0.426515,0.347640,0.411557,0.459508,0.316401,0.259454,0.483765,0.616413,0.528763,0.491891,0.550940,0.606597,0.463619,0.583331,0.517923,0.334431,0.439395,0.359322,0.390282,0.283694,0.566235,0.284666,0.294521,0.398594,0.478761,0.484978,0.450107,0.545219,0.436545,0.415577,0.408361,0.407768,0.224512,0.247183,0.312134,0.327214,0.477975,0.676035,0.431206,0.489477,0.435699,0.202696,0.323653,0.342859,0.343093,0.374018,0.388709,0.290914,0.256992,0.380317,0.307595,0.306021,0.348311,0.291425,0.310863,0.292109,0.285784,0.257575,0.116212,0.164202,0.112192,0.107969,0.104446,0.163628,0.193036,0.144766
2026-08-26,2.226034,2.149023,1.351401,1.683029,1.620350,1.106229,1.356323,1.920466,2.251627,1.287397,1.579068,1.380498,1.324611,1.383644,1.403817,1.625387,1.590004,1.286382,1.024449,1.025722,0.953601,0.985774,1.010634,0.807539,1.007371,0.97903,0.908507,0.701094,0.830590,0.884826,0.686692,0.941943,0.811856,0.532928,0.631029,0.768007,0.812912,0.988711,0.651760,0.718861,0.743511,0.758379,0.543717,0.782869,0.686232,0.635949,0.794916,0.759612,0.722613,0.602428,0.635814,0.739381,0.820696,0.665492,0.551375,0.417269,0.498312,0.727796,0.756816,0.456304,0.454970,0.382555,0.632096,0.634026,0.457251,0.475729,0.399147,0.433200,0.475347,0.338315,0.474101,0.613228,0.602311,0.787494,0.606334,0.778352,0.645298,0.552523,0.472574,0.422928,0.490753,0.392124,0.627276,0.641058,0.391532,0.438344,0.440728,0.529559,0.464902,0.362175,0.418108,0.541603,0.498405,0.506344,0.406280,0.382965,0.358006,0.476909,0.656778,0.585847,0.518618,0.399533,0.462401,0.367714,0.600215,0.598917,0.646422,0.711143,0.503047,0.382347,0.423635,0.402016,0.516647,0.389305,0.486285,0.513225,0.372871,0.413963,0.378643,0.361562,0.804369,0.670301,0.450630,0.521984,0.689878,0.514668,0.409391,0.500940,0.593898,0.414639,0.370144,0.405219,0.67033,0.352102,0.311475,0.335403,0.415943,0.533392,0.455801,0.352848,0.407585,0.438396,0.376526,0.416061,0.502352,0.436619,0.492374,0.558121,0.445988,0.340734,0.444387,0.584932,0.514322,0.393692,0.539140,0.734388,0.415965,0.534704,0.554574,0.577420,0.545223,0.468192,0.530979,0.522541,0.467680,0.303919,0.413256,0.514947,0.608461,0.557821,0.307959,0.406554,0.387220,0.366937,0.413965,0.347640,0.411557,0.459508,0.316401,0.244658,0.460674,0.628051,0.528763,0.454382,0.520303,0.551804,0.463619,0.583331,0.528553,0.334431,0.439395,0.359322,0.366354,0.298991,0.566235,0.284666,0.326130,0.404001,0.482536,0.484978,0.450107,0.545219,0.436545,0.383132,0.387833,0.407768,0.221009,0.229379,0.302357,0.321847,0.477975,0.629894,0.410864,0.457880,0.435699,0.202696,0.323653,0.355669,0.343093,0.360134,0.370299,0.276666,0.250016,0.380317,0.282248,0.281619,0.348311,0.291425,0.310863,0.292109,0.285784,0.233428,0.116212,0.164202,0.086816,0.108648,0.104515,0.168106,0.193036,0.144766
2026-08-27,2.121853,1.918437,1.377397,1.800049,1.620350,1.106229,1.356323,1.889860,2.127351,1.429117,1.688519,1.380498,1.324611,1.343799,1.258655,1.625387,1.748466,1.449164,1.036526,1.025722,0.953601,0.949335,0.949569,0.734660,1.007371,1.04101,0.934282,0.735449,0.830590,0.884826,0.666764,0.901762,0.860398,0.532928,0.565928,0.746809,0.798378,0.960648,0.651760,0.718861,0.756360,0.806453,0.543717,0.782869,0.686232,0.618888,0.775994,0.759612,0.722613,0.584931,0.653138,0.748254,0.820696,0.647249,0.541622,0.411837,0.463769,0.731895,0.756816,0.456304,0.472595,0.382555,0.632096,0.634026,0.457251,0.475729,0.417857,0.433200,0.475347,0.343854,0.547907,0.577765,0.581661,0.819204,0.642222,0.778352,0.645298,0.552523,0.416320,0.410744,0.490753,0.392124,0.592172,0.664839,0.418145,0.438344,0.440728,0.529559,0.478311,0.365262,0.429883,0.541603,0.498405,0.506344,0.406280,0.389493,0.358006,0.510452,0.656778,0.578933,0.469860,0.399533,0.478470,0.407979,0.600215,0.640854,0.641192,0.696304,0.495372,0.382347,0.353829,0.367908,0.462130,0.368284,0.488621,0.535234,0.363173,0.413963,0.378643,0.361562,0.804369,0.764154,0.455147,0.524307,0.695956,0.543341,0.409391,0.500940,0.593898,0.414639,0.370144,0.405219,0.67033,0.352102,0.283386,0.335403,0.415943,0.533392,0.476039,0.352848,0.407585,0.438396,0.376526,0.418854,0.502352,0.436619,0.491298,0.534359,0.445988,0.340734,0.508453,0.584932,0.503944,0.383473,0.539140,0.756919,0.431925,0.534704,0.534881,0.577420,0.599300,0.426845,0.521249,0.460600,0.467680,0.319177,0.413256,0.514947,0.608461,0.557821,0.289398,0.406554,0.387220,0.359528,0.411455,0.360463,0.411557,0.459508,0.328400,0.259454,0.432671,0.616413,0.528763,0.392700,0.520303,0.551804,0.452821,0.583331,0.561062,0.334431,0.439395,0.359322,0.352447,0.298991,0.566235,0.284666,0.291261,0.404001,0.479693,0.444904,0.450107,0.545219,0.465760,0.383132,0.370468,0.360704,0.224512,0.247183,0.312134,0.321847,0.477975,0.629894,0.431206,0.489477,0.420929,0.201206,0.348180,0.368027,0.350772,0.363817,0.370299,0.276666,0.250016,0.408950,0.282248,0.264686,0.348311,0.291425,0.310863,0.292109,0.285784,0.233428,0.112424,0.164202,0.086816,0.108648,0.104515,0.168106,0.193036,0.157402
2026-08-28,2.121853,2.149023,1.418832,1.829061,1.707993,1.243308,1.422947,1.920466,2.127351,1.287397,1.744899,1.426745,1.418531,1.383644,1.258655,1.625387,1.748466,1.449164,1.036526,1.080554,1.007200,0.901077,0.949569,0.665870,0.936483,0.97903,0.934282,0.769608,0.864856,0.884826,0.666764,0.853783,0.860398,0.532928,0.565928,0.746809,0.812912,0.988711,0.680796,0.762265,0.756360,0.806453,0.543717,0.689827,0.676499,0.602713,0.775994,0.764660,0.722613,0.584931,0.635814,0.748254,0.748863,0.647249,0.541622,0.405318,0.463769,0.731895,0.756816,0.456304,0.472595,0.382555,0.632096,0.583174,0.457251,0.475729,0.417857,0.372820,0.475347,0.351790,0.566877,0.577765,0.576403,0.787494,0.642222,0.778352,0.645298,0.580854,0.459982,0.422928,0.490753,0.386381,0.592172,0.696607,0.391532,0.418838,0.476985,0.583973,0.518546,0.374101,0.429883,0.516404,0.498405,0.506344,0.462671,0.395621,0.358006,0.510452,0.656778,0.578933,0.441866,0.384919,0.462401,0.441427,0.600215,0.640854,0.641192,0.696304,0.522793,0.408896,0.423635,0.367908,0.365391,0.389305,0.489228,0.538625,0.372871,0.433206,0.378643,0.365520,0.804369,0.670301,0.450630,0.540802,0.695956,0.543341,0.409391,0.500940,0.508002,0.387929,0.348363,0.359253,0.67033,0.352102,0.317033,0.317400,0.415943,0.534463,0.476039,0.352848,0.369263,0.407511,0.373739,0.418854,0.523175,0.447802,0.483939,0.526026,0.445988,0.321023,0.444387,0.542992,0.503944,0.383473,0.539140,0.776603,0.431925,0.505969,0.506151,0.546677,0.545223,0.426845,0.521039,0.399306,0.440383,0.356581,0.413256,0.514947,0.608461,0.557821,0.307959,0.456627,0.372758,0.357202,0.411455,0.360463,0.411557,0.459508,0.350010,0.280629,0.421002,0.593328,0.528763,0.338071,0.502093,0.480076,0.447190,0.583331,0.561062,0.311030,0.419883,0.347652,0.352447,0.298991,0.521538,0.284666,0.266939,0.398594,0.414341,0.444904,0.450107,0.523332,0.465760,0.383132,0.370468,0.309601,0.224512,0.247183,0.302357,0.309363,0.496456,0.580419,0.410864,0.457880,0.420929,0.202696,0.368503,0.368027,0.343093,0.363817,0.388709,0.290914,0.250016,0.408950,0.282248,0.253009,0.348311,0.291425,0.260296,0.292109,0.246411,0.233428,0.112424,0.164202,0.081051,0.107969,0.104515,0.168106,0.193036,0.165766

回望日历天数 lookback:  120
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,2.461031,2.548271,1.596765,1.993283,1.939121,1.416912,1.507239,2.295070,2.210346,1.442481,1.828928,1.491879,1.450033,1.407575,1.233703,1.479561,1.453214,1.184075,1.064235,1.159671,1.035516,1.168313,1.023168,0.854232,0.853720,0.903255,0.802911,0.778061,0.875017,0.919379,0.796584,0.941943,0.763377,0.789857,0.818759,0.790199,0.812912,0.988711,0.813280,0.748996,0.784080,0.728336,0.565981,0.784418,0.602024,0.635376,0.818239,0.719818,0.706464,0.541236,0.525645,0.695966,0.740905,0.518817,0.510379,0.452186,0.422754,0.550521,0.611642,0.424370,0.462953,0.394534,0.641795,0.691250,0.518411,0.584213,0.450950,0.476662,0.555290,0.586565,0.487545,0.568940,0.536982,0.57383,0.519863,0.686219,0.638566,0.587053,0.475692,0.454649,0.440659,0.317928,0.531958,0.484053,0.460370,0.572429,0.487307,0.486630,0.392847,0.367032,0.479585,0.719646,0.596039,0.543709,0.422941,0.390533,0.456301,0.501955,0.521964,0.512163,0.383761,0.384088,0.439787,0.312455,0.490309,0.495657,0.580575,0.611017,0.475404,0.373485,0.451762,0.458963,0.565192,0.368284,0.528697,0.449591,0.364562,0.422584,0.389914,0.340894,0.984588,1.076222,0.674364,0.469382,0.564136,0.607996,0.538484,0.475974,0.432149,0.521896,0.439941,0.457642,0.576299,0.301021,0.281978,0.324359,0.330988,0.481545,0.394957,0.314041,0.266142,0.389700,0.391063,0.416061,0.385627,0.357607,0.406982,0.408348,0.383736,0.310532,0.440824,0.590289,0.49014,0.357167,0.505215,0.578978,0.456628,0.474328,0.375590,0.426718,0.493084,0.427586,0.435134,0.316922,0.404814,0.401483,0.413256,0.378137,0.421155,0.347230,0.340442,0.419733,0.412825,0.391674,0.372229,0.318144,0.405512,0.469300,0.279767,0.253522,0.552377,0.740346,0.516546,0.432725,0.484168,0.494527,0.374206,0.360330,0.337052,0.332949,0.416768,0.412113,0.382623,0.316219,0.377358,0.331138,0.277241,0.265875,0.335246,0.384874,0.341879,0.288590,0.360884,0.353067,0.335373,0.377669,0.234694,0.246152,0.292257,0.327214,0.437099,0.459931,0.289063,0.467213,0.446412,0.251714,0.256896,0.240443,0.343093,0.284694,0.260701,0.233580,0.218962,0.290407,0.245489,0.280300,0.245195,0.197702,0.212317,0.246739,0.269182,0.257575,0.111619,0.144343,0.136349,0.109281,0.131024,0.198437,0.285824,0.191547
2026-08-25,2.564203,2.675080,1.596765,1.993283,1.872493,1.416912,1.582676,2.295070,2.210346,1.442481,1.828928,1.473882,1.450033,1.407575,1.296601,1.494906,1.453214,1.171802,1.057840,1.214259,1.089360,1.186664,1.023168,0.854232,0.871392,0.903255,0.802127,0.778061,0.898285,0.935367,0.796584,0.941943,0.763377,0.716124,0.814180,0.790199,0.812912,0.960648,0.813280,0.748996,0.784080,0.735816,0.579903,0.777872,0.587517,0.635376,0.808157,0.711945,0.693913,0.541236,0.527374,0.695966,0.740905,0.518817,0.510379,0.452186,0.422754,0.550521,0.616095,0.428988,0.462953,0.388769,0.641795,0.657224,0.518411,0.562773,0.436693,0.476662,0.542981,0.573467,0.455818,0.562659,0.536982,0.57383,0.519863,0.686219,0.645298,0.587053,0.475692,0.454649,0.440659,0.317928,0.546933,0.521493,0.441874,0.552038,0.504897,0.486630,0.392847,0.367032,0.447093,0.688514,0.589052,0.538751,0.422941,0.390533,0.433930,0.505880,0.556621,0.512163,0.383761,0.384088,0.439787,0.315518,0.490309,0.495657,0.580575,0.611017,0.475404,0.381923,0.451762,0.458963,0.565192,0.368284,0.528697,0.472672,0.364562,0.422584,0.386228,0.326893,1.016076,1.076222,0.652257,0.469382,0.564136,0.607996,0.559444,0.485983,0.432149,0.521896,0.458691,0.457642,0.543522,0.286521,0.280376,0.317400,0.330988,0.481545,0.394957,0.314041,0.252940,0.389700,0.391063,0.412064,0.385627,0.357607,0.406982,0.408348,0.383736,0.310532,0.440824,0.590289,0.49014,0.368706,0.505215,0.578978,0.439536,0.474328,0.387664,0.426718,0.493084,0.427586,0.425043,0.316922,0.404814,0.401483,0.413256,0.378137,0.421155,0.354960,0.340442,0.419733,0.394689,0.391674,0.383850,0.311965,0.395884,0.469300,0.304271,0.260919,0.552377,0.740346,0.516546,0.414082,0.475984,0.494527,0.374206,0.360330,0.351767,0.337403,0.416768,0.397924,0.382623,0.340417,0.389035,0.332490,0.282766,0.285991,0.347526,0.384874,0.341879,0.288590,0.377969,0.370822,0.339402,0.377669,0.234694,0.250204,0.292257,0.321847,0.444975,0.459931,0.289063,0.467213,0.439110,0.242661,0.256896,0.242870,0.350772,0.293583,0.260701,0.225995,0.227785,0.294624,0.256348,0.270510,0.245195,0.197702,0.212317,0.252545,0.262304,0.257575,0.116212,0.145246,0.136349,0.109281,0.126334,0.195445,0.281229,0.185571
2026-08-26,2.640127,2.675080,1.553853,1.993283,1.939121,1.416912,1.582676,2.295070,2.251627,1.446566,1.828928,1.491879,1.494497,1.405969,1.233703,1.519111,1.482304,1.171802,1.057840,1.159671,1.089360,1.202343,1.023168,0.854232,0.916506,0.903255,0.802911,0.764397,0.875017,0.935367,0.796584,0.903156,0.794746,0.789857,0.818759,0.793646,0.812912,0.948877,0.813280,0.748996,0.784080,0.742523,0.579903,0.777872,0.579094,0.618888,0.799647,0.711945,0.693913,0.557826,0.527374,0.695966,0.740905,0.518817,0.529392,0.452186,0.422754,0.550521,0.616095,0.438369,0.462953,0.388769,0.641795,0.657224,0.518411,0.584213,0.436693,0.476662,0.555290,0.543785,0.434597,0.560136,0.536982,0.59476,0.519863,0.686219,0.638566,0.580854,0.475692,0.465300,0.440659,0.317928,0.546933,0.484053,0.423279,0.552038,0.504897,0.486630,0.377075,0.367032,0.447093,0.688514,0.587181,0.522067,0.422941,0.390533,0.433930,0.505880,0.597616,0.512163,0.383761,0.384919,0.439787,0.315518,0.490309,0.506351,0.580575,0.611017,0.475404,0.381923,0.451762,0.470757,0.605078,0.368284,0.528697,0.487460,0.364562,0.418540,0.386228,0.340894,1.016076,1.076222,0.674364,0.475749,0.587182,0.600454,0.559444,0.485983,0.432149,0.513198,0.458691,0.462652,0.566496,0.301021,0.281978,0.317400,0.337710,0.508639,0.394957,0.314041,0.252940,0.408452,0.396579,0.407545,0.380362,0.357607,0.432496,0.442605,0.424285,0.310532,0.440824,0.590289,0.49014,0.368706,0.493670,0.578978,0.439536,0.465438,0.409920,0.447427,0.503789,0.446323,0.435134,0.316922,0.384888,0.390153,0.413256,0.384140,0.421155,0.347230,0.321244,0.415094,0.392922,0.391674,0.383850,0.311965,0.405512,0.469300,0.304271,0.253522,0.537815,0.740346,0.516546,0.414082,0.470328,0.494102,0.359135,0.360330,0.376529,0.337403,0.416768,0.397924,0.382623,0.340417,0.377358,0.331138,0.282766,0.285991,0.347526,0.384874,0.341879,0.279627,0.377969,0.370822,0.335373,0.395268,0.227731,0.246152,0.283677,0.321847,0.446471,0.420453,0.289063,0.467213,0.446412,0.242661,0.256896,0.242870,0.350772,0.290674,0.253249,0.222089,0.218962,0.294624,0.245489,0.267136,0.235538,0.197702,0.212317,0.252545,0.262304,0.257575,0.116212,0.145246,0.133848,0.109406,0.126334,0.195445,0.281229,0.183200
2026-08-27,2.640127,2.548271,1.553853,2.051586,1.939121,1.416912,1.582676,2.219125,2.210346,1.466644,1.840634,1.491879,1.450033,1.383644,1.233703,1.519111,1.521086,1.184075,1.057840,1.159671,1.089360,1.202343,1.023168,0.854232,0.916506,0.903255,0.802911,0.778061,0.898285,0.935367,0.794713,0.903156,0.811856,0.872667,0.818759,0.793646,0.807598,0.948877,0.819069,0.773226,0.835603,0.761629,0.635798,0.779542,0.579094,0.618888,0.799647,0.719818,0.706464,0.541236,0.527374,0.695966,0.734766,0.518817,0.529392,0.452186,0.400556,0.550521,0.620084,0.464960,0.472595,0.394534,0.641795,0.691250,0.518411,0.562773,0.450950,0.481503,0.555290,0.520479,0.434597,0.543258,0.525123,0.59476,0.519863,0.672094,0.624904,0.580854,0.468377,0.454649,0.455557,0.323304,0.561678,0.521493,0.441874,0.519295,0.487307,0.493334,0.392847,0.367032,0.479585,0.719646,0.589052,0.522067,0.408829,0.386591,0.433930,0.505880,0.556621,0.512163,0.383761,0.384088,0.439787,0.315518,0.490309,0.506351,0.575608,0.611017,0.475404,0.382347,0.451762,0.458963,0.565192,0.361445,0.540471,0.496791,0.364562,0.418540,0.382308,0.340894,1.051076,1.148843,0.674364,0.475749,0.587182,0.600454,0.538484,0.475974,0.432111,0.500684,0.458691,0.462652,0.566496,0.301021,0.281978,0.324359,0.337710,0.481545,0.394957,0.331204,0.266142,0.408452,0.396579,0.412064,0.377857,0.353323,0.432496,0.442605,0.424285,0.310532,0.440824,0.604662,0.49014,0.368706,0.493670,0.590628,0.456628,0.465438,0.387664,0.426718,0.503789,0.427586,0.425043,0.314490,0.384888,0.390153,0.399713,0.378137,0.421155,0.347230,0.310676,0.415094,0.392922,0.391674,0.383850,0.311965,0.395884,0.454714,0.316401,0.253522,0.510862,0.740346,0.516546,0.414082,0.470328,0.494102,0.373797,0.385697,0.433110,0.347534,0.416768,0.397924,0.366354,0.316219,0.364797,0.329801,0.277241,0.285991,0.347526,0.384874,0.341879,0.279627,0.386548,0.353067,0.327923,0.377669,0.227731,0.250204,0.292257,0.321847,0.446471,0.404429,0.289063,0.467213,0.439110,0.237624,0.256896,0.252747,0.350772,0.313121,0.248266,0.216591,0.212263,0.308012,0.245489,0.261312,0.235538,0.197702,0.212317,0.252545,0.262304,0.257575,0.116212,0.145246,0.133848,0.109406,0.126334,0.195445,0.281229,0.183200
2026-08-28,2.640127,2.675080,1.553853,2.130786,2.029736,1.416912,1.582676,2.184152,2.168890,1.466644,1.840634,1.491879,1.450033,1.383644,1.233703,1.519111,1.521086,1.222475,1.057840,1.132706,1.089360,1.186664,1.023168,0.854232,0.916506,0.903255,0.810348,0.818528,0.926192,0.945714,0.794713,0.872923,0.794746,0.872667,0.818759,0.793646,0.807598,0.960648,0.836151,0.773226,0.835603,0.761629,0.635798,0.753448,0.579094,0.602713,0.794916,0.742399,0.706464,0.534989,0.527374,0.706327,0.728417,0.518817,0.529392,0.441979,0.384623,0.550521,0.620084,0.490711,0.472595,0.394534,0.642249,0.691250,0.518411,0.562773,0.450950,0.476662,0.542981,0.543785,0.434597,0.543258,0.513159,0.57383,0.519863,0.653528,0.605101,0.587053,0.475692,0.454649,0.463234,0.336646,0.561678,0.553516,0.441874,0.519295,0.504897,0.524941,0.392847,0.372482,0.508606,0.719646,0.596039,0.538751,0.422941,0.390533,0.389444,0.501955,0.556621,0.484003,0.381240,0.384088,0.439787,0.315518,0.490309,0.506351,0.575608,0.611017,0.483054,0.386010,0.451762,0.470757,0.565192,0.368284,0.540471,0.501634,0.372871,0.418540,0.382308,0.355623,1.051076,1.148843,0.652257,0.493022,0.596025,0.607996,0.559444,0.485983,0.432111,0.490842,0.458691,0.462652,0.576299,0.301021,0.281978,0.324359,0.337710,0.481545,0.375887,0.331204,0.266142,0.408452,0.396579,0.416061,0.380362,0.357607,0.432496,0.442605,0.440154,0.310532,0.440824,0.604662,0.49014,0.368706,0.493670,0.591660,0.476527,0.467090,0.387664,0.384739,0.503789,0.419238,0.425043,0.307503,0.364208,0.401483,0.399713,0.378137,0.421155,0.347394,0.310676,0.415094,0.392922,0.391674,0.400631,0.311965,0.395884,0.454714,0.328400,0.260919,0.510862,0.724266,0.505946,0.414082,0.470328,0.480755,0.359135,0.360330,0.433110,0.347534,0.381352,0.397924,0.352447,0.308571,0.352309,0.329801,0.273202,0.265875,0.335246,0.384874,0.330140,0.272889,0.386548,0.354997,0.327923,0.377669,0.227731,0.253100,0.292257,0.309363,0.454663,0.404429,0.284024,0.457880,0.439110,0.242661,0.263516,0.252747,0.343093,0.313121,0.248266,0.218382,0.218962,0.329501,0.256348,0.261312,0.235538,0.193328,0.203567,0.264079,0.262304,0.241395,0.116212,0.145246,0.128157,0.108648,0.122541,0.195445,0.281229,0.183200

回望日历天数 lookback:  360
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,4.640836,4.043054,2.233957,1.996005,2.007368,1.770184,1.798330,1.872153,1.605569,1.308700,1.539837,1.546812,1.325164,1.181679,1.138830,1.134066,0.95494,0.902009,0.949703,1.007458,1.159837,0.985600,0.933431,0.788454,0.856980,0.764989,0.652661,0.737873,0.857997,0.856359,0.903944,0.825217,0.711377,0.759228,0.741035,0.749594,0.692049,0.738717,0.723870,0.702001,0.594905,0.613976,0.556134,0.599432,0.569158,0.631492,0.655935,0.635243,0.664991,0.549113,0.543165,0.620537,0.571243,0.480227,0.530539,0.446859,0.447914,0.472076,0.436268,0.462144,0.490447,0.476480,0.636076,0.575030,0.508944,0.492361,0.448330,0.437489,0.423750,0.410713,0.386306,0.404507,0.462581,0.469995,0.407563,0.440144,0.406011,0.409533,0.361438,0.335304,0.387276,0.345838,0.418142,0.494083,0.407982,0.411255,0.435110,0.426281,0.355377,0.396579,0.463455,0.541603,0.503848,0.496555,0.446352,0.373886,0.363954,0.423392,0.428034,0.424993,0.375753,0.400694,0.437980,0.358473,0.429783,0.448429,0.560209,0.495558,0.465537,0.422381,0.465372,0.495649,0.405916,0.457257,0.481364,0.448141,0.391926,0.412320,0.357727,0.37863,0.809133,0.838893,0.569660,0.523669,0.500498,0.483428,0.425366,0.411975,0.395754,0.394260,0.357782,0.355721,0.390028,0.295157,0.311082,0.322372,0.356995,0.367114,0.360590,0.346148,0.264808,0.330852,0.331702,0.317189,0.325083,0.361757,0.298598,0.278354,0.328609,0.262573,0.316416,0.436442,0.414582,0.357370,0.444825,0.410552,0.359364,0.307652,0.302770,0.310145,0.344516,0.335208,0.348490,0.289259,0.350024,0.390153,0.365944,0.298393,0.362966,0.354210,0.316865,0.344223,0.336685,0.351295,0.326951,0.329977,0.323003,0.385836,0.296065,0.350770,0.547897,0.621549,0.564532,0.517696,0.514053,0.463270,0.452061,0.418775,0.345158,0.354983,0.398116,0.396235,0.396164,0.319222,0.347526,0.339924,0.273948,0.298636,0.321431,0.355201,0.323619,0.304981,0.323251,0.309556,0.300190,0.259731,0.224512,0.222721,0.287685,0.294228,0.401926,0.577399,0.478919,0.446811,0.385465,0.315857,0.344698,0.326548,0.319598,0.340264,0.282869,0.278858,0.265279,0.277673,0.252871,0.288587,0.289516,0.239919,0.233886,0.249817,0.255900,0.26268,0.186894,0.170088,0.145137,0.158911,0.179070,0.213251,0.224244,0.198211
2026-08-25,4.738419,3.987680,2.194558,1.996005,1.995013,1.754899,1.830037,1.881430,1.609711,1.310800,1.539837,1.543018,1.336192,1.181679,1.138830,1.134066,0.94065,0.899130,0.949703,1.012030,1.167048,0.989161,0.938582,0.793190,0.864324,0.764989,0.652661,0.729310,0.864856,0.868114,0.896157,0.821936,0.711377,0.753222,0.729784,0.749594,0.692049,0.733011,0.723870,0.702001,0.597155,0.613976,0.556134,0.599432,0.569158,0.631492,0.658399,0.635243,0.657426,0.545020,0.543165,0.620537,0.571243,0.480227,0.530539,0.453045,0.454082,0.472076,0.439432,0.455106,0.488594,0.475114,0.636076,0.568211,0.508944,0.492361,0.448330,0.437489,0.423750,0.410713,0.386306,0.404507,0.462581,0.469995,0.407943,0.443461,0.406011,0.409533,0.361438,0.333938,0.381998,0.344080,0.418142,0.498736,0.407982,0.409369,0.436654,0.425087,0.354601,0.394157,0.459471,0.541021,0.500792,0.490034,0.446352,0.373886,0.362288,0.425323,0.430402,0.418921,0.370490,0.397335,0.433827,0.358473,0.429783,0.448429,0.562947,0.495558,0.456947,0.422381,0.465372,0.498480,0.412528,0.467283,0.481364,0.455236,0.395304,0.414946,0.357727,0.37863,0.809133,0.833928,0.564358,0.523669,0.500498,0.483428,0.430489,0.420225,0.391608,0.390826,0.357782,0.352995,0.387740,0.295157,0.311082,0.319206,0.353502,0.363242,0.357497,0.341374,0.263041,0.324928,0.331702,0.317189,0.325083,0.369596,0.298598,0.278354,0.323176,0.260939,0.310794,0.436442,0.423039,0.358275,0.440391,0.410552,0.359364,0.313460,0.302770,0.309070,0.343585,0.335208,0.348490,0.290093,0.352911,0.390153,0.361959,0.293964,0.358326,0.354210,0.312667,0.344223,0.329364,0.351295,0.329180,0.329977,0.323003,0.389678,0.297961,0.350770,0.538393,0.619035,0.563374,0.516747,0.514053,0.453357,0.452061,0.423999,0.352291,0.354983,0.398116,0.387588,0.396164,0.322230,0.347526,0.339924,0.273948,0.306136,0.323396,0.365125,0.326490,0.304981,0.327056,0.312551,0.304763,0.257488,0.223054,0.222721,0.295182,0.288590,0.404778,0.581805,0.474082,0.444062,0.385465,0.315857,0.344698,0.326548,0.320792,0.351920,0.280817,0.276494,0.265279,0.287827,0.255051,0.287268,0.289516,0.239919,0.233886,0.249817,0.255484,0.26268,0.187315,0.171005,0.145137,0.158911,0.176076,0.212306,0.224244,0.198211
2026-08-26,4.738419,3.932917,2.194558,1.996005,1.995013,1.754899,1.798330,1.881430,1.623524,1.314056,1.555308,1.543018,1.336192,1.174867,1.119228,1.139393,0.95494,0.902009,0.956381,1.007458,1.167048,0.990805,0.938582,0.797221,0.871116,0.760720,0.662816,0.729310,0.864856,0.868114,0.903944,0.821936,0.715872,0.759228,0.741035,0.760798,0.692049,0.733011,0.723870,0.702001,0.597155,0.613976,0.551954,0.597276,0.558635,0.631492,0.658399,0.635243,0.657426,0.545020,0.536657,0.611713,0.570447,0.480227,0.530539,0.453045,0.454082,0.468380,0.436268,0.462144,0.488594,0.475114,0.636076,0.568211,0.508944,0.498693,0.437666,0.434799,0.431213,0.404823,0.386306,0.404507,0.462581,0.469995,0.407563,0.440144,0.402739,0.403782,0.361438,0.333938,0.381998,0.345838,0.426593,0.498736,0.407982,0.411255,0.440728,0.426281,0.348146,0.394157,0.459471,0.541021,0.493593,0.483389,0.435511,0.368345,0.358006,0.423392,0.430402,0.411790,0.370490,0.400694,0.433827,0.358473,0.429783,0.448429,0.560209,0.488190,0.448062,0.417969,0.461043,0.498480,0.412528,0.467283,0.483616,0.459675,0.395304,0.412320,0.355576,0.37863,0.809133,0.833928,0.564358,0.521984,0.500498,0.487290,0.436358,0.420978,0.391608,0.388499,0.357782,0.352995,0.387740,0.295157,0.311082,0.319206,0.356995,0.367114,0.360590,0.346148,0.264808,0.330852,0.331702,0.316293,0.322251,0.361757,0.302339,0.279663,0.328609,0.260939,0.303638,0.431979,0.423039,0.358275,0.440391,0.410552,0.359364,0.313460,0.304578,0.310145,0.343585,0.335984,0.351851,0.290093,0.352911,0.390153,0.365944,0.298393,0.353594,0.352447,0.306478,0.336580,0.320845,0.348863,0.326951,0.329977,0.325560,0.389678,0.297961,0.347469,0.537795,0.619035,0.560603,0.515506,0.510131,0.442928,0.450035,0.418775,0.357794,0.354983,0.398116,0.381169,0.391076,0.330987,0.347526,0.339924,0.275326,0.311033,0.326738,0.365125,0.323619,0.301439,0.327056,0.312551,0.300190,0.257488,0.220332,0.222721,0.295182,0.288590,0.408299,0.581805,0.474082,0.444062,0.385465,0.315857,0.350842,0.326609,0.320792,0.340264,0.277511,0.274669,0.265279,0.289700,0.252871,0.286022,0.289516,0.239919,0.233886,0.249817,0.255484,0.26268,0.187315,0.170088,0.145137,0.160679,0.176076,0.212306,0.224244,0.198211
2026-08-27,4.640836,3.854641,2.194558,2.009614,2.007368,1.754899,1.798330,1.872153,1.623524,1.320190,1.571821,1.543018,1.336192,1.149826,1.111408,1.139393,0.95494,0.902009,0.956381,1.007458,1.167048,0.989161,0.938582,0.793190,0.864324,0.760720,0.667309,0.737873,0.864856,0.868114,0.896157,0.811780,0.720415,0.766328,0.741035,0.760798,0.685197,0.731233,0.723870,0.702001,0.597155,0.613976,0.556134,0.599432,0.558635,0.621033,0.658399,0.635243,0.657426,0.545020,0.543165,0.611713,0.570447,0.480227,0.530539,0.453045,0.454082,0.468380,0.436268,0.462144,0.488594,0.476480,0.638205,0.568211,0.499899,0.498693,0.448330,0.437489,0.431213,0.404823,0.386306,0.404507,0.462581,0.472293,0.407943,0.436006,0.399873,0.400120,0.359088,0.333938,0.387276,0.345838,0.426593,0.498736,0.407982,0.409369,0.436654,0.426281,0.348146,0.394157,0.463455,0.541603,0.493593,0.483389,0.425632,0.368345,0.362288,0.425323,0.430402,0.418921,0.375753,0.400694,0.437980,0.361381,0.436868,0.451915,0.552400,0.481746,0.445817,0.417969,0.457330,0.495649,0.412528,0.467283,0.483616,0.459675,0.391926,0.407136,0.348695,0.37863,0.809133,0.833928,0.564358,0.523669,0.501509,0.487290,0.436358,0.420978,0.391608,0.388499,0.358267,0.355721,0.390028,0.295157,0.311082,0.319206,0.356995,0.364123,0.364842,0.352416,0.267514,0.330852,0.339625,0.317189,0.319510,0.361757,0.306378,0.279663,0.328609,0.259877,0.303638,0.436442,0.414582,0.358275,0.444825,0.412431,0.359364,0.315232,0.304578,0.309070,0.344516,0.335984,0.351851,0.289259,0.352911,0.395856,0.365944,0.293964,0.350312,0.352447,0.306478,0.336580,0.320845,0.346917,0.326585,0.335668,0.332272,0.389678,0.299123,0.350770,0.537795,0.619035,0.558254,0.513567,0.499194,0.434743,0.450035,0.415798,0.357794,0.354983,0.398116,0.387588,0.391076,0.322230,0.347526,0.339924,0.275326,0.313449,0.326738,0.355201,0.319668,0.301439,0.331193,0.312551,0.300190,0.257488,0.223054,0.231948,0.295182,0.288590,0.408299,0.577399,0.468565,0.444062,0.385465,0.315857,0.344698,0.329307,0.322061,0.340264,0.277511,0.274669,0.265279,0.289700,0.249891,0.279408,0.283202,0.239464,0.233886,0.249817,0.255484,0.26268,0.187315,0.169334,0.145137,0.158911,0.174562,0.211592,0.224244,0.198211
2026-08-28,4.640836,3.932917,2.233957,2.014601,2.032547,1.770184,1.830037,1.872153,1.609711,1.314056,1.571821,1.543018,1.336192,1.149826,1.111408,1.139393,0.95494,0.902009,0.949703,1.012030,1.167377,0.985600,0.938582,0.788454,0.856980,0.757428,0.667309,0.738691,0.875017,0.878793,0.896157,0.811780,0.720415,0.766328,0.741035,0.768007,0.692049,0.733011,0.736426,0.702001,0.597155,0.613976,0.556134,0.599432,0.550917,0.610631,0.658399,0.635243,0.654612,0.542270,0.543714,0.620537,0.570447,0.479215,0.530539,0.453045,0.447914,0.464459,0.431568,0.462144,0.490447,0.481911,0.640096,0.564780,0.499899,0.505753,0.459081,0.434799,0.423750,0.410713,0.388741,0.404507,0.462581,0.469995,0.407943,0.432282,0.399873,0.403782,0.359088,0.335304,0.390827,0.346968,0.426593,0.498736,0.405353,0.401427,0.436654,0.429005,0.354601,0.394157,0.463455,0.541021,0.500792,0.490034,0.425632,0.368345,0.362288,0.425323,0.430402,0.418921,0.375753,0.397335,0.433827,0.361381,0.440653,0.454849,0.560209,0.481746,0.448062,0.422381,0.457330,0.498480,0.412528,0.473558,0.483616,0.459675,0.391926,0.407136,0.348695,0.37863,0.817674,0.833928,0.564358,0.524540,0.504173,0.487290,0.436358,0.425194,0.390404,0.385601,0.357782,0.352995,0.391030,0.295157,0.311731,0.319206,0.353502,0.364123,0.364842,0.352416,0.264808,0.324928,0.331702,0.317933,0.322251,0.369596,0.306378,0.281753,0.328609,0.256951,0.303638,0.436442,0.414582,0.359320,0.444825,0.412431,0.360362,0.315232,0.302770,0.308372,0.344516,0.335984,0.351851,0.289259,0.352911,0.395856,0.361959,0.289407,0.348722,0.352447,0.312667,0.344223,0.329364,0.348863,0.326585,0.329977,0.332272,0.389678,0.304516,0.353183,0.537795,0.619035,0.558254,0.513567,0.499194,0.434743,0.447263,0.412336,0.352291,0.354114,0.385379,0.381169,0.391076,0.319222,0.340906,0.339924,0.273948,0.311033,0.323396,0.355201,0.319668,0.301439,0.334763,0.312551,0.298207,0.254449,0.223054,0.231948,0.287685,0.284251,0.408299,0.571274,0.464655,0.442639,0.385465,0.315857,0.344698,0.326609,0.320792,0.340264,0.280817,0.276494,0.265279,0.289700,0.249891,0.270510,0.280199,0.238171,0.233642,0.249817,0.255484,0.26268,0.186894,0.169091,0.145137,0.156557,0.174562,0.211592,0.225306,0.201982

### 季节曲线归一化：估计混合贡献因子

对此前 $L$ 个交易日的 $x^{\mathrm{mix}}$，逐分钟取中位数；
再将得到的历史曲线归一到日内均值 1：

$$
\widehat g^{\mathrm{mix},(L)}_{t,i}
=
\frac{
\operatorname{median}_{h=t-L,\ldots,t-1}x^{\mathrm{mix}}_{h,i}
}{
M^{-1}\sum_{j=1}^{M}
\operatorname{median}_{h=t-L,\ldots,t-1}x^{\mathrm{mix}}_{h,j}
}.
$$

帽号表示它由历史样本估计得到，$(L)$ 表示所用回望窗口。
逐分钟取中位数后，整条曲线的均值未必仍为 1，因此需要第二次归一化。
大于 1 表示该分钟的历史典型相对贡献高于这条曲线的平均水平，
小于 1 表示低于平均水平。归一化只使用历史估计曲线，不使用目标日的实际贡献。

$\widehat g^{\mathrm{mix},(L)}$ 是**混合贡献季节因子**。
其估计对象与收益的方差周期 $f^2$ 有关，但两者不能由此定义直接画等号。

#### Cell 9：把历史中位数曲线归一化为日内分钟均值 1。

历史截至前一交易日由上面的 `shift(1)` 保证；当前结果未单独保存历史截止日期字段。

In [38]:
seasonality_by_lookback = {}

for lookback in lookback_windows:
    rolling_median_matrix = rolling_median_by_lookback[lookback]
    curve_mean_series = rolling_median_matrix.mean(axis=1)

    seasonality_by_lookback[lookback] = rolling_median_matrix.div(
        curve_mean_series.where(curve_mean_series > 0),
        axis=0,
    )

In [41]:
print(seasonality_by_lookback.keys())
for key, value in  seasonality_by_lookback.items():
    print("回望日历天数 lookback: ", key)
    print(value.columns)
    display(value.tail())

dict_keys([30, 60, 120, 360])
回望日历天数 lookback:  30
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,2.949197,2.180643,2.393191,3.092583,2.239649,2.160542,2.648128,3.133866,3.897606,1.719277,2.129818,2.553023,2.946045,2.377471,2.616266,2.707076,2.594575,1.980180,1.732143,1.705125,1.396039,1.272609,1.767241,1.242166,1.141006,2.005411,1.698951,1.294555,0.939632,1.180404,1.098154,1.443580,0.643168,0.654308,0.772674,1.336071,1.319132,2.019457,1.151092,1.136892,1.319046,1.312758,1.058288,1.098129,1.160283,1.046418,1.594011,1.343699,1.084469,0.934006,1.016651,1.411898,1.957172,1.157003,1.017313,0.631549,0.557615,1.187304,1.043369,0.845014,0.981487,1.055709,1.068750,0.629954,0.783595,0.904187,0.665047,0.592882,0.803718,0.581390,0.599857,0.880850,0.713588,1.019274,0.958511,1.388541,2.098647,1.171147,0.944317,0.744679,0.829766,0.537553,0.958616,1.648183,0.723529,0.681922,0.666584,0.442807,0.719578,0.612367,0.877131,1.068169,0.992807,0.846237,0.585628,0.710527,0.728532,0.863074,1.168899,1.009552,0.986456,0.836181,0.805263,0.853604,1.011334,1.012651,1.058876,1.340479,1.092431,1.350377,0.918850,0.501816,0.477510,0.719712,0.745333,0.657556,0.481385,0.991369,0.885138,0.656790,1.027715,0.869471,0.629303,0.882573,1.122660,0.854271,0.452697,0.864241,1.466102,0.959389,0.553774,0.774063,1.259702,0.484263,0.476492,0.716477,1.312170,1.290899,0.933838,0.450101,0.556744,0.948254,0.896340,0.869779,0.936316,0.653926,0.797218,1.006634,0.754078,0.626603,0.721076,0.963682,0.720684,0.648378,1.122436,0.720640,0.730300,1.080694,1.133366,1.129076,0.780242,0.564761,0.661446,0.958619,1.069768,0.577110,0.732558,0.912631,1.188811,1.098361,0.877075,1.041897,0.698005,0.614423,0.425041,0.753733,0.695861,0.783017,0.600947,0.603524,0.778910,1.217399,0.989530,0.549170,0.750524,0.878131,1.075499,1.001548,0.569889,0.404442,0.517216,0.792640,0.759978,0.695787,1.208241,0.598981,0.683794,0.703180,0.897084,1.348820,0.843703,1.075017,1.114028,0.974827,0.761344,0.727974,0.351052,0.305986,0.461214,0.570243,0.943006,1.053762,0.457871,0.912217,0.892212,0.330800,0.445554,0.502368,0.614145,0.601764,0.730422,0.447275,0.475351,0.397183,0.477226,0.573053,0.588926,0.757399,0.638516,0.503482,0.605886,0.487210,0.181055,0.287174,0.189694,0.195713,0.217641,0.303458,0.566260,0.297328
2026-08-25,3.231963,2.236646,2.254534,3.137002,2.180863,1.874288,2.640570,3.380108,3.886482,1.736173,2.544713,2.545737,3.449632,2.521071,2.746490,2.717759,2.587170,1.882765,1.727199,1.700258,1.550424,1.487808,1.762197,1.238621,1.372920,1.999688,1.694102,1.290861,1.013295,1.338662,0.934998,1.439460,0.749677,0.719683,0.742610,1.332257,1.370551,1.810072,1.147807,1.281265,1.315281,1.309011,1.055267,1.094995,1.156972,1.043431,1.589462,1.339864,1.008275,0.804887,1.013749,1.261540,1.686297,1.275154,1.111601,0.668473,0.620140,1.233959,1.040391,0.842603,0.978685,0.902824,1.034959,0.628157,0.940231,0.901607,0.625325,0.568829,0.801424,0.548092,0.598145,0.878336,0.764557,1.104909,1.097826,1.384578,2.092658,1.167804,0.941621,0.742554,0.827398,0.536019,0.996193,1.643478,0.721464,0.679976,0.706066,0.421333,0.556278,0.610619,0.793616,0.920417,0.989974,0.843822,0.583956,0.693494,0.726452,0.924880,1.433944,1.006670,0.983641,0.833794,0.802965,0.907081,1.081633,1.009761,1.055854,1.336653,0.920768,1.346523,0.916228,0.500384,0.489533,0.717658,0.711015,0.719693,0.480011,1.085812,0.882612,0.654916,1.036483,0.866990,0.700905,0.880054,1.119456,0.986424,0.511950,0.997843,1.450738,0.956651,0.552193,0.709882,1.193793,0.454968,0.346931,0.714432,1.308425,1.188094,0.931173,0.448816,0.464444,0.834570,0.724163,0.805718,0.933644,0.736130,0.794942,1.003761,0.743922,0.556782,0.671526,0.885652,0.839092,0.646527,1.027574,0.718583,0.728216,1.077610,1.139087,1.125854,0.719718,0.470672,0.493687,0.777651,1.105953,0.652656,0.696741,0.841551,1.008460,1.053210,0.736637,0.956746,0.652844,0.592276,0.423828,0.653028,0.672988,0.780782,0.599232,0.601802,0.729473,1.099955,0.931311,0.490197,0.748382,0.875625,0.901358,1.065536,0.720013,0.428597,0.515739,0.781985,0.757809,0.869855,1.244561,0.639641,0.839812,0.701173,0.894524,1.344970,0.841295,1.071949,1.136406,1.009862,0.799252,0.725896,0.294715,0.305113,0.478273,0.568615,1.084079,1.210687,0.456564,0.827738,0.805780,0.302781,0.444283,0.500934,0.612393,0.600046,0.694410,0.368887,0.493749,0.396049,0.518599,0.571418,0.587245,0.628918,0.636693,0.492489,0.586076,0.485819,0.180539,0.286354,0.146371,0.183432,0.175065,0.283423,0.540905,0.296479
2026-08-26,3.624620,2.043242,2.255984,3.139020,2.234694,2.155762,2.642269,3.382282,3.888982,1.737290,2.546350,2.547374,3.443313,2.522693,2.748257,2.742130,2.949772,1.883976,1.728310,1.701352,1.551422,1.488765,1.763331,1.239418,1.579905,2.000974,1.752159,1.291691,1.013947,1.347659,0.935600,1.440386,0.940732,0.761104,0.770964,1.348668,1.316213,1.668018,1.159905,1.282089,1.446338,1.427660,1.055946,1.095700,1.091120,1.016815,1.483802,1.340726,1.008924,0.805405,0.943894,1.208405,1.236847,1.275975,1.052876,0.668903,0.620538,1.234752,1.041060,0.843145,0.889504,0.705976,1.066385,0.575449,0.781861,0.902187,0.625727,0.577522,0.905356,0.499657,0.598530,0.878901,0.882078,1.130230,1.098532,1.385468,2.094004,1.168556,0.942227,0.812384,0.827930,0.576535,0.996834,1.398238,0.542056,0.680413,0.706521,0.421604,0.556636,0.611012,0.794127,0.921009,0.948962,0.825819,0.584332,0.693940,0.726920,0.861164,1.366337,1.007318,0.842306,0.776340,0.803482,0.907665,1.082329,1.127435,1.056533,1.337513,0.921360,1.347390,0.831168,0.600886,0.858867,0.718119,0.711472,0.720156,0.395635,1.086511,0.883180,0.655337,1.037149,0.867548,0.701356,0.849463,1.120176,0.969233,0.512279,0.998485,1.451671,0.911861,0.552548,0.889415,1.194561,0.455261,0.347155,0.714892,1.309267,1.188859,0.930118,0.529806,0.555512,0.835107,0.894357,0.806236,0.847499,0.652479,0.795454,1.004407,0.752410,0.625216,0.603590,0.829454,0.839632,0.646943,0.952704,0.719045,0.728685,1.062777,1.062508,1.170419,0.778515,0.563511,0.659983,0.778152,1.106664,0.653076,0.730937,0.910612,0.952565,1.053887,0.617112,0.772388,0.549090,0.592657,0.370801,0.653448,0.673421,0.735390,0.599617,0.602189,0.660075,1.100663,0.892056,0.547955,0.748863,0.876188,0.901938,1.066221,0.873187,0.426190,0.414943,0.782488,0.758297,0.952226,1.205568,0.597656,0.912682,0.747154,0.925014,1.271041,0.791701,1.072639,1.137137,0.972670,0.759660,0.782097,0.328161,0.305309,0.460193,0.568981,1.112717,1.211466,0.454611,0.649830,0.889445,0.330068,0.444568,0.578424,0.612787,0.600432,0.694857,0.369124,0.494067,0.396304,0.476170,0.557879,0.503747,0.629323,0.637103,0.472202,0.586453,0.486132,0.180655,0.286539,0.142176,0.195280,0.217159,0.283605,0.400322,0.296670
2026-08-27,3.663995,2.262398,2.413836,3.571122,2.452508,2.179181,2.670973,3.419025,3.931229,2.024024,2.895622,2.575047,2.971460,2.163461,2.285774,2.749050,2.981816,2.360706,1.767681,1.719834,1.568275,1.366733,1.723526,1.056567,1.388727,2.022711,1.771193,1.305723,1.239167,1.709872,0.920422,1.417108,0.950951,0.769372,0.779339,1.359117,1.095281,1.686138,1.292671,1.296017,1.462050,1.443169,1.067417,1.107602,1.102973,0.991044,1.380904,1.368313,1.093824,0.838396,1.011020,1.276064,1.309975,1.289836,0.990803,0.636997,0.562425,1.248166,1.052370,0.852304,0.899167,0.713645,1.077970,0.635389,0.790354,0.911987,0.637330,0.597997,1.027118,0.558365,0.629759,0.802205,0.773360,1.142508,1.167766,1.260391,1.780986,1.017678,0.952463,0.821210,0.875533,0.658582,1.009885,1.413428,0.729771,0.687805,0.672334,0.454292,0.725785,0.622914,0.802753,0.931014,0.959271,0.834791,0.527380,0.674688,0.734816,0.935529,1.381180,1.018261,0.768304,0.784773,0.891932,0.967661,1.094087,1.139683,1.068010,1.352043,0.931369,1.362027,0.795191,0.607414,0.868197,0.665892,0.751763,0.727980,0.371976,0.999921,0.804551,0.718066,1.048416,0.958311,0.764844,0.858691,1.132345,0.979762,0.487851,0.871696,1.333612,0.879759,0.558551,0.899077,1.156484,0.407693,0.299368,0.722658,1.271085,1.116797,0.940222,0.535562,0.624132,0.874322,0.798491,0.814994,0.856706,0.659567,0.804095,0.944159,0.755909,0.589802,0.610147,0.838465,0.726901,0.600234,0.963053,0.761585,0.797710,1.066263,1.074050,1.183134,0.843744,0.476091,0.499371,0.644953,1.078996,0.660170,0.704763,0.920504,0.962913,1.065336,0.623815,0.780779,0.555055,0.573172,0.361449,0.660546,0.680737,0.743379,0.606131,0.667953,0.667246,1.076133,0.901746,0.553908,0.756998,0.885706,0.911736,1.077804,0.901388,0.430820,0.419450,0.800817,0.766534,0.962571,1.218664,0.604149,0.922597,0.709246,0.904823,1.039713,0.715335,1.084291,1.152158,0.983237,0.767912,0.734254,0.331726,0.308625,0.465193,0.493515,1.124804,1.062852,0.459550,0.656890,0.899108,0.333653,0.449398,0.606554,0.689775,0.606955,0.652723,0.356445,0.408491,0.400609,0.458893,0.488444,0.431756,0.453024,0.644024,0.461604,0.497998,0.491413,0.165192,0.239143,0.133393,0.185544,0.206198,0.261393,0.285023,0.282695
2026-08-28,3.277861,2.264240,2.415801,3.574029,2.454505,2.180955,2.673148,3.421809,3.934430,2.047102,3.014000,2.577144,3.483552,2.552174,2.287635,2.751289,3.330545,2.769766,1.769120,1.912842,1.569552,1.318033,1.724929,1.057427,1.389857,1.707145,1.772636,1.498359,1.430043,1.711264,0.921171,1.418262,1.153952,0.769999,0.824696,1.435909,1.331595,1.687511,1.293724,1.297072,1.652029,1.488452,1.068286,0.966554,1.103871,0.991851,1.382028,1.410036,1.094715,0.839078,1.012485,1.425237,1.311041,1.167934,0.991610,0.637515,0.562883,1.249182,1.053227,0.860462,0.990760,0.714226,1.078847,0.582174,0.717042,1.024220,0.817550,0.585695,0.915937,0.639103,0.661207,0.802858,0.720330,1.028904,1.168716,1.115428,1.248116,1.018506,0.953238,0.821878,0.876246,0.645873,1.010707,1.663754,0.718880,0.688365,0.714777,0.488500,0.805353,0.623421,0.868077,0.931772,0.960052,0.877843,0.527810,0.702050,0.735415,0.936290,1.179943,0.985393,0.768929,0.785412,0.892658,0.968449,1.269754,1.264980,1.094372,1.220657,0.932127,1.363136,0.840881,0.795628,0.868904,0.726511,0.752375,0.728572,0.372279,0.941241,0.805206,0.718650,1.115238,0.959092,0.722123,0.859390,1.082098,1.155775,0.548217,0.872406,1.196369,0.757521,0.507617,0.718640,1.271603,0.460581,0.299612,0.661905,1.077241,1.184468,0.812493,0.454353,0.470173,0.709974,0.707085,0.815658,0.945163,0.745211,0.716129,0.944927,0.791603,0.590282,0.547096,0.776343,0.727492,0.600722,0.963838,1.019305,0.798359,1.067131,1.074925,1.184097,0.844431,0.444578,0.499778,0.645478,1.079875,0.660708,0.652256,0.921254,0.912615,1.066203,0.745725,0.781414,0.522799,0.573638,0.361743,0.593344,0.621153,0.743984,0.651875,0.696147,0.654506,0.896000,0.840778,0.496245,0.667450,0.738826,0.768458,1.011011,0.883391,0.364100,0.419792,0.801469,0.649693,0.822382,1.174539,0.705920,0.923348,0.709824,0.905559,1.040560,0.715918,1.085174,1.071310,0.984037,0.713293,0.615642,0.354369,0.340592,0.465571,0.493917,1.169537,1.063717,0.459924,0.657424,0.899840,0.333925,0.449764,0.525203,0.619948,0.607449,0.653254,0.435608,0.408824,0.400936,0.481735,0.488842,0.414212,0.298369,0.481145,0.498565,0.389817,0.328244,0.159504,0.180565,0.125986,0.182146,0.146668,0.256475,0.405001,0.302907

回望日历天数 lookback:  60
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,3.501789,3.182782,2.359418,3.083400,2.775584,1.669467,2.323319,3.434190,3.856933,2.205251,2.704870,2.443947,2.099250,2.370118,2.404674,2.742540,2.769613,2.482351,1.754834,1.757014,1.575231,1.543503,1.333062,1.258439,1.640766,1.677034,1.462664,1.318303,1.422762,1.381114,1.176272,1.688858,1.307970,0.839231,1.180735,1.315560,1.392480,1.770985,1.116434,1.231376,1.273600,1.247606,0.969500,1.359581,1.175483,1.123257,1.388786,1.301180,1.231461,1.001959,1.073352,1.281422,1.405815,1.058843,0.882804,0.694290,0.743127,1.246681,1.296390,0.780385,0.809534,0.668844,1.082751,1.272471,0.783251,0.807330,0.715771,0.856578,0.868682,0.602600,0.938540,1.050431,0.987351,1.264476,1.038621,1.368330,1.105365,0.994977,0.905583,0.724456,0.879416,0.671690,1.012132,1.027733,0.784147,0.750863,0.743363,0.907109,0.819324,0.661685,0.736370,0.947153,0.963526,0.898496,0.792534,0.677680,0.698007,0.865545,1.084471,1.032745,0.888369,0.769923,0.819597,0.540468,0.975510,1.025917,1.129579,1.354435,0.899089,0.654943,0.725667,0.630210,0.791607,0.630854,0.832984,0.830058,0.638711,0.709099,0.648597,0.587586,1.377847,1.308961,0.760499,0.894135,1.137367,0.865462,0.628063,0.815321,1.121540,0.799933,0.634039,0.705135,1.148244,0.603135,0.533542,0.574529,0.712492,0.913676,0.780765,0.622738,0.698175,0.698048,0.640197,0.712693,0.836378,0.747908,0.828965,0.956035,0.794467,0.632825,0.986733,1.174182,0.863233,0.674377,0.928270,1.102273,0.674535,0.915922,0.916226,1.048631,0.993004,0.801992,0.892876,0.895088,0.738472,0.520599,0.707889,0.848685,1.042266,0.955522,0.550277,0.786901,0.746247,0.649593,0.709103,0.595491,0.704977,0.787115,0.498108,0.419087,0.828667,1.055886,0.905746,0.911502,0.987791,1.039073,0.794158,0.952671,0.887178,0.572865,0.752663,0.677459,0.696036,0.485954,0.893370,0.487620,0.467982,0.653905,0.819593,0.762100,0.766193,0.896444,0.747782,0.711865,0.699504,0.738105,0.390092,0.423414,0.534610,0.577713,0.798412,1.078979,0.759010,0.895106,0.761557,0.366474,0.554403,0.587301,0.567906,0.640676,0.705521,0.541281,0.440216,0.604017,0.483478,0.553469,0.532966,0.446893,0.448765,0.510078,0.556401,0.441214,0.199066,0.281270,0.239114,0.186108,0.191128,0.280287,0.377768,0.269623
2026-08-25,3.645826,3.692510,2.366682,3.092893,2.470970,1.674607,2.444946,3.444762,3.868807,2.212041,2.713198,2.372009,2.275983,2.416032,2.552403,2.769744,2.731989,2.210297,1.760237,1.762423,1.638504,1.631174,1.631576,1.262313,1.645817,1.682197,1.467167,1.263669,1.427142,1.412563,1.145653,1.651076,1.311997,0.875037,1.084252,1.319610,1.396767,1.698831,1.119871,1.235167,1.277521,1.251447,0.972485,1.363767,1.179102,1.126715,1.373975,1.250117,1.235252,1.005044,1.092473,1.270424,1.410143,1.112120,0.930630,0.707629,0.796860,1.250519,1.364302,0.784033,0.781742,0.657317,1.054756,1.169391,0.814540,0.809815,0.685825,0.744337,0.816754,0.590820,0.941430,1.053665,0.999426,1.353093,1.103484,1.372543,1.108768,0.949360,0.908371,0.726687,0.882124,0.673758,1.077803,1.101483,0.718469,0.753175,0.757271,0.698050,0.798807,0.642791,0.718405,0.930596,0.899942,0.870015,0.698082,0.658020,0.615136,0.877073,1.128494,1.006619,0.891104,0.686488,0.794511,0.567779,0.999935,1.029076,1.133057,1.286257,0.864348,0.656959,0.727901,0.632150,0.887718,0.668915,0.804824,0.881837,0.671577,0.711282,0.650594,0.589395,1.382089,1.151729,0.762840,0.896888,1.140869,0.868127,0.629997,0.817831,1.020451,0.802396,0.635991,0.696258,1.151780,0.567973,0.535185,0.576298,0.714685,0.869606,0.783169,0.606272,0.634478,0.700197,0.642168,0.714887,0.863155,0.750210,0.831517,0.958979,0.766309,0.585459,0.873638,1.069129,0.883722,0.695415,0.931128,1.105667,0.676612,0.918742,0.952884,0.992139,0.936817,0.804461,0.895625,0.897844,0.803580,0.548418,0.710068,0.851298,1.045475,0.978956,0.529144,0.713226,0.709327,0.637741,0.732850,0.597325,0.707148,0.789539,0.543648,0.445801,0.831218,1.059137,0.908535,0.845181,0.946641,1.042272,0.796603,1.002296,0.889909,0.574629,0.754981,0.617396,0.670593,0.487450,0.972921,0.489121,0.506054,0.684875,0.822620,0.833303,0.773386,0.936811,0.750084,0.714057,0.701658,0.700637,0.385763,0.424717,0.536318,0.562229,0.821270,1.161582,0.740910,0.841032,0.748629,0.348277,0.556110,0.589109,0.589513,0.642648,0.667890,0.499857,0.441571,0.653471,0.528519,0.525814,0.598478,0.500734,0.534133,0.501909,0.491043,0.442573,0.199679,0.282136,0.192771,0.185515,0.179463,0.281150,0.331679,0.248741
2026-08-26,3.824244,3.691943,2.321658,2.891383,2.783702,1.900461,2.330113,3.299290,3.868212,2.211701,2.712781,2.371644,2.275633,2.377050,2.411707,2.792355,2.731569,2.209957,1.759967,1.762152,1.638253,1.693524,1.736233,1.387322,1.730626,1.681938,1.560782,1.204454,1.426923,1.520099,1.179712,1.618224,1.394739,0.915551,1.084085,1.319407,1.396553,1.698570,1.119699,1.234977,1.277324,1.302867,0.934086,1.344940,1.178921,1.092537,1.365637,1.304985,1.241422,1.034950,1.092305,1.270229,1.409926,1.143291,0.947242,0.716853,0.856082,1.250327,1.300182,0.783913,0.781622,0.657216,1.085917,1.089233,0.785541,0.817285,0.685719,0.744222,0.816628,0.581214,0.814488,1.053503,1.034749,1.352886,1.041659,1.337181,1.108598,0.949214,0.811864,0.726575,0.843095,0.673655,1.077637,1.101314,0.672637,0.753059,0.757154,0.909762,0.798684,0.622204,0.718294,0.930453,0.856241,0.869881,0.697974,0.657919,0.615041,0.819312,1.128321,1.006464,0.890967,0.686383,0.794388,0.631720,1.031147,1.028918,1.110530,1.221717,0.864216,0.656858,0.727789,0.690649,0.887581,0.668812,0.835420,0.881702,0.640579,0.711173,0.650494,0.621150,1.381877,1.151552,0.774166,0.896750,1.185185,0.884180,0.703319,0.860596,1.020294,0.712335,0.635894,0.696151,1.151603,0.604899,0.535103,0.576210,0.714576,0.916348,0.783049,0.606179,0.700217,0.753148,0.646859,0.714777,0.863022,0.750095,0.845880,0.958831,0.766191,0.585369,0.763440,1.004892,0.883587,0.676349,0.926222,1.261652,0.714613,0.918601,0.952738,0.991986,0.936673,0.804337,0.912202,0.897706,0.803457,0.522121,0.709959,0.884660,1.045314,0.958317,0.529063,0.698445,0.665230,0.630385,0.711177,0.597233,0.707039,0.789417,0.543565,0.420313,0.791421,1.078969,0.908395,0.780612,0.893862,0.947979,0.796480,1.002142,0.908034,0.574541,0.754865,0.617302,0.629382,0.513655,0.972772,0.489046,0.560279,0.694059,0.828979,0.833175,0.773267,0.936667,0.749969,0.658207,0.666283,0.700530,0.379686,0.394064,0.519438,0.552922,0.821144,1.082135,0.705849,0.786621,0.748514,0.348224,0.556024,0.611026,0.589422,0.618698,0.636160,0.475302,0.429518,0.653370,0.484892,0.483811,0.598386,0.500657,0.534051,0.501832,0.490967,0.401022,0.199648,0.282092,0.149147,0.186652,0.179553,0.288800,0.331628,0.248702
2026-08-27,3.648123,3.298387,2.368173,3.094842,2.785883,1.901950,2.331940,3.249255,3.657576,2.457095,2.903088,2.373503,2.277416,2.310407,2.164018,2.794544,3.006155,2.491562,1.782109,1.763533,1.639536,1.632201,1.632603,1.263109,1.731982,1.789818,1.606320,1.264465,1.428041,1.521291,1.146374,1.550408,1.479290,0.916268,0.973005,1.283995,1.372659,1.651651,1.120577,1.235945,1.300417,1.386543,0.934818,1.345994,1.179845,1.064060,1.334174,1.306008,1.242395,1.005677,1.122947,1.286480,1.411031,1.112821,0.931216,0.708075,0.797362,1.258354,1.301201,0.784527,0.812538,0.657731,1.086768,1.090087,0.786157,0.817925,0.718427,0.744806,0.817268,0.591192,0.942023,0.993356,1.000055,1.408466,1.104179,1.338229,1.109467,0.949958,0.715784,0.706196,0.843756,0.674183,1.018128,1.143065,0.718921,0.753649,0.757748,0.910475,0.822364,0.627998,0.739102,0.931183,0.856913,0.870563,0.698521,0.669659,0.615523,0.877625,1.129205,0.995366,0.807835,0.686920,0.822638,0.701442,1.031955,1.101827,1.102407,1.197162,0.851697,0.657373,0.608341,0.632548,0.794545,0.633195,0.840091,0.920233,0.624407,0.711730,0.651004,0.621637,1.382960,1.313818,0.782539,0.901446,1.196565,0.934171,0.703870,0.861271,1.021094,0.712893,0.636392,0.696696,1.152505,0.605373,0.487229,0.576661,0.715136,0.917067,0.818458,0.606654,0.700766,0.753738,0.647365,0.720139,0.863698,0.750683,0.844694,0.918729,0.766791,0.585828,0.874188,1.005679,0.866436,0.659309,0.926948,1.301379,0.742613,0.919321,0.919626,0.992764,1.030382,0.733878,0.896189,0.791914,0.804086,0.548763,0.710516,0.885353,1.046133,0.959068,0.497564,0.698992,0.665751,0.618140,0.707418,0.619747,0.707593,0.790036,0.564621,0.446082,0.743895,1.059804,0.909107,0.675172,0.894562,0.948722,0.778540,1.002928,0.964639,0.574991,0.755456,0.617785,0.605965,0.514057,0.973534,0.489429,0.500768,0.694603,0.824742,0.764927,0.773873,0.937401,0.800786,0.658723,0.636949,0.620162,0.386006,0.424985,0.536656,0.553355,0.821788,1.082983,0.741377,0.841562,0.723708,0.345936,0.598630,0.632753,0.603086,0.625515,0.636658,0.475674,0.429855,0.703111,0.485272,0.455077,0.598855,0.501050,0.534470,0.502225,0.491352,0.401336,0.193291,0.282313,0.149264,0.186799,0.179694,0.289026,0.331888,0.270623
2026-08-28,3.659527,3.706387,2.447037,3.154553,2.945750,2.144314,2.454134,3.312198,3.669010,2.220354,3.009401,2.460684,2.446518,2.386349,2.170783,2.803280,3.015552,2.499351,1.787680,1.863614,1.737102,1.554074,1.637707,1.148416,1.615137,1.688519,1.611342,1.327331,1.491604,1.526047,1.149958,1.472507,1.483915,0.919133,0.976047,1.288009,1.402016,1.705215,1.174158,1.314668,1.304482,1.390877,0.937740,1.189734,1.166747,1.039491,1.338345,1.318797,1.246279,1.008821,1.096579,1.290502,1.291552,1.116300,0.934127,0.699045,0.799855,1.262288,1.305268,0.786980,0.815078,0.659787,1.090166,1.005791,0.788615,0.820482,0.720672,0.642997,0.819823,0.606727,0.977684,0.996462,0.994113,1.358178,1.107631,1.342412,1.112935,1.001791,0.793324,0.729418,0.846393,0.666385,1.021310,1.201428,0.675269,0.722364,0.822649,1.007169,0.894328,0.645207,0.741413,0.890634,0.859591,0.873284,0.797961,0.682321,0.617447,0.880369,1.132735,0.998477,0.762079,0.663865,0.797496,0.761322,1.035181,1.105271,1.105854,1.200904,0.901654,0.705217,0.730636,0.634526,0.630184,0.671428,0.843764,0.928958,0.643085,0.747143,0.653039,0.630407,1.387283,1.156058,0.777195,0.932712,1.200305,0.937092,0.706071,0.863963,0.876144,0.669055,0.600816,0.619598,1.156108,0.607266,0.546781,0.547414,0.717371,0.921780,0.821017,0.608551,0.636862,0.702829,0.644581,0.722390,0.902312,0.772317,0.834642,0.907228,0.769188,0.553664,0.766427,0.936490,0.869144,0.661370,0.929846,1.339396,0.744934,0.872638,0.872951,0.942845,0.940338,0.736172,0.898628,0.688677,0.759522,0.614989,0.712737,0.888121,1.049404,0.962066,0.531133,0.787537,0.642891,0.616061,0.709629,0.621685,0.709805,0.792506,0.603657,0.483996,0.726097,1.023303,0.911949,0.583066,0.865951,0.827980,0.771261,1.006063,0.967654,0.536429,0.724166,0.599589,0.607860,0.515664,0.899488,0.490959,0.460386,0.687449,0.714607,0.767319,0.776292,0.902583,0.803289,0.660782,0.638941,0.533964,0.387212,0.426313,0.521470,0.533554,0.856230,1.001040,0.708610,0.789698,0.725970,0.349586,0.635551,0.634731,0.591728,0.627470,0.670400,0.501736,0.431199,0.705309,0.486789,0.436360,0.600727,0.502616,0.448928,0.503795,0.424982,0.402590,0.193896,0.283196,0.139788,0.186212,0.180255,0.289930,0.332926,0.285894

回望日历天数 lookback:  120
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,4.285243,4.437149,2.780349,3.470782,3.376472,2.467182,2.624464,3.996264,3.848740,2.511704,3.184600,2.597717,2.524854,2.450924,2.148172,2.576269,2.530393,2.061757,1.853087,2.019264,1.803081,2.034312,1.781580,1.487422,1.486531,1.572783,1.398059,1.354790,1.523614,1.600859,1.387043,1.640148,1.329221,1.375329,1.425654,1.375924,1.415473,1.721582,1.416114,1.304181,1.365271,1.268207,0.985509,1.365859,1.048267,1.106342,1.424750,1.253375,1.230122,0.942422,0.915273,1.211843,1.290092,0.903384,0.888691,0.787364,0.736116,0.958588,1.065015,0.738930,0.806111,0.686977,1.117518,1.203632,0.902678,1.017253,0.785212,0.829982,0.966893,1.021350,0.848933,0.990661,0.935014,0.999176,0.905206,1.194870,1.111895,1.022199,0.828294,0.791653,0.767292,0.553588,0.926266,0.842853,0.801614,0.996735,0.848518,0.847339,0.684041,0.639091,0.835073,1.253076,1.037847,0.946728,0.736441,0.680011,0.794529,0.874024,0.908864,0.891799,0.668220,0.668790,0.765774,0.544059,0.853744,0.863057,1.010920,1.063926,0.827791,0.650327,0.786626,0.799164,0.984134,0.641271,0.920588,0.782845,0.634789,0.735820,0.678934,0.593578,1.714403,1.873960,1.174229,0.817306,0.982296,1.058666,0.937630,0.828784,0.752474,0.908745,0.766042,0.796864,1.003475,0.524149,0.490990,0.564786,0.576329,0.838485,0.687715,0.546820,0.463416,0.678561,0.680934,0.724461,0.671469,0.622679,0.708654,0.711031,0.668177,0.540710,0.767580,1.027834,0.853451,0.621913,0.879699,1.008139,0.795098,0.825918,0.653992,0.743017,0.858576,0.744530,0.757673,0.551837,0.704877,0.699077,0.719578,0.658426,0.733332,0.604611,0.592790,0.730855,0.718826,0.681999,0.648139,0.553964,0.706093,0.817163,0.487141,0.441443,0.961820,1.289119,0.899429,0.753477,0.843051,0.861090,0.651582,0.627421,0.586888,0.579743,0.725692,0.717588,0.666238,0.550612,0.657070,0.576590,0.482742,0.462951,0.583744,0.670157,0.595293,0.502504,0.628385,0.614775,0.583965,0.657611,0.408658,0.428610,0.508889,0.569758,0.761094,0.800850,0.503328,0.813530,0.777310,0.438295,0.447317,0.418669,0.597408,0.495719,0.453943,0.406718,0.381265,0.505667,0.427455,0.488069,0.426944,0.344247,0.369694,0.429631,0.468709,0.448500,0.194356,0.251336,0.237417,0.190285,0.228143,0.345527,0.497687,0.333528
2026-08-25,4.455583,4.648244,2.774553,3.463547,3.253661,2.462039,2.750071,3.987934,3.840718,2.506468,3.177961,2.561031,2.519591,2.445815,2.252985,2.597562,2.525118,2.036134,1.838112,2.109907,1.892881,2.061957,1.777866,1.484321,1.514139,1.569505,1.393783,1.351966,1.560868,1.625303,1.384151,1.636729,1.326450,1.244344,1.414727,1.373056,1.412523,1.669230,1.413162,1.301462,1.362425,1.278560,1.007644,1.351637,1.020874,1.104036,1.404260,1.237082,1.205749,0.940457,0.916369,1.209317,1.287403,0.901501,0.886838,0.785723,0.734582,0.956590,1.070533,0.745413,0.804431,0.675529,1.115189,1.141999,0.900796,0.977879,0.758803,0.828252,0.943488,0.996461,0.792033,0.977681,0.933065,0.997093,0.903319,1.192380,1.121275,1.020068,0.826567,0.790003,0.765693,0.552434,0.950356,0.906152,0.767804,0.959226,0.877314,0.845573,0.682615,0.637759,0.776873,1.196369,1.023542,0.936139,0.734906,0.678593,0.754001,0.879022,0.967191,0.889940,0.666827,0.667396,0.764178,0.548247,0.851965,0.861258,1.008812,1.061708,0.826066,0.663632,0.784986,0.797498,0.982083,0.639934,0.918669,0.821320,0.633466,0.734286,0.671114,0.568012,1.765542,1.870054,1.133367,0.815602,0.980248,1.056460,0.972095,0.844448,0.750906,0.906851,0.797026,0.795203,0.944430,0.497861,0.487184,0.551516,0.575128,0.836737,0.686281,0.545680,0.439510,0.677146,0.679515,0.716006,0.670070,0.621381,0.707176,0.709549,0.666784,0.539583,0.765980,1.025692,0.851672,0.640667,0.877866,1.006037,0.763741,0.824197,0.673608,0.741469,0.856787,0.742978,0.738559,0.550687,0.703408,0.697620,0.718078,0.657054,0.731803,0.616782,0.591555,0.729332,0.685815,0.680577,0.666981,0.542073,0.687892,0.815460,0.528705,0.453375,0.959815,1.286432,0.897555,0.719513,0.827074,0.859295,0.650224,0.626113,0.611233,0.586275,0.724179,0.691437,0.664849,0.591512,0.675991,0.577738,0.491337,0.496941,0.603865,0.668760,0.594052,0.501457,0.656763,0.644343,0.589748,0.656241,0.407807,0.434756,0.507828,0.559245,0.773192,0.799180,0.502279,0.811834,0.763001,0.421651,0.446385,0.422013,0.609505,0.510133,0.452997,0.392690,0.395801,0.511941,0.445432,0.470041,0.426054,0.343529,0.368924,0.438824,0.455782,0.447565,0.201931,0.252381,0.236922,0.189888,0.219519,0.339608,0.488666,0.322450
2026-08-26,4.574359,4.634921,2.692250,3.453620,3.359776,2.454982,2.742189,3.976504,3.901233,2.506362,3.168852,2.584872,2.589409,2.436022,2.137550,2.632055,2.568282,2.030298,1.832843,2.009279,1.887456,2.083213,1.772771,1.480067,1.587965,1.565006,1.391146,1.324416,1.516080,1.620644,1.380184,1.564834,1.376999,1.368528,1.418605,1.375094,1.408474,1.644052,1.409112,1.297732,1.358520,1.286516,1.004756,1.347763,1.003356,1.072303,1.385491,1.233536,1.202293,0.966506,0.913743,1.205851,1.283713,0.898917,0.917239,0.783471,0.732476,0.953848,1.067465,0.759531,0.802125,0.673592,1.111992,1.138726,0.898214,1.012223,0.756628,0.825878,0.962112,0.942178,0.752995,0.970507,0.930390,1.030498,0.900730,1.188962,1.106397,1.006405,0.824198,0.806193,0.763498,0.550850,0.947632,0.838685,0.733386,0.956477,0.874800,0.843149,0.653331,0.635931,0.774646,1.192940,1.017366,0.904548,0.732799,0.676648,0.751840,0.876503,1.035447,0.887389,0.664916,0.666922,0.761988,0.546676,0.849523,0.877318,1.005921,1.058665,0.823698,0.661730,0.782736,0.815647,1.048375,0.638100,0.916036,0.844586,0.631650,0.725175,0.669190,0.590643,1.760482,1.864694,1.168423,0.824297,1.017369,1.040364,0.969309,0.842027,0.748753,0.889181,0.794741,0.801604,0.981527,0.521557,0.488562,0.549936,0.585125,0.881283,0.684314,0.544116,0.438250,0.707696,0.687124,0.706124,0.659025,0.619600,0.749355,0.766870,0.735129,0.538037,0.763785,1.022752,0.849231,0.638831,0.855347,1.003154,0.761552,0.806431,0.710239,0.775224,0.872879,0.773312,0.753926,0.549108,0.666868,0.675990,0.716020,0.665572,0.729706,0.601621,0.556597,0.719204,0.680787,0.678626,0.665069,0.540520,0.702601,0.813123,0.527189,0.439260,0.931834,1.282745,0.894982,0.717450,0.814903,0.856095,0.622247,0.624318,0.652385,0.584594,0.722104,0.689455,0.662943,0.589816,0.653821,0.573739,0.489928,0.495517,0.602134,0.666843,0.592350,0.484489,0.654880,0.642496,0.581077,0.684853,0.394573,0.426490,0.491507,0.557642,0.773568,0.728489,0.500839,0.809507,0.773466,0.420442,0.445105,0.420803,0.607758,0.503630,0.438786,0.384798,0.379379,0.510473,0.425341,0.462848,0.408099,0.342544,0.367866,0.437566,0.454476,0.446282,0.201352,0.251658,0.231909,0.189560,0.218890,0.338634,0.487265,0.317417
2026-08-27,4.571458,4.412408,2.690542,3.552383,3.357645,2.453425,2.740450,3.842481,3.827280,2.539538,3.187113,2.583233,2.510776,2.395820,2.136194,2.630386,2.633806,2.050261,1.831681,2.008005,1.886259,2.081892,1.771646,1.479128,1.586958,1.564014,1.390264,1.347236,1.555407,1.619616,1.376070,1.563842,1.405752,1.511050,1.417705,1.374222,1.398380,1.643009,1.418242,1.338864,1.446871,1.318783,1.100904,1.349799,1.002719,1.071623,1.384612,1.246386,1.223263,0.937167,0.913163,1.205086,1.272270,0.898347,0.916657,0.782974,0.693574,0.953243,1.073693,0.805092,0.818313,0.683147,1.111287,1.196921,0.897644,0.974457,0.780833,0.833736,0.961502,0.901225,0.752518,0.940668,0.909267,1.029845,0.900159,1.163750,1.082040,1.005767,0.811008,0.787239,0.788810,0.559810,0.972562,0.902981,0.765118,0.899174,0.843786,0.854222,0.680227,0.635527,0.830417,1.246089,1.019961,0.903974,0.707899,0.669394,0.751363,0.875947,0.963807,0.886826,0.664494,0.665061,0.761504,0.546329,0.848984,0.876761,0.996682,1.057993,0.823176,0.662045,0.782239,0.794708,0.978647,0.625854,0.935842,0.860208,0.631250,0.724715,0.661977,0.590269,1.819969,1.989255,1.167682,0.823774,1.016724,1.039704,0.932402,0.824163,0.748213,0.866950,0.794237,0.801096,0.980905,0.521226,0.488252,0.561637,0.584754,0.833810,0.683880,0.573490,0.460832,0.707247,0.686688,0.713501,0.654271,0.611790,0.748880,0.766384,0.734663,0.537695,0.763300,1.046989,0.848692,0.638425,0.854805,1.022690,0.790664,0.805920,0.671251,0.738874,0.872325,0.740378,0.735975,0.544549,0.666445,0.675561,0.692114,0.654755,0.729243,0.601239,0.537944,0.718747,0.680356,0.678196,0.664648,0.540177,0.685486,0.787352,0.547857,0.438981,0.884573,1.281931,0.894414,0.716995,0.814387,0.855552,0.647241,0.667846,0.749943,0.601765,0.721646,0.689018,0.634352,0.547542,0.631658,0.571061,0.480051,0.495202,0.601752,0.666420,0.591974,0.484182,0.669319,0.611347,0.567808,0.653945,0.394322,0.433235,0.506051,0.557288,0.773078,0.700281,0.500522,0.808994,0.760332,0.411453,0.444823,0.437638,0.607372,0.542179,0.429879,0.375033,0.367540,0.533333,0.425071,0.452470,0.407840,0.342327,0.367633,0.437289,0.454188,0.445999,0.201224,0.251498,0.231762,0.189439,0.218751,0.338420,0.486956,0.317216
2026-08-28,4.564757,4.625191,2.686598,3.684112,3.509396,2.449829,2.736433,3.776381,3.749992,2.535816,3.182441,2.579446,2.507096,2.392309,2.133063,2.626530,2.629946,2.113649,1.828996,1.958440,1.883494,2.051732,1.769049,1.476960,1.584632,1.561721,1.401085,1.415228,1.601379,1.635131,1.374053,1.509277,1.374109,1.508835,1.415627,1.372208,1.396331,1.660952,1.445697,1.336901,1.444750,1.316850,1.099290,1.302705,1.001250,1.042086,1.374404,1.283602,1.221470,0.924991,0.911825,1.221233,1.259428,0.897030,0.915314,0.764178,0.665010,0.951846,1.072119,0.848436,0.817114,0.682145,1.110444,1.195166,0.896329,0.973029,0.779689,0.824144,0.938809,0.940201,0.751415,0.939289,0.887247,0.992148,0.898839,1.129945,1.046215,1.015010,0.822468,0.786085,0.800928,0.582058,0.971137,0.957025,0.763997,0.897856,0.872963,0.907619,0.679230,0.644018,0.879375,1.244262,1.030547,0.931496,0.731261,0.675228,0.673346,0.867876,0.962394,0.836838,0.659161,0.664086,0.760388,0.545528,0.847739,0.875476,0.995221,1.056442,0.835197,0.667408,0.781093,0.813935,0.977212,0.636760,0.934470,0.867321,0.644691,0.723652,0.661007,0.614869,1.817301,1.986339,1.127746,0.852432,1.030522,1.051220,0.967274,0.840260,0.747117,0.848662,0.793073,0.799922,0.996417,0.520462,0.487537,0.560814,0.583897,0.832588,0.649905,0.572649,0.460157,0.706210,0.685681,0.719365,0.657642,0.618300,0.747782,0.765261,0.761023,0.536907,0.762181,1.045455,0.847448,0.637490,0.853552,1.022975,0.823911,0.807595,0.670267,0.665211,0.871047,0.724859,0.734896,0.531670,0.629712,0.694161,0.691100,0.653795,0.728174,0.600641,0.537156,0.717694,0.679358,0.677202,0.692688,0.539385,0.684481,0.786197,0.567800,0.451126,0.883276,1.252250,0.874776,0.715944,0.813193,0.831222,0.620941,0.623008,0.748843,0.600883,0.659355,0.688008,0.609378,0.533518,0.609139,0.570224,0.472364,0.459695,0.579638,0.665443,0.570810,0.471823,0.668338,0.613787,0.566975,0.652986,0.393744,0.437608,0.505309,0.534887,0.786109,0.699255,0.491076,0.791671,0.759217,0.419559,0.455617,0.436997,0.593206,0.541384,0.429249,0.377581,0.378583,0.569704,0.443223,0.451807,0.407243,0.334262,0.351965,0.456590,0.453522,0.417370,0.200929,0.251130,0.221582,0.187851,0.211873,0.337923,0.486242,0.316751

回望日历天数 lookback:  360
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,8.537527,7.437814,4.109705,3.671957,3.692861,3.256523,3.308302,3.444110,2.953689,2.407553,2.832766,2.845597,2.437842,2.173879,2.095051,2.086287,1.756758,1.659384,1.747124,1.853372,2.133697,1.813162,1.717189,1.450481,1.576545,1.407314,1.200670,1.357429,1.578417,1.575403,1.662944,1.518112,1.308686,1.396716,1.363247,1.378992,1.273130,1.358983,1.331669,1.291438,1.094419,1.129503,1.023093,1.102746,1.047053,1.161727,1.206693,1.168626,1.223352,1.010177,0.999235,1.141572,1.050888,0.883450,0.976008,0.822066,0.824006,0.868457,0.802581,0.850185,0.902253,0.876557,1.170159,1.057856,0.936281,0.905772,0.824772,0.804827,0.779553,0.755569,0.710668,0.744152,0.850988,0.864628,0.749775,0.809711,0.746919,0.753399,0.664920,0.616843,0.712454,0.636222,0.769235,0.908942,0.750545,0.756565,0.800451,0.784208,0.653770,0.729568,0.852596,0.996360,0.926905,0.913488,0.821133,0.687821,0.669548,0.778893,0.787435,0.781839,0.691254,0.737138,0.805732,0.659466,0.790652,0.824953,1.030590,0.911654,0.856427,0.777034,0.856124,0.911822,0.746745,0.841193,0.885543,0.824423,0.721008,0.758525,0.658094,0.696549,1.488523,1.543273,1.047976,0.963368,0.920742,0.889339,0.782526,0.757890,0.728050,0.725302,0.658195,0.654402,0.717516,0.542986,0.572284,0.593053,0.656747,0.675362,0.663360,0.636792,0.487155,0.608653,0.610216,0.583518,0.598039,0.665507,0.549317,0.512074,0.604526,0.483043,0.582095,0.802902,0.762686,0.657438,0.818324,0.755274,0.661104,0.565972,0.556992,0.570560,0.633790,0.616666,0.641100,0.532136,0.643922,0.717745,0.673209,0.548939,0.667732,0.651623,0.582922,0.633250,0.619383,0.646261,0.601476,0.607044,0.594213,0.709805,0.544657,0.645295,1.007941,1.143435,1.038543,0.952381,0.945680,0.852255,0.831636,0.770401,0.634971,0.653045,0.732396,0.728934,0.728804,0.587257,0.639327,0.625342,0.503970,0.549386,0.591322,0.653447,0.595347,0.561060,0.594669,0.569475,0.552246,0.477815,0.413024,0.409729,0.529240,0.541277,0.739403,1.062214,0.881045,0.821977,0.709122,0.581068,0.634124,0.600734,0.587948,0.625968,0.520381,0.513002,0.488021,0.510822,0.465195,0.530899,0.532609,0.441368,0.430270,0.459577,0.470767,0.483240,0.343820,0.312902,0.267003,0.292341,0.329427,0.392309,0.412530,0.364639
2026-08-25,8.717705,7.336501,4.037530,3.672235,3.670409,3.228649,3.366887,3.461440,2.961533,2.411600,2.832980,2.838832,2.458315,2.174044,2.095210,2.086445,1.730600,1.654212,1.747257,1.861925,2.147125,1.819850,1.726796,1.459305,1.590177,1.407421,1.200761,1.341778,1.591155,1.597149,1.648742,1.512192,1.308785,1.385772,1.342650,1.379097,1.273227,1.348588,1.331770,1.291536,1.098640,1.129589,1.023170,1.102830,1.047133,1.161815,1.211318,1.168715,1.209526,1.002723,0.999310,1.141658,1.050968,0.883517,0.976082,0.833508,0.835417,0.868522,0.808463,0.837300,0.898911,0.874110,1.170248,1.045389,0.936352,0.905841,0.824835,0.804888,0.779612,0.755626,0.710722,0.744208,0.851053,0.864693,0.750530,0.815876,0.746975,0.753456,0.664971,0.614376,0.702797,0.633036,0.769293,0.917571,0.750602,0.753154,0.803353,0.782071,0.652392,0.725166,0.845332,0.995367,0.921352,0.901560,0.821195,0.687873,0.666534,0.782505,0.791851,0.770727,0.681625,0.731013,0.798152,0.659516,0.790712,0.825016,1.035706,0.911723,0.840688,0.777093,0.856189,0.917099,0.758966,0.859704,0.885610,0.837540,0.727276,0.763414,0.658144,0.696601,1.488636,1.534254,1.038301,0.963441,0.920812,0.889407,0.792010,0.773126,0.720478,0.719039,0.658245,0.649437,0.713360,0.543027,0.572327,0.587273,0.650371,0.668290,0.657720,0.628057,0.483942,0.597801,0.610262,0.583562,0.598084,0.679979,0.549359,0.512113,0.594577,0.480074,0.571796,0.802962,0.778304,0.659152,0.810228,0.755331,0.661154,0.576700,0.557034,0.568624,0.632126,0.616713,0.641149,0.533711,0.649282,0.717800,0.665930,0.540832,0.659245,0.651672,0.575242,0.633298,0.605961,0.646310,0.605623,0.607089,0.594258,0.716927,0.548187,0.645344,0.990531,1.138896,1.036490,0.950707,0.945751,0.834082,0.831699,0.780070,0.648142,0.653094,0.732451,0.713081,0.728860,0.592836,0.639375,0.625390,0.504008,0.563227,0.594981,0.671754,0.600673,0.561102,0.601716,0.575028,0.560701,0.473724,0.410373,0.409760,0.543074,0.530946,0.744708,1.070400,0.872212,0.816982,0.709176,0.581112,0.634172,0.600780,0.590190,0.647460,0.516644,0.508691,0.488058,0.529542,0.469241,0.528513,0.532649,0.441401,0.430302,0.459612,0.470038,0.483276,0.344620,0.314614,0.267023,0.292363,0.323944,0.390598,0.412562,0.364666
2026-08-26,8.727083,7.243533,4.041873,3.676185,3.674358,3.232122,3.312112,3.465164,2.990160,2.420190,2.864522,2.841886,2.460960,2.163836,2.061362,2.098501,1.758781,1.661295,1.761435,1.855506,2.149435,1.824835,1.728653,1.468298,1.604397,1.401072,1.220756,1.343222,1.592867,1.598868,1.664859,1.513818,1.318473,1.398324,1.364817,1.401215,1.274597,1.350039,1.333203,1.292925,1.099822,1.130804,1.016572,1.100046,1.028879,1.163065,1.212621,1.169972,1.210827,1.003802,0.988400,1.126635,1.050633,0.884468,0.977132,0.834405,0.836316,0.862649,0.803505,0.851164,0.899878,0.875050,1.171507,1.046514,0.937359,0.918477,0.806080,0.800801,0.794195,0.745592,0.711487,0.745009,0.851968,0.865623,0.750639,0.810644,0.741754,0.743673,0.665686,0.615037,0.703553,0.636955,0.785687,0.918558,0.751409,0.757437,0.811720,0.785111,0.641205,0.725946,0.846241,0.996438,0.909085,0.890292,0.802111,0.678408,0.659365,0.779790,0.792703,0.758423,0.682359,0.737986,0.799010,0.660226,0.791563,0.825903,1.031777,0.899134,0.825228,0.769803,0.849135,0.918085,0.759782,0.860629,0.890711,0.846617,0.728059,0.759398,0.654889,0.697351,1.490237,1.535905,1.039418,0.961376,0.921802,0.897476,0.803671,0.775345,0.721253,0.715526,0.658953,0.650136,0.714128,0.543611,0.572943,0.587905,0.657504,0.676140,0.664124,0.637525,0.487716,0.609354,0.610919,0.582540,0.593513,0.666273,0.556839,0.515076,0.605222,0.480590,0.559231,0.795606,0.779142,0.659861,0.811099,0.756143,0.661866,0.577321,0.560962,0.571217,0.632806,0.618805,0.648030,0.534285,0.649981,0.718572,0.673984,0.549571,0.651238,0.649126,0.564462,0.619904,0.590923,0.642525,0.602169,0.607743,0.599606,0.717698,0.548776,0.639959,0.990496,1.140121,1.032503,0.949443,0.939545,0.815772,0.828862,0.771289,0.658974,0.653797,0.733239,0.702026,0.720272,0.609602,0.640063,0.626063,0.507088,0.572852,0.601776,0.672476,0.596033,0.555182,0.602363,0.575647,0.552882,0.474233,0.405801,0.410201,0.543658,0.531518,0.751993,1.071551,0.873150,0.817860,0.709939,0.581737,0.646171,0.601539,0.590825,0.626689,0.511112,0.505877,0.488583,0.533562,0.465731,0.526786,0.533222,0.441876,0.430765,0.460106,0.470544,0.483796,0.344991,0.313263,0.267310,0.295934,0.324292,0.391019,0.413005,0.365058
2026-08-27,8.560911,7.110622,4.048282,3.707117,3.702975,3.237247,3.317364,3.453544,2.994901,2.435343,2.899525,2.846392,2.464862,2.121074,2.050205,2.101828,1.761570,1.663929,1.764227,1.858448,2.152843,1.824696,1.731394,1.463191,1.594411,1.403294,1.230979,1.361147,1.595393,1.601403,1.653133,1.497484,1.328943,1.413638,1.366981,1.403437,1.263978,1.348899,1.335316,1.294975,1.101566,1.132597,1.025895,1.105767,1.030510,1.145615,1.214544,1.171827,1.212747,1.005393,1.001971,1.128421,1.052299,0.885870,0.978681,0.835728,0.837642,0.864016,0.804779,0.852514,0.901304,0.878958,1.177291,1.048173,0.922159,0.919934,0.827031,0.807032,0.795454,0.746774,0.712615,0.746190,0.853319,0.871234,0.752529,0.804296,0.737642,0.738098,0.662407,0.616012,0.714405,0.637965,0.786933,0.920015,0.752601,0.755159,0.805493,0.786356,0.642222,0.727097,0.854932,0.999089,0.910526,0.891704,0.785159,0.679483,0.668309,0.784589,0.793960,0.772780,0.693148,0.739157,0.807939,0.666636,0.805886,0.833643,1.019008,0.888673,0.822394,0.771024,0.843633,0.914320,0.760987,0.861993,0.892123,0.847959,0.722983,0.751040,0.643235,0.698456,1.492600,1.538340,1.041066,0.966007,0.925130,0.898899,0.804946,0.776574,0.722396,0.716660,0.660893,0.656195,0.719481,0.544473,0.573851,0.588837,0.658546,0.671694,0.673021,0.650099,0.493481,0.610320,0.626504,0.585116,0.589397,0.667329,0.565172,0.515892,0.606182,0.479393,0.560118,0.805101,0.764775,0.660907,0.820565,0.760807,0.662915,0.581506,0.561852,0.570138,0.635526,0.619786,0.649057,0.533593,0.651011,0.730232,0.675053,0.542272,0.646218,0.650156,0.565357,0.620887,0.591860,0.639956,0.602449,0.619205,0.612939,0.718836,0.551789,0.647063,0.992067,1.141929,1.029807,0.947373,0.920859,0.801967,0.830177,0.767020,0.660019,0.654834,0.734402,0.714980,0.721414,0.594415,0.641078,0.627055,0.507892,0.578217,0.602730,0.655237,0.589689,0.556063,0.610948,0.576559,0.553758,0.474985,0.411466,0.427872,0.544520,0.532360,0.753185,1.065124,0.864357,0.819157,0.711065,0.582659,0.635861,0.607471,0.594104,0.627682,0.511923,0.506679,0.489358,0.534408,0.460973,0.515421,0.522421,0.441738,0.431448,0.460836,0.471290,0.484563,0.345538,0.312368,0.267734,0.293142,0.322014,0.390322,0.413660,0.365637
2026-08-28,8.549914,7.245698,4.115668,3.711543,3.744606,3.261248,3.371516,3.449107,2.965606,2.420913,2.895800,2.842736,2.461695,2.118349,2.047571,2.099128,1.759307,1.661792,1.749659,1.864485,2.150684,1.815792,1.729170,1.452586,1.578832,1.395426,1.229398,1.360906,1.612063,1.619019,1.651009,1.495561,1.327236,1.411823,1.365225,1.414915,1.274978,1.350442,1.356733,1.293311,1.100151,1.131142,1.024577,1.104346,1.014966,1.124978,1.212984,1.170322,1.206007,0.999036,1.001697,1.143228,1.050947,0.882869,0.977424,0.834654,0.825201,0.855683,0.795087,0.851418,0.903562,0.887834,1.179263,1.040507,0.920975,0.931760,0.845774,0.801040,0.780684,0.756665,0.716185,0.745231,0.852223,0.865882,0.751562,0.796403,0.736694,0.743896,0.661556,0.617738,0.720029,0.639226,0.785922,0.918833,0.746791,0.739557,0.804458,0.790366,0.653289,0.726163,0.853833,0.996736,0.922619,0.902800,0.784151,0.678610,0.667451,0.783581,0.792940,0.771787,0.692257,0.732018,0.799249,0.665780,0.811824,0.837978,1.032085,0.887531,0.825475,0.778162,0.842549,0.918360,0.760009,0.872447,0.890977,0.846870,0.722054,0.750075,0.642409,0.697559,1.506418,1.536364,1.039729,0.966372,0.928848,0.897744,0.803912,0.783343,0.719250,0.710401,0.659150,0.650330,0.720403,0.543774,0.574309,0.588080,0.651265,0.670831,0.672157,0.649264,0.487862,0.598623,0.611102,0.585736,0.593691,0.680914,0.564446,0.519080,0.605403,0.473387,0.559398,0.804066,0.763793,0.661983,0.819511,0.759830,0.663902,0.580759,0.557800,0.568120,0.634710,0.618990,0.648224,0.532908,0.650175,0.729294,0.666845,0.533182,0.642458,0.649320,0.576033,0.634169,0.606794,0.642717,0.601675,0.607924,0.612152,0.717913,0.561016,0.650677,0.990792,1.140462,1.028484,0.946156,0.919676,0.800937,0.824002,0.759655,0.649033,0.652391,0.709993,0.702236,0.720487,0.588109,0.628058,0.626250,0.504701,0.573023,0.595799,0.654395,0.588932,0.555348,0.616740,0.575819,0.549394,0.468776,0.410937,0.427323,0.530008,0.523681,0.752218,1.052471,0.856044,0.815484,0.710151,0.581911,0.635044,0.601719,0.591001,0.626876,0.517355,0.509390,0.488729,0.533721,0.460380,0.498366,0.516217,0.438787,0.430444,0.460244,0.470684,0.483941,0.344319,0.311519,0.267390,0.288427,0.321600,0.389821,0.415086,0.372116

### 使用混合贡献季节因子

当前代码保留两种直接调整构造：

$$
c^{\mathrm{mix,adj},(L)}_{t,i}
=
\frac{c^{\mathrm{mix}}_{t,i}}
     {\widehat g^{\mathrm{mix},(L)}_{t,i}},
\qquad
r^{\mathrm{adj,mix},(L)}_{t,i}
=
\frac{r_{t,i}}
     {\sqrt{\widehat g^{\mathrm{mix},(L)}_{t,i}}}.
$$

它们分别对应 `variance_adjusted` 和 `return_adjusted`。
因子为零或缺失时，调整结果保留为空。
第一式调整混合贡献；第二式将同一贡献因子的平方根用于收益，
是现有实验构造，不能仅凭它将 $\sqrt{\widehat g^{\mathrm{mix},(L)}}$ 称为已估计的收益标准差周期 $\widehat f$。

若先按标准差周期过滤收益 $r^f_{t,i}=r_{t,i}/\widehat f_{t,i}$，
再计算同 Session 的 BV 求和项，恒有：

$$
b^f_{t,i}
=
\frac{b_{t,i}}{\widehat f_{t,i}\widehat f_{t,i-1}}.
$$

特别地，用上面既有的 $r^{\mathrm{adj,mix},(L)}$ 重算 BV 求和项，
除数会是 $\sqrt{\widehat g^{\mathrm{mix},(L)}_{t,i}
\widehat g^{\mathrm{mix},(L)}_{t,i-1}}$，
通常不同于当前直接除以 $\widehat g^{\mathrm{mix},(L)}_{t,i}$。
因此，调整后的混合贡献与“先调整收益再计算 BV”应作为不同对象解释。

#### Cell 10：混合贡献除以 $\widehat g^{\mathrm{mix},(L)}$；既有收益调整构造除以其平方根。

In [ ]:
log_return_matrix = minute_df.pivot(
    index="trading_date",
    columns="minute_slot",
    values="log_return",
).reindex(index=trading_dates, columns=minute_slots)

variance_adjusted_by_lookback = {}
volatility_seasonality_by_lookback = {}
return_adjusted_by_lookback = {}

for lookback in lookback_windows:
    seasonality_matrix = seasonality_by_lookback[lookback]
    positive_seasonality_matrix = seasonality_matrix.where(
        seasonality_matrix > 0
    )

    variance_adjusted_by_lookback[lookback] = (
        variance_contribution_matrix / positive_seasonality_matrix
    )
    volatility_seasonality_by_lookback[lookback] = np.sqrt(
        seasonality_matrix
    )
    return_adjusted_by_lookback[lookback] = (
        log_return_matrix / np.sqrt(positive_seasonality_matrix)
    )

In [45]:
print(return_adjusted_by_lookback.keys())
for key, value in  return_adjusted_by_lookback.items():
    print("回望日历天数 lookback: ", key)
    print(value.columns)
    display(value.tail())

dict_keys([30, 60, 120, 360])
回望日历天数 lookback:  30
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,-0.001718,0.000505,0.000395,0.001404,-0.000035,-0.001825,-0.001702,-0.001644,-0.000434,-0.001614,0.000459,0.000637,-0.001046,-0.000540,-0.000698,0.000539,-0.000200,0.000134,0.000592,-0.000864,0.001840,-0.000713,-0.001071,-0.001424,-0.000807,-0.000038,0.000165,-0.001374,-0.001002,-0.000547,0.000077,0.000427,0.001413,-0.000400,-0.000768,0.001400,0.000375,0.000663,-0.000577,0.001867,-0.000515,-0.000845,-0.000812,-0.000154,0.000850,-0.000685,0.000555,0.000116,0.000052,-0.000557,0.000881,0.000430,-0.000769,-0.000851,0.001095,0.001151,-0.000973,-0.000890,-0.000871,-0.000323,-0.000163,0.001338,-0.000235,0.001086,-0.001826,0.000170,-0.000165,-0.000385,-0.000241,-0.000177,-0.000314,-0.000690,-0.001376,-0.001501,-0.000387,0.000643,-0.000505,-0.000250,0.000780,0.000000,-0.000178,-0.001478,0.000803,-0.000443,-0.000287,0.000689,-0.001328,0.000204,-0.000224,0.000104,-0.000492,0.000131,-0.000272,-0.000413,0.000355,-0.000322,-0.000764,0.002074,0.000501,-0.000027,-0.000082,-0.000741,0.000332,0.001818,0.000511,0.001397,-0.001103,0.000000,0.001190,-0.000442,-0.001721,-0.001529,-0.002473,0.000608,0.000566,0.001638,-0.002188,0.001116,0.000173,-0.000669,-0.001070,0.000291,-0.001300,-0.001302,-0.000385,0.002910,0.001209,0.000845,0.000134,-0.000664,-0.001312,-0.000154,0.000483,0.000078,-0.000864,-0.000160,-0.000190,-0.000048,-0.000056,-0.000162,-0.000218,-0.000781,0.000143,0.001543,0.000392,-0.001040,0.000030,-0.000541,-0.000375,0.000274,-0.000352,-0.000747,-0.000801,-0.000879,-0.000206,-0.000321,-0.000669,-0.000393,0.000896,0.000000,0.000154,0.000471,-0.000536,-0.000556,-0.001002,-0.000575,-0.000287,-0.000086,-0.001378,0.000235,-0.000438,-0.000375,0.000196,0.000802,0.000796,-0.000126,0.001898,0.000894,-0.001055,-0.001089,0.000278,0.000000,0.001453,-0.000037,0.001195,-0.000087,-0.001603,0.000327,0.002959,0.000727,0.001701,0.000092,-0.001060,0.002149,-0.000939,-0.001475,0.001545,0.001683,0.001631,-0.001237,0.001446,-0.001569,0.000334,0.001208,0.000528,0.000222,-0.000457,-0.001665,-0.000359,0.000825,-0.001507,-0.000502,0.000040,0.000483,0.000000,0.001462,0.001705,0.001642,-0.001830,0.000524,0.000095,0.000850,-0.002396,0.002921,-0.000157,0.001250,0.000634,0.000497,0.001452,0.000190,0.001247,-0.000888,0.002153,-0.000452,-0.000186,0.000974,0.000173,0.000147,-0.000322,-0.000049
2026-08-25,-0.001933,-0.000055,0.001285,0.000306,0.002073,-0.001661,0.000067,-0.001772,-0.001603,0.001097,-0.000786,0.001230,-0.000455,0.000086,-0.000559,-0.001640,-0.001106,0.001336,-0.000708,0.000503,-0.000308,0.003022,-0.000678,0.001690,0.000349,0.000693,0.001815,-0.000096,-0.001483,-0.000681,0.001517,-0.000204,0.003320,0.003920,0.000845,-0.000982,0.000092,-0.001486,0.001262,0.000668,-0.000989,-0.000520,-0.000079,0.001162,0.000226,-0.000132,0.001070,0.001281,0.000992,-0.001981,-0.000161,-0.000096,-0.000935,0.000812,0.000486,-0.002772,-0.001888,0.000146,-0.001035,-0.001181,0.000055,-0.000685,0.000773,0.000171,-0.001510,-0.000572,0.000206,0.002122,-0.000606,-0.000256,0.000351,-0.001216,-0.001709,-0.000699,0.000234,0.000069,-0.000132,0.000378,-0.000757,0.000758,-0.000538,-0.000892,0.000873,-0.000106,-0.000865,0.000825,-0.000972,-0.001259,-0.000037,-0.000279,0.000918,0.000369,0.000547,0.000444,-0.000071,0.000392,-0.000543,-0.000594,0.001022,-0.000054,0.000466,0.000803,0.000848,-0.000969,0.001149,-0.000486,-0.000529,-0.000493,0.000085,0.000281,-0.000767,0.001344,0.002598,-0.000896,0.001318,0.001213,-0.000039,0.000026,0.001756,-0.000501,0.004023,0.002970,-0.000448,0.001029,-0.000659,-0.000567,0.001274,0.002332,-0.000266,0.000547,-0.001764,0.000889,0.000539,0.003682,-0.000453,0.001955,-0.001165,-0.000955,-0.000470,0.001355,0.000861,-0.001987,0.001098,-0.000208,-0.000166,0.000964,-0.001527,0.000693,-0.001394,-0.000537,-0.000196,-0.000313,-0.000643,0.000166,-0.000607,0.001421,-0.000502,0.000619,0.000526,-0.001437,-0.000979,-0.001407,-0.000611,-0.000761,0.000077,0.000897,-0.000707,-0.001054,0.000027,0.000366,-0.000125,0.000082,0.000598,0.000349,0.000577,0.001128,-0.000915,-0.000425,-0.000208,0.000104,0.001915,-0.000537,0.000167,0.002295,-0.000093,-0.000544,0.000395,0.000518,-0.001262,0.000082,-0.000933,-0.000182,0.001108,0.000459,-0.000216,-0.000871,0.001198,0.001086,-0.000509,0.000254,0.000029,-0.000077,0.000326,0.000372,-0.000628,-0.000910,-0.000345,0.000436,-0.000426,-0.000497,0.001413,0.000000,-0.000079,0.001322,0.000387,-0.002767,0.000521,-0.001133,-0.000205,0.000380,0.000706,-0.000132,-0.001027,-0.001148,0.000260,0.000920,-0.000035,0.000270,-0.000737,0.000267,-0.000419,-0.000077,0.001070,0.000050,-0.001259,0.001124,-0.001215,-0.001006,-0.000109,-0.000590
2026-08-26,0.000239,-0.001200,0.001285,0.001494,0.000553,-0.001510,-0.000774,0.000000,-0.001019,0.001281,-0.000302,-0.000504,-0.000231,-0.000034,-0.000081,0.000907,0.001698,-0.000740,0.000346,0.000164,-0.001374,-0.000154,-0.000827,-0.000096,-0.000683,0.000626,-0.000648,-0.001346,-0.001308,-0.001229,-0.000195,-0.000629,-0.002059,0.000867,0.000369,0.000139,-0.000306,0.000251,0.001127,-0.000452,-0.000740,0.001174,0.000341,0.001543,0.000927,0.000080,0.000485,0.000510,-0.000668,0.000329,0.002622,0.000536,0.000433,0.000118,-0.000652,0.000065,0.001019,-0.000891,-0.001076,0.001546,0.001815,0.002763,0.000387,0.002036,0.000090,0.000448,-0.000740,0.001924,0.000195,0.001540,0.002809,0.000028,-0.000931,0.000797,-0.002124,-0.000023,-0.000110,-0.000147,-0.000027,0.001001,-0.000700,-0.000699,0.000479,-0.001056,-0.000650,0.000129,-0.000854,-0.000451,0.001141,-0.000238,-0.001374,0.000610,0.000519,0.000527,0.000382,0.000702,-0.001309,-0.000344,-0.000273,0.000795,0.000290,0.000422,-0.001127,-0.000614,0.001023,-0.000827,-0.000207,-0.000046,0.002022,-0.000435,0.000087,-0.000171,0.000029,-0.001600,0.001513,-0.000407,0.000254,-0.000153,-0.000509,-0.000526,-0.001229,0.000457,-0.001686,0.000463,-0.000680,-0.000732,0.000261,0.000187,0.000266,-0.000363,-0.001724,-0.000595,0.000440,0.000198,0.000861,-0.000821,0.000210,0.000612,-0.000581,-0.001946,-0.002083,0.000234,0.000991,0.000447,0.000116,0.000728,0.000419,0.000426,0.000031,-0.000541,0.000791,0.000645,0.000000,-0.001494,-0.000246,-0.001608,-0.001537,-0.000156,-0.000078,0.000916,0.000394,-0.000143,-0.000395,0.000304,0.000661,0.000331,0.000438,-0.000084,-0.000110,0.000052,-0.000034,-0.000396,0.000036,0.000035,0.000703,0.000694,0.000326,-0.000374,-0.002694,0.000276,0.000165,0.000485,-0.000425,0.000145,0.000309,-0.000515,-0.000366,0.000493,-0.000974,0.000410,0.002119,0.000484,0.000399,-0.000219,0.000341,0.000000,-0.000699,-0.000247,-0.000556,0.000214,-0.000150,0.000387,0.000652,0.000135,-0.000276,-0.000121,0.001679,0.001401,0.000511,0.000177,0.000607,0.000194,-0.001424,-0.000298,-0.000453,-0.000325,-0.001202,0.001229,-0.000409,0.000655,-0.000256,0.000044,-0.000798,0.000891,-0.000155,0.000214,-0.000903,-0.000034,0.000234,0.000311,-0.000558,-0.000192,0.000251,0.000150,-0.000425,0.000181,0.000057,-0.000050,-0.000169,0.001275
2026-08-27,-0.000612,0.001310,-0.000411,0.001421,-0.000865,-0.001334,-0.000603,0.000562,-0.000148,0.001254,-0.000594,-0.000498,-0.002572,0.001218,0.002152,0.000947,-0.000909,0.000831,0.000140,0.002207,-0.000339,0.000794,-0.000747,-0.000258,0.000113,0.001379,-0.001055,0.000255,-0.002313,-0.000671,0.000471,0.000558,0.000518,-0.000394,-0.000783,0.000570,-0.001321,0.001044,0.001564,0.001001,-0.000482,0.001257,0.000666,0.000402,-0.000478,0.000292,-0.000991,-0.000294,-0.000507,-0.000376,0.000764,-0.000610,0.000046,0.000093,-0.000506,-0.000100,0.002084,-0.000047,0.000851,-0.001089,-0.000810,0.000690,0.000612,-0.000066,0.002765,-0.000359,0.001124,-0.000102,0.000885,0.001093,-0.000465,-0.000383,0.000030,0.001626,-0.000317,0.000117,0.000946,-0.000365,0.001616,0.000435,0.001934,0.000129,-0.000756,0.000617,-0.000184,0.001042,-0.000511,-0.001283,0.001415,-0.001627,0.000410,-0.000625,0.000749,-0.000688,0.001588,-0.000957,0.000031,-0.000434,-0.000223,-0.000078,0.000180,-0.000266,0.000888,0.000266,0.001452,-0.000662,0.001165,-0.000225,0.001435,-0.000313,-0.001202,0.000403,-0.000225,0.001666,-0.000362,0.000949,0.000984,0.000417,-0.000960,-0.000246,-0.000792,-0.000027,0.000778,-0.000423,-0.000713,0.000582,0.000674,-0.000869,0.000136,-0.000335,0.000140,-0.001409,0.000463,0.002460,-0.000717,-0.000154,-0.000859,-0.000793,-0.000081,0.000143,0.000763,-0.000224,-0.000675,0.000668,0.001047,0.000355,-0.000117,-0.001671,-0.000422,0.000307,-0.000336,-0.000401,-0.001293,0.000305,0.000562,-0.000993,0.001910,0.000127,0.000000,-0.000338,0.000000,0.001406,0.000371,-0.000196,0.000378,0.001031,0.000000,-0.000191,0.000187,-0.000964,-0.000796,-0.000504,-0.000493,0.000624,-0.000916,-0.000065,-0.000223,0.000548,0.001145,0.000256,0.000289,-0.000530,0.000138,0.001126,0.000150,-0.000083,0.000082,-0.000303,0.000000,-0.001118,0.000000,-0.000762,0.000180,0.000053,0.001068,0.000371,-0.000055,0.000715,-0.000083,0.000103,-0.000062,0.000377,-0.000683,0.000396,0.000388,-0.000122,0.002405,0.001175,0.000077,0.001040,-0.000541,0.000405,-0.000269,0.000901,0.000495,-0.000948,0.000506,0.000100,0.000910,0.000501,0.000805,0.000392,-0.001262,-0.000494,0.001345,0.000186,-0.000436,0.000039,0.000940,-0.000459,0.000147,-0.000334,-0.000256,0.000160,0.000285,-0.000423,-0.000172,0.001933,-0.000487,-0.001419
2026-08-28,0.001437,0.001379,-0.000267,0.000959,-0.000512,0.000123,0.000554,0.000629,0.000026,-0.001447,-0.000284,-0.001082,0.000111,0.000179,0.001628,0.000031,0.000298,-0.000109,0.000253,0.001625,-0.000412,-0.000135,-0.001338,0.000176,0.000351,0.000830,-0.000854,0.001182,-0.000821,-0.000415,-0.000350,-0.000304,0.000144,-0.000708,0.000199,-0.000691,0.000112,0.000060,0.000751,-0.001888,0.000424,-0.000234,-0.000953,-0.000343,0.000469,0.000911,0.000110,-0.000699,-0.000347,0.000849,0.000979,0.000304,0.000158,-0.001246,-0.000208,0.000390,-0.000864,-0.000325,0.000834,-0.000224,-0.000938,0.000061,-0.000500,0.000884,0.000184,-0.000744,-0.001005,-0.000136,-0.000489,0.000423,-0.001311,0.000987,0.000490,-0.000641,0.000072,-0.000813,-0.000396,0.000077,-0.000133,0.000316,0.000723,0.000582,-0.002641,0.000828,0.000522,0.000345,0.001261,-0.000409,0.000724,-0.002438,0.000950,0.000754,-0.001062,0.000583,-0.000680,-0.000031,-0.001032,0.000296,-0.000384,-0.000551,0.000743,0.000411,-0.000441,-0.001006,0.000393,0.001297,0.000398,0.000188,-0.000189,0.000245,-0.000823,0.000175,0.000112,-0.001741,0.000511,0.000153,-0.000085,0.000483,0.000319,0.000215,-0.001974,0.000586,-0.001443,0.000479,0.000652,0.000655,-0.000598,-0.000056,0.000929,-0.001107,-0.000878,0.000062,0.000670,0.000729,-0.000143,0.001248,0.000201,-0.000239,0.000346,-0.000386,-0.001253,-0.000155,-0.000124,-0.000750,-0.000161,0.000211,0.000893,-0.000295,0.000117,0.000678,-0.001233,-0.000059,-0.000367,0.000471,-0.001355,0.000543,-0.000642,-0.001289,0.000479,0.000864,0.000312,0.000665,-0.000148,0.000909,-0.000100,-0.000289,0.000000,0.000679,-0.000300,0.000479,0.000181,0.000854,-0.000108,-0.000344,0.000173,-0.000913,-0.001124,0.000030,-0.000646,0.000250,-0.000709,0.000413,0.000057,0.000370,0.000255,0.000364,-0.000387,-0.000259,-0.000250,0.001426,0.000523,-0.000320,0.000388,-0.000029,0.000240,-0.001272,-0.000217,-0.000464,0.000356,0.000409,-0.000401,0.000501,-0.000076,-0.000394,-0.000185,0.000166,0.000175,0.000447,0.000458,0.000074,0.000385,-0.000556,0.001191,-0.000257,-0.000659,-0.000045,-0.000078,0.000324,0.000364,-0.000267,-0.001355,-0.000356,0.000286,-0.000742,0.000376,0.000373,-0.000122,-0.000191,0.000188,0.000406,-0.000292,-0.000410,-0.001895,-0.000369,-0.000147,0.000918,-0.000204,0.000928,-0.000041,0.000474

回望日历天数 lookback:  60
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,-0.001577,0.000418,0.000398,0.001406,-0.000032,-0.002076,-0.001817,-0.001571,-0.000436,-0.001425,0.000408,0.000651,-0.001239,-0.000540,-0.000728,0.000535,-0.000194,0.000119,0.000588,-0.000851,0.001732,-0.000648,-0.001233,-0.001414,-0.000673,-0.000042,0.000178,-0.001362,-0.000814,-0.000506,0.000075,0.000395,0.000991,-0.000353,-0.000621,0.001411,0.000365,0.000708,-0.000586,0.001794,-0.000524,-0.000867,-0.000848,-0.000139,0.000845,-0.000661,0.000594,0.000118,0.000049,-0.000538,0.000857,0.000452,-0.000908,-0.000890,0.001175,0.001098,-0.000843,-0.000868,-0.000781,-0.000336,-0.000180,0.001681,-0.000233,0.000764,-0.001827,0.000180,-0.000159,-0.000321,-0.000232,-0.000174,-0.000251,-0.000632,-0.001169,-0.001348,-0.000372,0.000648,-0.000695,-0.000272,0.000797,0.000000,-0.000173,-0.001322,0.000781,-0.000561,-0.000275,0.000657,-0.001258,0.000142,-0.000210,0.000100,-0.000537,0.000139,-0.000276,-0.000401,0.000305,-0.000330,-0.000780,0.002071,0.000521,-0.000027,-0.000086,-0.000772,0.000329,0.002285,0.000521,0.001388,-0.001068,0.000000,0.001311,-0.000634,-0.001937,-0.001365,-0.001921,0.000649,0.000535,0.001458,-0.001899,0.001320,0.000202,-0.000707,-0.000924,0.000237,-0.001183,-0.001293,-0.000383,0.002891,0.001027,0.000870,0.000153,-0.000727,-0.001226,-0.000162,0.000506,0.000070,-0.000817,-0.000179,-0.000257,-0.000057,-0.000061,-0.000138,-0.000195,-0.000910,0.000170,0.001704,0.000415,-0.000972,0.000030,-0.000555,-0.000366,0.000273,-0.000301,-0.000677,-0.000732,-0.000862,-0.000226,-0.000259,-0.000697,-0.000427,0.000996,0.000000,0.000137,0.000395,-0.000461,-0.000576,-0.001206,-0.000605,-0.000292,-0.000089,-0.001472,0.000252,-0.000553,-0.000432,0.000190,0.000780,0.000617,-0.000142,0.001886,0.000891,-0.001159,-0.001307,0.000270,0.000000,0.001519,-0.000029,0.001042,-0.000080,-0.001866,0.000335,0.002371,0.000611,0.001410,0.000099,-0.001107,0.002571,-0.001092,-0.001635,0.001867,0.001745,0.001706,-0.001645,0.001517,-0.001718,0.000408,0.001413,0.000550,0.000221,-0.000433,-0.001415,-0.000334,0.000820,-0.001638,-0.000496,0.000031,0.000488,0.000000,0.001389,0.001528,0.001518,-0.001903,0.000507,0.000097,0.000772,-0.002489,0.002369,-0.000156,0.001272,0.000666,0.000646,0.001732,0.000189,0.001301,-0.000933,0.002053,-0.000457,-0.000165,0.000999,0.000185,0.000153,-0.000394,-0.000052
2026-08-25,-0.001820,-0.000042,0.001254,0.000309,0.001947,-0.001758,0.000069,-0.001755,-0.001606,0.000971,-0.000761,0.001274,-0.000560,0.000088,-0.000580,-0.001624,-0.001076,0.001233,-0.000701,0.000495,-0.000299,0.002886,-0.000704,0.001674,0.000318,0.000755,0.001951,-0.000097,-0.001250,-0.000663,0.001371,-0.000190,0.002510,0.003555,0.000700,-0.000987,0.000091,-0.001534,0.001277,0.000680,-0.001004,-0.000532,-0.000082,0.001041,0.000224,-0.000127,0.001151,0.001326,0.000896,-0.001773,-0.000155,-0.000096,-0.001022,0.000870,0.000531,-0.002695,-0.001666,0.000145,-0.000904,-0.001224,0.000061,-0.000803,0.000766,0.000125,-0.001623,-0.000603,0.000197,0.001855,-0.000600,-0.000247,0.000280,-0.001110,-0.001495,-0.000631,0.000233,0.000070,-0.000181,0.000419,-0.000771,0.000766,-0.000521,-0.000796,0.000839,-0.000130,-0.000867,0.000784,-0.000938,-0.000978,-0.000030,-0.000272,0.000965,0.000367,0.000574,0.000438,-0.000065,0.000402,-0.000590,-0.000610,0.001153,-0.000054,0.000490,0.000885,0.000853,-0.001225,0.001195,-0.000482,-0.000510,-0.000503,0.000088,0.000402,-0.000860,0.001196,0.001930,-0.000928,0.001239,0.001096,-0.000033,0.000032,0.002046,-0.000528,0.003483,0.002577,-0.000430,0.001019,-0.000653,-0.000605,0.001149,0.002576,-0.000318,0.000597,-0.001644,0.000898,0.000548,0.003295,-0.000365,0.002177,-0.001576,-0.001116,-0.000513,0.001166,0.000737,-0.002169,0.001166,-0.000221,-0.000172,0.000955,-0.001493,0.000709,-0.001373,-0.000524,-0.000172,-0.000285,-0.000626,0.000160,-0.000638,0.001145,-0.000520,0.000670,0.000575,-0.001531,-0.000858,-0.001076,-0.000454,-0.000708,0.000090,0.000978,-0.000701,-0.001048,0.000026,0.000380,-0.000148,0.000095,0.000574,0.000336,0.000439,0.001180,-0.000893,-0.000423,-0.000218,0.000121,0.001794,-0.000547,0.000169,0.001748,-0.000083,-0.000498,0.000420,0.000535,-0.001135,0.000071,-0.000771,-0.000205,0.001178,0.000613,-0.000244,-0.000996,0.001543,0.001099,-0.000531,0.000322,0.000030,-0.000083,0.000401,0.000443,-0.000670,-0.000927,-0.000302,0.000370,-0.000402,-0.000500,0.001624,0.000000,-0.000062,0.001311,0.000401,-0.002580,0.000466,-0.001045,-0.000209,0.000367,0.000720,-0.000113,-0.001086,-0.000894,0.000258,0.000959,-0.000035,0.000302,-0.000805,0.000264,-0.000458,-0.000080,0.001018,0.000050,-0.001097,0.001118,-0.001200,-0.001010,-0.000139,-0.000644
2026-08-26,0.000233,-0.000893,0.001266,0.001557,0.000496,-0.001608,-0.000824,0.000000,-0.001022,0.001135,-0.000293,-0.000522,-0.000284,-0.000035,-0.000086,0.000898,0.001764,-0.000683,0.000343,0.000161,-0.001337,-0.000144,-0.000833,-0.000091,-0.000652,0.000682,-0.000687,-0.001394,-0.001103,-0.001157,-0.000174,-0.000593,-0.001691,0.000790,0.000311,0.000141,-0.000297,0.000249,0.001147,-0.000461,-0.000788,0.001229,0.000363,0.001393,0.000892,0.000077,0.000506,0.000517,-0.000602,0.000290,0.002438,0.000523,0.000406,0.000125,-0.000687,0.000063,0.000868,-0.000885,-0.000963,0.001603,0.001936,0.002864,0.000384,0.001480,0.000090,0.000471,-0.000707,0.001695,0.000206,0.001428,0.002408,0.000026,-0.000859,0.000729,-0.002182,-0.000023,-0.000151,-0.000163,-0.000029,0.001058,-0.000693,-0.000647,0.000460,-0.001189,-0.000583,0.000123,-0.000825,-0.000307,0.000952,-0.000236,-0.001444,0.000607,0.000546,0.000513,0.000350,0.000721,-0.001423,-0.000353,-0.000301,0.000795,0.000282,0.000449,-0.001133,-0.000736,0.001048,-0.000865,-0.000202,-0.000048,0.002088,-0.000623,0.000093,-0.000160,0.000028,-0.001658,0.001397,-0.000368,0.000199,-0.000189,-0.000593,-0.000540,-0.001064,0.000397,-0.001605,0.000450,-0.000661,-0.000766,0.000223,0.000201,0.000317,-0.000411,-0.001607,-0.000673,0.000448,0.000172,0.000694,-0.000915,0.000284,0.000697,-0.000634,-0.001819,-0.001855,0.000247,0.001165,0.000475,0.000115,0.000679,0.000407,0.000436,0.000031,-0.000559,0.000703,0.000586,0.000000,-0.001461,-0.000250,-0.001214,-0.001552,-0.000168,-0.000082,0.000995,0.000360,-0.000119,-0.000336,0.000283,0.000776,0.000370,0.000444,-0.000085,-0.000105,0.000055,-0.000037,-0.000416,0.000033,0.000034,0.000507,0.000726,0.000318,-0.000361,-0.002830,0.000330,0.000150,0.000490,-0.000421,0.000121,0.000283,-0.000495,-0.000390,0.000508,-0.000955,0.000353,0.001571,0.000545,0.000438,-0.000298,0.000379,0.000000,-0.000893,-0.000257,-0.000588,0.000264,-0.000152,0.000415,0.000803,0.000165,-0.000295,-0.000128,0.001561,0.001233,0.000481,0.000179,0.000706,0.000205,-0.001142,-0.000271,-0.000494,-0.000317,-0.001075,0.001196,-0.000417,0.000645,-0.000268,0.000039,-0.000856,0.000694,-0.000153,0.000230,-0.000828,-0.000038,0.000256,0.000302,-0.000610,-0.000211,0.000239,0.000151,-0.000415,0.000185,0.000063,-0.000050,-0.000186,0.001392
2026-08-27,-0.000614,0.001085,-0.000415,0.001526,-0.000812,-0.001428,-0.000646,0.000577,-0.000153,0.001138,-0.000594,-0.000519,-0.002938,0.001179,0.002212,0.000939,-0.000906,0.000809,0.000139,0.002180,-0.000331,0.000726,-0.000768,-0.000236,0.000101,0.001466,-0.001108,0.000259,-0.002155,-0.000711,0.000422,0.000534,0.000415,-0.000361,-0.000700,0.000586,-0.001180,0.001055,0.001680,0.001025,-0.000511,0.001282,0.000711,0.000365,-0.000463,0.000282,-0.001008,-0.000301,-0.000475,-0.000344,0.000725,-0.000607,0.000045,0.000100,-0.000522,-0.000095,0.001751,-0.000047,0.000766,-0.001135,-0.000852,0.000719,0.000609,-0.000051,0.002773,-0.000380,0.001059,-0.000092,0.000992,0.001063,-0.000380,-0.000344,0.000026,0.001465,-0.000326,0.000114,0.001199,-0.000378,0.001864,0.000469,0.001970,0.000128,-0.000753,0.000686,-0.000185,0.000996,-0.000481,-0.000906,0.001329,-0.001620,0.000427,-0.000625,0.000793,-0.000674,0.001379,-0.000960,0.000033,-0.000448,-0.000247,-0.000079,0.000175,-0.000285,0.000925,0.000313,0.001495,-0.000673,0.001146,-0.000239,0.001501,-0.000451,-0.001374,0.000395,-0.000235,0.001708,-0.000342,0.000844,0.000760,0.000495,-0.001067,-0.000265,-0.000689,-0.000023,0.000769,-0.000413,-0.000694,0.000596,0.000561,-0.000874,0.000155,-0.000372,0.000131,-0.001600,0.000464,0.002018,-0.000562,-0.000172,-0.001145,-0.000876,-0.000087,0.000135,0.000720,-0.000241,-0.000749,0.000710,0.001043,0.000332,-0.000114,-0.001694,-0.000419,0.000308,-0.000280,-0.000366,-0.001184,0.000291,0.000573,-0.000760,0.001980,0.000137,0.000000,-0.000368,0.000000,0.001132,0.000277,-0.000177,0.000438,0.001131,0.000000,-0.000195,0.000179,-0.001016,-0.000892,-0.000533,-0.000450,0.000600,-0.000655,-0.000067,-0.000218,0.000531,0.001186,0.000314,0.000273,-0.000534,0.000137,0.001020,0.000138,-0.000081,0.000089,-0.000314,0.000000,-0.000967,0.000000,-0.000867,0.000202,0.000073,0.001195,0.000412,-0.000074,0.000722,-0.000086,0.000120,-0.000059,0.000405,-0.000819,0.000484,0.000426,-0.000133,0.002230,0.001001,0.000071,0.000982,-0.000633,0.000401,-0.000212,0.000796,0.000552,-0.000931,0.000438,0.000098,0.000973,0.000494,0.000815,0.000339,-0.001230,-0.000373,0.001308,0.000193,-0.000370,0.000037,0.001032,-0.000440,0.000148,-0.000370,-0.000237,0.000147,0.000269,-0.000421,-0.000184,0.001838,-0.000451,-0.001450
2026-08-28,0.001360,0.001078,-0.000265,0.001021,-0.000468,0.000124,0.000578,0.000639,0.000027,-0.001389,-0.000284,-0.001108,0.000133,0.000185,0.001671,0.000031,0.000313,-0.000115,0.000251,0.001646,-0.000392,-0.000124,-0.001373,0.000169,0.000326,0.000835,-0.000896,0.001256,-0.000804,-0.000439,-0.000313,-0.000298,0.000127,-0.000648,0.000183,-0.000730,0.000109,0.000059,0.000788,-0.001875,0.000477,-0.000242,-0.001018,-0.000309,0.000456,0.000890,0.000112,-0.000722,-0.000325,0.000775,0.000940,0.000319,0.000159,-0.001275,-0.000215,0.000372,-0.000725,-0.000323,0.000749,-0.000234,-0.001034,0.000064,-0.000497,0.000673,0.000175,-0.000831,-0.001071,-0.000130,-0.000517,0.000434,-0.001078,0.000886,0.000417,-0.000558,0.000074,-0.000741,-0.000419,0.000078,-0.000146,0.000335,0.000735,0.000573,-0.002628,0.000975,0.000539,0.000337,0.001176,-0.000285,0.000687,-0.002396,0.001028,0.000771,-0.001122,0.000585,-0.000553,-0.000031,-0.001126,0.000305,-0.000391,-0.000548,0.000746,0.000447,-0.000467,-0.001135,0.000436,0.001387,0.000396,0.000190,-0.000192,0.000341,-0.000882,0.000196,0.000131,-0.001811,0.000482,0.000135,-0.000065,0.000542,0.000354,0.000229,-0.001770,0.000534,-0.001391,0.000459,0.000619,0.000727,-0.000527,-0.000056,0.001085,-0.001178,-0.000807,0.000066,0.000703,0.000635,-0.000106,0.001372,0.000246,-0.000271,0.000345,-0.000334,-0.001076,-0.000155,-0.000130,-0.000797,-0.000165,0.000208,0.000827,-0.000301,0.000119,0.000700,-0.001041,-0.000054,-0.000336,0.000449,-0.001379,0.000473,-0.000665,-0.001426,0.000531,0.000968,0.000296,0.000517,-0.000110,0.000880,-0.000120,-0.000299,0.000000,0.000691,-0.000280,0.000505,0.000214,0.000851,-0.000097,-0.000332,0.000124,-0.000892,-0.001052,0.000029,-0.000671,0.000300,-0.000673,0.000387,0.000055,0.000342,0.000224,0.000344,-0.000386,-0.000260,-0.000239,0.001175,0.000398,-0.000370,0.000401,-0.000036,0.000275,-0.001525,-0.000307,-0.000472,0.000401,0.000476,-0.000385,0.000549,-0.000087,-0.000481,-0.000196,0.000178,0.000168,0.000399,0.000433,0.000071,0.000450,-0.000573,0.000959,-0.000234,-0.000734,-0.000044,-0.000065,0.000294,0.000373,-0.000263,-0.001337,-0.000331,0.000278,-0.000559,0.000374,0.000395,-0.000101,-0.000147,0.000195,0.000404,-0.000280,-0.000370,-0.001719,-0.000294,-0.000140,0.000908,-0.000184,0.000872,-0.000045,0.000488

回望日历天数 lookback:  120
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,-0.001425,0.000354,0.000367,0.001326,-0.000029,-0.001708,-0.001710,-0.001456,-0.000436,-0.001336,0.000376,0.000632,-0.001130,-0.000531,-0.000770,0.000552,-0.000203,0.000131,0.000572,-0.000794,0.001619,-0.000564,-0.001066,-0.001301,-0.000707,-0.000043,0.000182,-0.001343,-0.000787,-0.000470,0.000069,0.000401,0.000983,-0.000276,-0.000565,0.001380,0.000362,0.000718,-0.000520,0.001743,-0.000506,-0.000860,-0.000841,-0.000138,0.000894,-0.000666,0.000587,0.000120,0.000049,-0.000555,0.000929,0.000464,-0.000948,-0.000964,0.001171,0.001031,-0.000847,-0.000990,-0.000862,-0.000345,-0.000180,0.001659,-0.000229,0.000786,-0.001702,0.000160,-0.000152,-0.000326,-0.000219,-0.000133,-0.000264,-0.000651,-0.001202,-0.001516,-0.000399,0.000694,-0.000693,-0.000268,0.000833,0.000000,-0.000185,-0.001457,0.000817,-0.000620,-0.000272,0.000570,-0.001177,0.000147,-0.000230,0.000102,-0.000505,0.000121,-0.000266,-0.000391,0.000316,-0.000329,-0.000731,0.002061,0.000569,-0.000029,-0.000099,-0.000829,0.000341,0.002277,0.000556,0.001513,-0.001129,0.000000,0.001367,-0.000637,-0.001860,-0.001212,-0.001723,0.000644,0.000509,0.001501,-0.001905,0.001296,0.000197,-0.000703,-0.000829,0.000198,-0.000952,-0.001353,-0.000412,0.002614,0.000840,0.000863,0.000187,-0.000682,-0.001115,-0.000152,0.000542,0.000075,-0.000852,-0.000181,-0.000286,-0.000059,-0.000065,-0.000147,-0.000239,-0.000923,0.000165,0.001690,0.000463,-0.001066,0.000032,-0.000644,-0.000399,0.000295,-0.000341,-0.000724,-0.000736,-0.000897,-0.000232,-0.000271,-0.000642,-0.000450,0.001179,0.000000,0.000147,0.000410,-0.000501,-0.000733,-0.001234,-0.000522,-0.000290,-0.000101,-0.001755,0.000316,-0.000533,-0.000448,0.000194,0.000761,0.000645,-0.000147,0.001884,0.000875,-0.001172,-0.001273,0.000251,0.000000,0.001524,-0.000031,0.001128,-0.000088,-0.002060,0.000413,0.002915,0.000607,0.001436,0.000096,-0.001132,0.002416,-0.001273,-0.001503,0.001838,0.002074,0.002022,-0.001754,0.001721,-0.002294,0.000445,0.001521,0.000602,0.000234,-0.000423,-0.001407,-0.000342,0.000826,-0.001678,-0.000576,0.000038,0.000511,0.000000,0.001270,0.001701,0.001798,-0.001856,0.000577,0.000121,0.000891,-0.002675,0.002589,-0.000166,0.001355,0.000744,0.000737,0.001909,0.000206,0.001417,-0.000926,0.002078,-0.000484,-0.000166,0.000988,0.000169,0.000137,-0.000344,-0.000047
2026-08-25,-0.001646,-0.000038,0.001158,0.000292,0.001697,-0.001450,0.000065,-0.001631,-0.001612,0.000913,-0.000703,0.001226,-0.000532,0.000087,-0.000617,-0.001677,-0.001119,0.001285,-0.000686,0.000452,-0.000278,0.002567,-0.000675,0.001544,0.000332,0.000782,0.002001,-0.000093,-0.001195,-0.000618,0.001247,-0.000191,0.002496,0.002981,0.000612,-0.000967,0.000091,-0.001548,0.001137,0.000663,-0.000972,-0.000526,-0.000081,0.001046,0.000241,-0.000129,0.001139,0.001333,0.000907,-0.001833,-0.000169,-0.000098,-0.001070,0.000966,0.000544,-0.002557,-0.001735,0.000166,-0.001020,-0.001255,0.000060,-0.000792,0.000745,0.000127,-0.001543,-0.000549,0.000187,0.001759,-0.000558,-0.000190,0.000305,-0.001153,-0.001547,-0.000736,0.000258,0.000075,-0.000180,0.000404,-0.000808,0.000735,-0.000560,-0.000879,0.000893,-0.000143,-0.000839,0.000695,-0.000872,-0.000889,-0.000033,-0.000273,0.000928,0.000324,0.000538,0.000422,-0.000063,0.000396,-0.000533,-0.000610,0.001245,-0.000058,0.000566,0.000898,0.000870,-0.001247,0.001294,-0.000526,-0.000541,-0.000554,0.000090,0.000400,-0.000828,0.001065,0.001835,-0.000949,0.001160,0.001136,-0.000034,0.000032,0.002014,-0.000538,0.003082,0.002022,-0.000353,0.001069,-0.000704,-0.000548,0.000925,0.002535,-0.000370,0.000562,-0.001469,0.000840,0.000605,0.003520,-0.000382,0.002225,-0.001757,-0.001138,-0.000548,0.001229,0.000885,-0.002206,0.001134,-0.000221,-0.000196,0.001050,-0.001619,0.000824,-0.001472,-0.000546,-0.000183,-0.000291,-0.000638,0.000167,-0.000657,0.001201,-0.000490,0.000707,0.000684,-0.001771,-0.000897,-0.001120,-0.000499,-0.000904,0.000096,0.000868,-0.000697,-0.001193,0.000031,0.000479,-0.000140,0.000094,0.000584,0.000325,0.000460,0.001238,-0.000905,-0.000416,-0.000221,0.000120,0.001670,-0.000496,0.000170,0.001894,-0.000088,-0.000549,0.000465,0.000676,-0.001369,0.000070,-0.000787,-0.000193,0.001183,0.000557,-0.000293,-0.000916,0.001566,0.001290,-0.000619,0.000360,0.000035,-0.000113,0.000429,0.000466,-0.000731,-0.000958,-0.000293,0.000365,-0.000413,-0.000501,0.001673,0.000000,-0.000075,0.001334,0.000397,-0.002345,0.000520,-0.001235,-0.000206,0.000412,0.000874,-0.000128,-0.001148,-0.001010,0.000281,0.001015,-0.000041,0.000365,-0.000969,0.000283,-0.000476,-0.000080,0.001012,0.000053,-0.000989,0.001105,-0.001085,-0.000919,-0.000115,-0.000566
2026-08-26,0.000213,-0.000797,0.001176,0.001424,0.000451,-0.001415,-0.000759,0.000000,-0.001018,0.001067,-0.000271,-0.000500,-0.000267,-0.000034,-0.000092,0.000925,0.001819,-0.000713,0.000336,0.000151,-0.001246,-0.000130,-0.000825,-0.000088,-0.000681,0.000707,-0.000728,-0.001330,-0.001070,-0.001121,-0.000161,-0.000603,-0.001702,0.000646,0.000272,0.000138,-0.000296,0.000253,0.001022,-0.000450,-0.000764,0.001237,0.000350,0.001391,0.000966,0.000078,0.000502,0.000532,-0.000612,0.000300,0.002665,0.000536,0.000425,0.000141,-0.000699,0.000060,0.000938,-0.001014,-0.001063,0.001629,0.001911,0.002829,0.000379,0.001447,0.000084,0.000423,-0.000673,0.001609,0.000190,0.001121,0.002505,0.000027,-0.000906,0.000835,-0.002346,-0.000024,-0.000151,-0.000159,-0.000029,0.001005,-0.000729,-0.000715,0.000491,-0.001363,-0.000559,0.000109,-0.000768,-0.000319,0.001053,-0.000233,-0.001391,0.000536,0.000501,0.000503,0.000342,0.000711,-0.001287,-0.000341,-0.000314,0.000847,0.000326,0.000456,-0.001157,-0.000792,0.001154,-0.000937,-0.000212,-0.000052,0.002138,-0.000621,0.000090,-0.000147,0.000026,-0.001698,0.001334,-0.000376,0.000201,-0.000187,-0.000585,-0.000554,-0.000943,0.000312,-0.001306,0.000470,-0.000714,-0.000706,0.000190,0.000204,0.000370,-0.000368,-0.001437,-0.000627,0.000486,0.000185,0.000726,-0.000936,0.000314,0.000711,-0.000678,-0.001920,-0.002345,0.000255,0.001130,0.000478,0.000132,0.000747,0.000432,0.000488,0.000031,-0.000583,0.000703,0.000581,0.000000,-0.001503,-0.000260,-0.001362,-0.001504,-0.000179,-0.000095,0.001126,0.000372,-0.000122,-0.000370,0.000361,0.000852,0.000325,0.000442,-0.000098,-0.000125,0.000069,-0.000036,-0.000410,0.000032,0.000032,0.000525,0.000763,0.000319,-0.000356,-0.002874,0.000323,0.000139,0.000449,-0.000424,0.000126,0.000296,-0.000521,-0.000441,0.000644,-0.001127,0.000350,0.001606,0.000515,0.000427,-0.000278,0.000463,0.000000,-0.000955,-0.000304,-0.000689,0.000295,-0.000174,0.000576,0.000859,0.000167,-0.000316,-0.000129,0.001531,0.001185,0.000495,0.000179,0.000728,0.000250,-0.001356,-0.000267,-0.000486,-0.000288,-0.001201,0.001441,-0.000411,0.000715,-0.000322,0.000043,-0.000910,0.000785,-0.000164,0.000235,-0.001003,-0.000046,0.000308,0.000323,-0.000634,-0.000200,0.000238,0.000160,-0.000333,0.000184,0.000057,-0.000046,-0.000153,0.001232
2026-08-27,-0.000548,0.000938,-0.000389,0.001425,-0.000740,-0.001257,-0.000596,0.000530,-0.000150,0.001119,-0.000566,-0.000497,-0.002798,0.001158,0.002227,0.000968,-0.000967,0.000892,0.000138,0.002043,-0.000309,0.000643,-0.000737,-0.000218,0.000105,0.001568,-0.001191,0.000251,-0.002064,-0.000689,0.000385,0.000531,0.000426,-0.000281,-0.000580,0.000567,-0.001169,0.001058,0.001493,0.000985,-0.000485,0.001315,0.000656,0.000364,-0.000502,0.000281,-0.000989,-0.000308,-0.000479,-0.000356,0.000804,-0.000628,0.000047,0.000112,-0.000526,-0.000090,0.001877,-0.000054,0.000843,-0.001121,-0.000849,0.000705,0.000603,-0.000048,0.002595,-0.000348,0.001016,-0.000087,0.000915,0.000861,-0.000425,-0.000353,0.000028,0.001713,-0.000361,0.000122,0.001214,-0.000367,0.001751,0.000444,0.002037,0.000140,-0.000771,0.000772,-0.000180,0.000911,-0.000456,-0.000936,0.001461,-0.001610,0.000403,-0.000540,0.000727,-0.000662,0.001370,-0.000961,0.000030,-0.000448,-0.000267,-0.000084,0.000193,-0.000289,0.000961,0.000355,0.001648,-0.000755,0.001206,-0.000254,0.001527,-0.000449,-0.001212,0.000352,-0.000211,0.001718,-0.000324,0.000873,0.000755,0.000490,-0.001058,-0.000272,-0.000601,-0.000019,0.000629,-0.000432,-0.000753,0.000565,0.000488,-0.000893,0.000182,-0.000337,0.000117,-0.001492,0.000503,0.002175,-0.000562,-0.000175,-0.001267,-0.000918,-0.000095,0.000138,0.000888,-0.000249,-0.000728,0.000714,0.001198,0.000368,-0.000121,-0.001855,-0.000428,0.000322,-0.000300,-0.000359,-0.001197,0.000296,0.000596,-0.000857,0.001919,0.000146,0.000000,-0.000427,0.000000,0.001127,0.000305,-0.000213,0.000481,0.001019,0.000000,-0.000226,0.000215,-0.001283,-0.000857,-0.000526,-0.000445,0.000573,-0.000676,-0.000071,-0.000222,0.000532,0.001204,0.000316,0.000251,-0.000486,0.000139,0.000990,0.000145,-0.000085,0.000098,-0.000384,0.000000,-0.000946,0.000000,-0.000821,0.000198,0.000071,0.001484,0.000381,-0.000076,0.000855,-0.000101,0.000128,-0.000068,0.000564,-0.000896,0.000502,0.000451,-0.000129,0.002206,0.000992,0.000073,0.000979,-0.000653,0.000499,-0.000258,0.000812,0.000538,-0.000853,0.000508,0.000118,0.000970,0.000530,0.000992,0.000382,-0.001331,-0.000428,0.001397,0.000193,-0.000448,0.000044,0.001244,-0.000472,0.000154,-0.000351,-0.000232,0.000156,0.000216,-0.000418,-0.000167,0.001699,-0.000373,-0.001339
2026-08-28,0.001217,0.000965,-0.000253,0.000945,-0.000428,0.000116,0.000548,0.000599,0.000027,-0.001300,-0.000276,-0.001082,0.000131,0.000185,0.001685,0.000032,0.000335,-0.000125,0.000249,0.001606,-0.000376,-0.000108,-0.001321,0.000149,0.000329,0.000868,-0.000960,0.001216,-0.000776,-0.000424,-0.000287,-0.000295,0.000132,-0.000506,0.000152,-0.000707,0.000110,0.000060,0.000710,-0.001859,0.000453,-0.000248,-0.000940,-0.000296,0.000493,0.000889,0.000111,-0.000732,-0.000329,0.000809,0.001031,0.000328,0.000161,-0.001422,-0.000217,0.000356,-0.000795,-0.000372,0.000827,-0.000225,-0.001033,0.000063,-0.000493,0.000617,0.000164,-0.000763,-0.001030,-0.000115,-0.000483,0.000349,-0.001230,0.000912,0.000442,-0.000652,0.000082,-0.000808,-0.000433,0.000078,-0.000144,0.000323,0.000756,0.000614,-0.002695,0.001092,0.000506,0.000302,0.001141,-0.000300,0.000788,-0.002398,0.000944,0.000653,-0.001025,0.000566,-0.000578,-0.000032,-0.001079,0.000307,-0.000425,-0.000598,0.000802,0.000447,-0.000478,-0.001341,0.000481,0.001558,0.000417,0.000202,-0.000199,0.000350,-0.000854,0.000173,0.000105,-0.001860,0.000458,0.000140,-0.000065,0.000551,0.000352,0.000232,-0.001546,0.000407,-0.001154,0.000480,0.000668,0.000686,-0.000450,-0.000057,0.001175,-0.001046,-0.000703,0.000058,0.000757,0.000686,-0.000112,0.001356,0.000272,-0.000285,0.000387,-0.000344,-0.001266,-0.000155,-0.000126,-0.000799,-0.000193,0.000232,0.000874,-0.000328,0.000119,0.000711,-0.001044,-0.000051,-0.000340,0.000457,-0.001440,0.000542,-0.000632,-0.001482,0.000606,0.001152,0.000308,0.000521,-0.000122,0.001001,-0.000131,-0.000282,0.000000,0.000806,-0.000336,0.000639,0.000213,0.000891,-0.000095,-0.000316,0.000125,-0.000957,-0.001071,0.000029,-0.000692,0.000311,-0.000611,0.000350,0.000056,0.000308,0.000231,0.000343,-0.000430,-0.000330,-0.000271,0.001110,0.000417,-0.000346,0.000401,-0.000036,0.000334,-0.001415,-0.000304,-0.000577,0.000445,0.000511,-0.000449,0.000759,-0.000096,-0.000499,-0.000208,0.000161,0.000166,0.000394,0.000440,0.000071,0.000470,-0.000685,0.001152,-0.000234,-0.000718,-0.000040,-0.000077,0.000355,0.000372,-0.000283,-0.001671,-0.000382,0.000297,-0.000622,0.000392,0.000388,-0.000123,-0.000180,0.000220,0.000425,-0.000271,-0.000363,-0.001688,-0.000313,-0.000111,0.000904,-0.000170,0.000808,-0.000037,0.000464

回望日历天数 lookback:  360
Index([09:31:00, 09:32:00, 09:33:00, 09:34:00, 09:35:00, 09:36:00, 09:37:00, 09:38:00, 09:39:00, 09:40:00,
       ...
       14:51:00, 14:52:00, 14:53:00, 14:54:00, 14:55:00, 14:56:00, 14:57:00, 14:58:00, 14:59:00, 15:00:00], dtype='object', name='minute_slot', length=240)

minute_slot,09:31:00,09:32:00,09:33:00,09:34:00,09:35:00,09:36:00,09:37:00,09:38:00,09:39:00,09:40:00,09:41:00,09:42:00,09:43:00,09:44:00,09:45:00,09:46:00,09:47:00,09:48:00,09:49:00,09:50:00,09:51:00,09:52:00,09:53:00,09:54:00,09:55:00,09:56:00,09:57:00,09:58:00,09:59:00,10:00:00,10:01:00,10:02:00,10:03:00,10:04:00,10:05:00,10:06:00,10:07:00,10:08:00,10:09:00,10:10:00,10:11:00,10:12:00,10:13:00,10:14:00,10:15:00,10:16:00,10:17:00,10:18:00,10:19:00,10:20:00,10:21:00,10:22:00,10:23:00,10:24:00,10:25:00,10:26:00,10:27:00,10:28:00,10:29:00,10:30:00,10:31:00,10:32:00,10:33:00,10:34:00,10:35:00,10:36:00,10:37:00,10:38:00,10:39:00,10:40:00,10:41:00,10:42:00,10:43:00,10:44:00,10:45:00,10:46:00,10:47:00,10:48:00,10:49:00,10:50:00,10:51:00,10:52:00,10:53:00,10:54:00,10:55:00,10:56:00,10:57:00,10:58:00,10:59:00,11:00:00,11:01:00,11:02:00,11:03:00,11:04:00,11:05:00,11:06:00,11:07:00,11:08:00,11:09:00,11:10:00,11:11:00,11:12:00,11:13:00,11:14:00,11:15:00,11:16:00,11:17:00,11:18:00,11:19:00,11:20:00,11:21:00,11:22:00,11:23:00,11:24:00,11:25:00,11:26:00,11:27:00,11:28:00,11:29:00,11:30:00,13:01:00,13:02:00,13:03:00,13:04:00,13:05:00,13:06:00,13:07:00,13:08:00,13:09:00,13:10:00,13:11:00,13:12:00,13:13:00,13:14:00,13:15:00,13:16:00,13:17:00,13:18:00,13:19:00,13:20:00,13:21:00,13:22:00,13:23:00,13:24:00,13:25:00,13:26:00,13:27:00,13:28:00,13:29:00,13:30:00,13:31:00,13:32:00,13:33:00,13:34:00,13:35:00,13:36:00,13:37:00,13:38:00,13:39:00,13:40:00,13:41:00,13:42:00,13:43:00,13:44:00,13:45:00,13:46:00,13:47:00,13:48:00,13:49:00,13:50:00,13:51:00,13:52:00,13:53:00,13:54:00,13:55:00,13:56:00,13:57:00,13:58:00,13:59:00,14:00:00,14:01:00,14:02:00,14:03:00,14:04:00,14:05:00,14:06:00,14:07:00,14:08:00,14:09:00,14:10:00,14:11:00,14:12:00,14:13:00,14:14:00,14:15:00,14:16:00,14:17:00,14:18:00,14:19:00,14:20:00,14:21:00,14:22:00,14:23:00,14:24:00,14:25:00,14:26:00,14:27:00,14:28:00,14:29:00,14:30:00,14:31:00,14:32:00,14:33:00,14:34:00,14:35:00,14:36:00,14:37:00,14:38:00,14:39:00,14:40:00,14:41:00,14:42:00,14:43:00,14:44:00,14:45:00,14:46:00,14:47:00,14:48:00,14:49:00,14:50:00,14:51:00,14:52:00,14:53:00,14:54:00,14:55:00,14:56:00,14:57:00,14:58:00,14:59:00,15:00:00
trading_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-08-24,-0.001010,0.000273,0.000302,0.001289,-0.000028,-0.001486,-0.001523,-0.001569,-0.000498,-0.001364,0.000398,0.000604,-0.001150,-0.000564,-0.000780,0.000614,-0.000243,0.000146,0.000589,-0.000828,0.001488,-0.000598,-0.001086,-0.001317,-0.000686,-0.000045,0.000197,-0.001342,-0.000773,-0.000473,0.000063,0.000416,0.000991,-0.000274,-0.000578,0.001378,0.000382,0.000808,-0.000537,0.001752,-0.000565,-0.000911,-0.000825,-0.000154,0.000895,-0.000650,0.000637,0.000125,0.000049,-0.000536,0.000889,0.000478,-0.001050,-0.000974,0.001118,0.001009,-0.000800,-0.001040,-0.000993,-0.000322,-0.000170,0.001468,-0.000224,0.000838,-0.001671,0.000170,-0.000148,-0.000331,-0.000244,-0.000155,-0.000288,-0.000751,-0.001260,-0.001630,-0.000438,0.000843,-0.000846,-0.000312,0.000930,0.000000,-0.000192,-0.001359,0.000896,-0.000597,-0.000282,0.000654,-0.001212,0.000153,-0.000235,0.000095,-0.000499,0.000136,-0.000282,-0.000398,0.000300,-0.000327,-0.000797,0.002183,0.000611,-0.000031,-0.000098,-0.000789,0.000332,0.002068,0.000578,0.001548,-0.001118,0.000000,0.001344,-0.000582,-0.001783,-0.001135,-0.001977,0.000562,0.000519,0.001463,-0.001788,0.001276,0.000200,-0.000649,-0.000889,0.000218,-0.001008,-0.001246,-0.000425,0.002852,0.000920,0.000903,0.000190,-0.000763,-0.001203,-0.000168,0.000640,0.000074,-0.000789,-0.000176,-0.000268,-0.000066,-0.000067,-0.000136,-0.000233,-0.000975,0.000174,0.001884,0.000491,-0.001031,0.000037,-0.000759,-0.000419,0.000313,-0.000392,-0.000819,-0.000778,-0.000873,-0.000241,-0.000313,-0.000704,-0.000543,0.001278,0.000000,0.000171,0.000451,-0.000544,-0.000747,-0.001291,-0.000515,-0.000299,-0.000111,-0.001839,0.000305,-0.000537,-0.000481,0.000209,0.000782,0.000669,-0.000140,0.002054,0.000939,-0.001108,-0.001053,0.000245,0.000000,0.001419,-0.000028,0.001065,-0.000088,-0.001823,0.000373,0.002803,0.000572,0.001429,0.000095,-0.001082,0.002339,-0.001290,-0.001444,0.001799,0.001904,0.002009,-0.001777,0.001721,-0.002171,0.000457,0.001580,0.000619,0.000274,-0.000421,-0.001439,-0.000335,0.000847,-0.001702,-0.000500,0.000029,0.000509,0.000000,0.001103,0.001429,0.001501,-0.001871,0.000513,0.000113,0.000793,-0.002364,0.002576,-0.000159,0.001299,0.000666,0.000650,0.001769,0.000199,0.001414,-0.000892,0.001562,-0.000433,-0.000156,0.000797,0.000141,0.000129,-0.000377,-0.000045
2026-08-25,-0.001177,-0.000030,0.000960,0.000283,0.001598,-0.001266,0.000059,-0.001751,-0.001836,0.000930,-0.000745,0.001164,-0.000538,0.000092,-0.000640,-0.001871,-0.001352,0.001425,-0.000704,0.000481,-0.000261,0.002733,-0.000685,0.001557,0.000324,0.000826,0.002156,-0.000094,-0.001184,-0.000624,0.001143,-0.000199,0.002513,0.002825,0.000629,-0.000965,0.000096,-0.001722,0.001171,0.000665,-0.001082,-0.000560,-0.000080,0.001158,0.000238,-0.000125,0.001226,0.001371,0.000906,-0.001775,-0.000162,-0.000101,-0.001184,0.000976,0.000519,-0.002483,-0.001627,0.000174,-0.001174,-0.001184,0.000057,-0.000696,0.000727,0.000133,-0.001513,-0.000570,0.000179,0.001784,-0.000614,-0.000218,0.000322,-0.001321,-0.001620,-0.000790,0.000283,0.000090,-0.000220,0.000470,-0.000901,0.000833,-0.000584,-0.000821,0.000993,-0.000142,-0.000848,0.000784,-0.000911,-0.000924,-0.000034,-0.000256,0.000889,0.000355,0.000567,0.000430,-0.000060,0.000394,-0.000566,-0.000646,0.001376,-0.000062,0.000560,0.000858,0.000851,-0.001137,0.001343,-0.000538,-0.000534,-0.000598,0.000089,0.000370,-0.000793,0.000993,0.002087,-0.000819,0.001181,0.001125,-0.000032,0.000031,0.002034,-0.000486,0.003357,0.002233,-0.000368,0.000983,-0.000726,-0.000597,0.001025,0.002649,-0.000378,0.000631,-0.001616,0.000930,0.000697,0.003370,-0.000353,0.002157,-0.001652,-0.001273,-0.000560,0.001145,0.000844,-0.002348,0.001197,-0.000245,-0.000207,0.001003,-0.001837,0.000970,-0.001559,-0.000579,-0.000212,-0.000328,-0.000667,0.000165,-0.000684,0.001386,-0.000526,0.000845,0.000752,-0.002022,-0.001044,-0.001229,-0.000536,-0.000918,0.000100,0.000855,-0.000723,-0.001315,0.000033,0.000466,-0.000142,0.000101,0.000621,0.000334,0.000483,0.001170,-0.000974,-0.000444,-0.000217,0.000100,0.001643,-0.000527,0.000158,0.001648,-0.000083,-0.000557,0.000411,0.000606,-0.001330,0.000066,-0.000782,-0.000190,0.001130,0.000556,-0.000301,-0.000880,0.001546,0.001212,-0.000624,0.000359,0.000035,-0.000107,0.000448,0.000493,-0.000750,-0.001127,-0.000292,0.000376,-0.000399,-0.000514,0.001705,0.000000,-0.000057,0.001330,0.000412,-0.001998,0.000436,-0.001035,-0.000209,0.000366,0.000818,-0.000112,-0.001033,-0.000993,0.000274,0.000957,-0.000037,0.000322,-0.000897,0.000276,-0.000468,-0.000077,0.000775,0.000048,-0.000932,0.000891,-0.000893,-0.000857,-0.000125,-0.000532
2026-08-26,0.000154,-0.000637,0.000960,0.001380,0.000432,-0.001233,-0.000691,0.000000,-0.001162,0.001085,-0.000285,-0.000477,-0.000274,-0.000036,-0.000093,0.001036,0.002199,-0.000788,0.000342,0.000157,-0.001167,-0.000139,-0.000835,-0.000088,-0.000677,0.000748,-0.000777,-0.001320,-0.001044,-0.001128,-0.000146,-0.000613,-0.001740,0.000640,0.000277,0.000137,-0.000311,0.000279,0.001051,-0.000451,-0.000849,0.001319,0.000347,0.001540,0.000954,0.000075,0.000537,0.000546,-0.000610,0.000295,0.002563,0.000555,0.000470,0.000142,-0.000677,0.000059,0.000878,-0.001066,-0.001225,0.001539,0.001804,0.002482,0.000369,0.001510,0.000082,0.000444,-0.000652,0.001634,0.000209,0.001261,0.002577,0.000031,-0.000947,0.000911,-0.002570,-0.000029,-0.000185,-0.000185,-0.000033,0.001150,-0.000759,-0.000665,0.000539,-0.001302,-0.000552,0.000122,-0.000797,-0.000330,0.001063,-0.000218,-0.001331,0.000587,0.000530,0.000507,0.000326,0.000710,-0.001375,-0.000361,-0.000359,0.000916,0.000322,0.000433,-0.001130,-0.000720,0.001196,-0.000966,-0.000210,-0.000056,0.002137,-0.000575,0.000087,-0.000139,0.000030,-0.001462,0.001353,-0.000376,0.000187,-0.000183,-0.000591,-0.000510,-0.001025,0.000344,-0.001385,0.000435,-0.000750,-0.000760,0.000208,0.000212,0.000377,-0.000410,-0.001579,-0.000696,0.000569,0.000181,0.000670,-0.000906,0.000297,0.000812,-0.000688,-0.001774,-0.002223,0.000275,0.001199,0.000526,0.000139,0.000721,0.000501,0.000596,0.000034,-0.000616,0.000821,0.000658,0.000000,-0.001479,-0.000267,-0.001568,-0.001613,-0.000212,-0.000107,0.001311,0.000437,-0.000136,-0.000399,0.000366,0.000863,0.000316,0.000456,-0.000108,-0.000133,0.000066,-0.000036,-0.000442,0.000035,0.000033,0.000551,0.000720,0.000345,-0.000378,-0.002817,0.000268,0.000134,0.000476,-0.000395,0.000110,0.000276,-0.000533,-0.000382,0.000579,-0.001121,0.000331,0.001594,0.000511,0.000409,-0.000274,0.000468,0.000000,-0.000938,-0.000283,-0.000690,0.000294,-0.000173,0.000538,0.000896,0.000176,-0.000323,-0.000155,0.001510,0.001209,0.000470,0.000183,0.000738,0.000206,-0.001027,-0.000265,-0.000507,-0.000245,-0.000997,0.001205,-0.000417,0.000641,-0.000299,0.000038,-0.000802,0.000768,-0.000156,0.000221,-0.000878,-0.000040,0.000285,0.000315,-0.000623,-0.000192,0.000182,0.000143,-0.000310,0.000147,0.000047,-0.000043,-0.000166,0.001149
2026-08-27,-0.000401,0.000739,-0.000317,0.001395,-0.000704,-0.001095,-0.000541,0.000559,-0.000169,0.001143,-0.000594,-0.000474,-0.002824,0.001230,0.002273,0.001083,-0.001183,0.000990,0.000140,0.002123,-0.000289,0.000687,-0.000746,-0.000219,0.000105,0.001656,-0.001266,0.000250,-0.002038,-0.000693,0.000352,0.000543,0.000438,-0.000290,-0.000591,0.000561,-0.001230,0.001167,0.001539,0.001002,-0.000555,0.001419,0.000679,0.000402,-0.000495,0.000272,-0.001056,-0.000318,-0.000481,-0.000344,0.000768,-0.000648,0.000052,0.000113,-0.000509,-0.000087,0.001708,-0.000057,0.000973,-0.001089,-0.000809,0.000622,0.000586,-0.000052,0.002560,-0.000358,0.000987,-0.000088,0.001006,0.000945,-0.000437,-0.000397,0.000029,0.001862,-0.000394,0.000147,0.001470,-0.000428,0.001937,0.000502,0.002141,0.000131,-0.000857,0.000765,-0.000181,0.000995,-0.000467,-0.000975,0.001504,-0.001505,0.000397,-0.000603,0.000769,-0.000666,0.001301,-0.000953,0.000032,-0.000474,-0.000294,-0.000090,0.000189,-0.000275,0.000933,0.000321,0.001692,-0.000774,0.001192,-0.000277,0.001528,-0.000417,-0.001167,0.000328,-0.000240,0.001464,-0.000332,0.000879,0.000706,0.000482,-0.001074,-0.000250,-0.000664,-0.000021,0.000667,-0.000399,-0.000789,0.000607,0.000525,-0.000920,0.000185,-0.000371,0.000129,-0.001649,0.000587,0.002128,-0.000518,-0.000170,-0.001194,-0.001023,-0.000096,0.000130,0.000858,-0.000268,-0.000762,0.000788,0.001262,0.000352,-0.000139,-0.002261,-0.000471,0.000341,-0.000350,-0.000409,-0.001261,0.000291,0.000609,-0.000993,0.002095,0.000172,0.000000,-0.000486,0.000000,0.001232,0.000325,-0.000215,0.000487,0.000980,0.000000,-0.000249,0.000228,-0.001234,-0.000836,-0.000566,-0.000477,0.000590,-0.000710,-0.000067,-0.000235,0.000557,0.001200,0.000261,0.000237,-0.000515,0.000129,0.000861,0.000136,-0.000088,0.000086,-0.000359,0.000000,-0.000906,0.000000,-0.000806,0.000185,0.000068,0.001473,0.000364,-0.000073,0.000792,-0.000101,0.000129,-0.000068,0.000526,-0.000937,0.000517,0.000457,-0.000152,0.002160,0.000998,0.000071,0.001001,-0.000661,0.000405,-0.000196,0.000807,0.000556,-0.000717,0.000425,0.000100,0.000980,0.000493,0.000909,0.000329,-0.001153,-0.000427,0.001342,0.000181,-0.000396,0.000039,0.001148,-0.000460,0.000152,-0.000336,-0.000177,0.000140,0.000201,-0.000336,-0.000138,0.001582,-0.000404,-0.001247
2026-08-28,0.000889,0.000771,-0.000204,0.000941,-0.000415,0.000100,0.000493,0.000627,0.000030,-0.001330,-0.000289,-0.001031,0.000132,0.000196,0.001720,0.000036,0.000410,-0.000140,0.000254,0.001646,-0.000352,-0.000115,-0.001336,0.000150,0.000329,0.000919,-0.001025,0.001240,-0.000773,-0.000427,-0.000262,-0.000296,0.000135,-0.000523,0.000155,-0.000696,0.000115,0.000067,0.000733,-0.001890,0.000519,-0.000268,-0.000974,-0.000321,0.000489,0.000856,0.000118,-0.000767,-0.000331,0.000778,0.000984,0.000339,0.000177,-0.001434,-0.000210,0.000341,-0.000714,-0.000393,0.000960,-0.000225,-0.000982,0.000055,-0.000478,0.000662,0.000162,-0.000780,-0.000989,-0.000116,-0.000530,0.000389,-0.001260,0.001024,0.000450,-0.000698,0.000090,-0.000962,-0.000516,0.000091,-0.000160,0.000364,0.000797,0.000585,-0.002995,0.001114,0.000512,0.000333,0.001189,-0.000322,0.000804,-0.002259,0.000958,0.000729,-0.001083,0.000575,-0.000558,-0.000032,-0.001083,0.000324,-0.000468,-0.000623,0.000783,0.000426,-0.000466,-0.001214,0.000492,0.001593,0.000410,0.000221,-0.000200,0.000324,-0.000822,0.000163,0.000119,-0.001589,0.000469,0.000141,-0.000061,0.000541,0.000357,0.000218,-0.001698,0.000463,-0.001202,0.000451,0.000704,0.000743,-0.000494,-0.000059,0.001198,-0.001144,-0.000771,0.000065,0.000891,0.000671,-0.000103,0.001324,0.000258,-0.000318,0.000381,-0.000323,-0.001230,-0.000168,-0.000133,-0.000885,-0.000203,0.000221,0.001006,-0.000398,0.000134,0.000757,-0.001219,-0.000058,-0.000358,0.000449,-0.001469,0.000629,-0.000704,-0.001748,0.000665,0.001247,0.000360,0.000564,-0.000130,0.001000,-0.000129,-0.000275,0.000000,0.000892,-0.000358,0.000614,0.000206,0.000948,-0.000100,-0.000325,0.000134,-0.000902,-0.001132,0.000031,-0.000696,0.000259,-0.000577,0.000366,0.000051,0.000268,0.000217,0.000349,-0.000373,-0.000299,-0.000291,0.001065,0.000402,-0.000342,0.000368,-0.000034,0.000329,-0.001350,-0.000294,-0.000517,0.000439,0.000516,-0.000442,0.000700,-0.000100,-0.000515,-0.000211,0.000190,0.000163,0.000399,0.000430,0.000072,0.000481,-0.000559,0.000873,-0.000231,-0.000742,-0.000034,-0.000065,0.000302,0.000373,-0.000263,-0.001522,-0.000329,0.000261,-0.000643,0.000385,0.000370,-0.000109,-0.000158,0.000199,0.000423,-0.000266,-0.000337,-0.001290,-0.000281,-0.000101,0.000729,-0.000138,0.000752,-0.000041,0.000428

#### Cell 11：整理各窗口的分钟结果，保留 RV／BPV 类型标记。

In [43]:
output_index = pd.MultiIndex.from_product(
    [trading_dates, minute_slots],
    names=["trading_date", "minute_slot"],
)

base_output_df = minute_df.set_index(
    ["trading_date", "minute_slot"]
)[[
    "contract_code", "session_number", "bar_at",
    "log_return", "bpv_contribution", "variance_contribution",
]].reindex(output_index)

base_output_df["contribution_method"] = np.where(
    output_index.get_level_values("minute_slot").isin([
        dt.time(9, 31), dt.time(13, 1),
    ]),
    "rv_open",
    "bpv",
)

output_by_lookback = {}

for lookback in lookback_windows:
    output_df = base_output_df.copy()
    output_df["lookback_trading_days"] = lookback

    output_df["variance_seasonality"] = (
        seasonality_by_lookback[lookback].to_numpy().ravel()
    )
    output_df["variance_adjusted"] = (
        variance_adjusted_by_lookback[lookback].to_numpy().ravel()
    )
    output_df["volatility_seasonality"] = (
        volatility_seasonality_by_lookback[lookback].to_numpy().ravel()
    )
    output_df["return_adjusted"] = (
        return_adjusted_by_lookback[lookback].to_numpy().ravel()
    )

    output_by_lookback[lookback] = output_df.reset_index()

In [46]:
print(output_by_lookback.keys())
for key, value in  output_by_lookback.items():
    print("回望日历天数 lookback: ", key)
    print(value.columns)
    display(value.tail())

dict_keys([30, 60, 120, 360])
回望日历天数 lookback:  30
Index(['trading_date', 'minute_slot', 'contract_code', 'session_number', 'bar_at', 'log_return', 'bpv_contribution', 'variance_contribution', 'contribution_method', 'lookback_trading_days', 'variance_seasonality', 'variance_adjusted', 'volatility_seasonality', 'return_adjusted'], dtype='str')

       trading_date minute_slot contract_code  session_number                     bar_at  log_return  bpv_contribution  variance_contribution contribution_method  lookback_trading_days  variance_seasonality  variance_adjusted  volatility_seasonality  return_adjusted
238795   2026-08-28    14:56:00   IM2609.CCFX               2  2026-08-28 14:56:00+08:00    0.000392      3.212797e-08           3.212797e-08                 bpv                     30              0.182146       1.763859e-07                0.426786         0.000918
238796   2026-08-28    14:57:00   IM2609.CCFX               2  2026-08-28 14:57:00+08:00   -0.000078      4.817623e-08           4.817623e-08                 bpv                     30              0.146668       3.284703e-07                0.382973        -0.000204
238797   2026-08-28    14:58:00   IM2609.CCFX               2  2026-08-28 14:58:00+08:00    0.000470      5.779111e-08           5.779111e-08                 bpv                     30              0.256475       2.253281e-07                0.506434         0.000928
238798   2026-08-28    14:59:00   IM2609.CCFX               2  2026-08-28 14:59:00+08:00   -0.000026      1.925566e-08           1.925566e-08                 bpv                     30              0.405001       4.754477e-08                0.636397        -0.000041
238799   2026-08-28    15:00:00   IM2609.CCFX               2  2026-08-28 15:00:00+08:00    0.000261      1.069396e-08           1.069396e-08                 bpv                     30              0.302907       3.530447e-08                0.550370         0.000474

回望日历天数 lookback:  60
Index(['trading_date', 'minute_slot', 'contract_code', 'session_number', 'bar_at', 'log_return', 'bpv_contribution', 'variance_contribution', 'contribution_method', 'lookback_trading_days', 'variance_seasonality', 'variance_adjusted', 'volatility_seasonality', 'return_adjusted'], dtype='str')

       trading_date minute_slot contract_code  session_number                     bar_at  log_return  bpv_contribution  variance_contribution contribution_method  lookback_trading_days  variance_seasonality  variance_adjusted  volatility_seasonality  return_adjusted
238795   2026-08-28    14:56:00   IM2609.CCFX               2  2026-08-28 14:56:00+08:00    0.000392      3.212797e-08           3.212797e-08                 bpv                     60              0.186212       1.725343e-07                0.431523         0.000908
238796   2026-08-28    14:57:00   IM2609.CCFX               2  2026-08-28 14:57:00+08:00   -0.000078      4.817623e-08           4.817623e-08                 bpv                     60              0.180255       2.672666e-07                0.424565        -0.000184
238797   2026-08-28    14:58:00   IM2609.CCFX               2  2026-08-28 14:58:00+08:00    0.000470      5.779111e-08           5.779111e-08                 bpv                     60              0.289930       1.993279e-07                0.538451         0.000872
238798   2026-08-28    14:59:00   IM2609.CCFX               2  2026-08-28 14:59:00+08:00   -0.000026      1.925566e-08           1.925566e-08                 bpv                     60              0.332926       5.783770e-08                0.576997        -0.000045
238799   2026-08-28    15:00:00   IM2609.CCFX               2  2026-08-28 15:00:00+08:00    0.000261      1.069396e-08           1.069396e-08                 bpv                     60              0.285894       3.740538e-08                0.534690         0.000488

回望日历天数 lookback:  120
Index(['trading_date', 'minute_slot', 'contract_code', 'session_number', 'bar_at', 'log_return', 'bpv_contribution', 'variance_contribution', 'contribution_method', 'lookback_trading_days', 'variance_seasonality', 'variance_adjusted', 'volatility_seasonality', 'return_adjusted'], dtype='str')

       trading_date minute_slot contract_code  session_number                     bar_at  log_return  bpv_contribution  variance_contribution contribution_method  lookback_trading_days  variance_seasonality  variance_adjusted  volatility_seasonality  return_adjusted
238795   2026-08-28    14:56:00   IM2609.CCFX               2  2026-08-28 14:56:00+08:00    0.000392      3.212797e-08           3.212797e-08                 bpv                    120              0.187851       1.710293e-07                0.433417         0.000904
238796   2026-08-28    14:57:00   IM2609.CCFX               2  2026-08-28 14:57:00+08:00   -0.000078      4.817623e-08           4.817623e-08                 bpv                    120              0.211873       2.273824e-07                0.460297        -0.000170
238797   2026-08-28    14:58:00   IM2609.CCFX               2  2026-08-28 14:58:00+08:00    0.000470      5.779111e-08           5.779111e-08                 bpv                    120              0.337923       1.710183e-07                0.581312         0.000808
238798   2026-08-28    14:59:00   IM2609.CCFX               2  2026-08-28 14:59:00+08:00   -0.000026      1.925566e-08           1.925566e-08                 bpv                    120              0.486242       3.960097e-08                0.697311        -0.000037
238799   2026-08-28    15:00:00   IM2609.CCFX               2  2026-08-28 15:00:00+08:00    0.000261      1.069396e-08           1.069396e-08                 bpv                    120              0.316751       3.376140e-08                0.562806         0.000464

回望日历天数 lookback:  360
Index(['trading_date', 'minute_slot', 'contract_code', 'session_number', 'bar_at', 'log_return', 'bpv_contribution', 'variance_contribution', 'contribution_method', 'lookback_trading_days', 'variance_seasonality', 'variance_adjusted', 'volatility_seasonality', 'return_adjusted'], dtype='str')

       trading_date minute_slot contract_code  session_number                     bar_at  log_return  bpv_contribution  variance_contribution contribution_method  lookback_trading_days  variance_seasonality  variance_adjusted  volatility_seasonality  return_adjusted
238795   2026-08-28    14:56:00   IM2609.CCFX               2  2026-08-28 14:56:00+08:00    0.000392      3.212797e-08           3.212797e-08                 bpv                    360              0.288427       1.113901e-07                0.537054         0.000729
238796   2026-08-28    14:57:00   IM2609.CCFX               2  2026-08-28 14:57:00+08:00   -0.000078      4.817623e-08           4.817623e-08                 bpv                    360              0.321600       1.498017e-07                0.567098        -0.000138
238797   2026-08-28    14:58:00   IM2609.CCFX               2  2026-08-28 14:58:00+08:00    0.000470      5.779111e-08           5.779111e-08                 bpv                    360              0.389821       1.482505e-07                0.624356         0.000752
238798   2026-08-28    14:59:00   IM2609.CCFX               2  2026-08-28 14:59:00+08:00   -0.000026      1.925566e-08           1.925566e-08                 bpv                    360              0.415086       4.638954e-08                0.644272        -0.000041
238799   2026-08-28    15:00:00   IM2609.CCFX               2  2026-08-28 15:00:00+08:00    0.000261      1.069396e-08           1.069396e-08                 bpv                    360              0.372116       2.873824e-08                0.610013         0.000428

#### Cell 12：定义输出 Schema，注明“首分钟 RV 项＋其余分钟 BV 求和项”的混合口径。

现有字段 `variance_seasonality` 表示 $\widehat g^{\mathrm{mix},(L)}$，
`volatility_seasonality` 表示其平方根；Schema 中保留的
`seasonality_scale=variance` 是旧标签，不构成该因子等于收益方差周期 $f^2$ 的证明。
字段名称、Schema 与既有输出沿用当前实现，统计含义以上述定义为准。

In [48]:
output_schema = pa.schema([
    pa.field("trading_date", pa.date32(), nullable=False),
    pa.field("minute_slot", pa.time64("us"), nullable=False),
    pa.field("lookback_trading_days", pa.int16(), nullable=False),
    pa.field("contract_code", pa.string()),
    pa.field("session_number", pa.int8()),
    pa.field("bar_at", pa.timestamp("us", tz="Asia/Shanghai")),
    pa.field("contribution_method", pa.string(), nullable=False),

    *[
        pa.field(column, pa.float64())
        for column in [
            "log_return",
            "bpv_contribution",
            "variance_contribution",
            "variance_seasonality",
            "variance_adjusted",
            "volatility_seasonality",
            "return_adjusted",
        ]
    ],
], metadata={
    b"primary_key": b"trading_date,minute_slot",
    b"contribution_method": b"RV at 09:31 and 13:01; BPV elsewhere within session",
    b"seasonality_scale": b"variance",
    b"estimation": b"daily normalization; shift(1); rolling median; mean normalization",
    b"source_file": source_path.name.encode("utf-8"),
})

In [49]:
for lookback in lookback_windows:
    window_schema = output_schema.with_metadata({
        **output_schema.metadata,
        b"lookback_trading_days": str(lookback).encode("utf-8"),
    })

    output_table = pa.Table.from_pandas(
        output_by_lookback[lookback][window_schema.names],
        schema=window_schema,
        preserve_index=False,
    )

    output_path = (
        research_dir / f"im_bpv_seasonality_1m_{lookback}td.parquet"
    )
    temporary_output_path = output_path.with_suffix(".parquet.tmp")

    pq.write_table(output_table, temporary_output_path, compression="zstd")
    temporary_output_path.replace(output_path)

    print(f"已保存：{output_path.name}")

已保存：im_bpv_seasonality_1m_30td.parquet
已保存：im_bpv_seasonality_1m_60td.parquet
已保存：im_bpv_seasonality_1m_120td.parquet
已保存：im_bpv_seasonality_1m_360td.parquet